Repository dotnet/docfx, pull requests merged in 2019-12, with the labels that each got.

#5329 Drop overwrite config
  docs/specs/config.yml
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/OverwriteConfigIdentifier.cs
  test/docfx.Test/build/ConfigTest.cs
Labels: v3

#5330 Add config.updateCommitBuildTime to disable saving build_history.json for PR
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/Config.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
Labels: v3

#5328 Replace GithubUserCache with non-blocking JsonDiskCache
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/LinkResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ContributionInfo.cs
  src/docfx/build/page/Contributor.cs
  src/docfx/lib/RandomUtility.cs
  src/docfx/lib/cache/ICacheObject{TKey}.cs
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/github/GitHubQueries.cs
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/github/GitHubUserCacheFile.cs
  src/docfx/lib/log/PerfScope.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphUser.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/restore/RestoreFile.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
  test/docfx.Test/lib/GitUtilityTest.cs
  test/docfx.Test/lib/JsonDiskCacheTest.cs
Labels: v3

#5332 Drop config file loc fallback
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/InputUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFileMap.cs
Labels: v3

#5324 142096 code extension
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2, v3

#5335 🐞Fix github-api-failed for vsts repos
  src/docfx/lib/github/GitHubAccessor.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#5333 ⚒Refine localization
  docs/specs/git.yml
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/localization/LocalizationProvider.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5331 Control config using environment variables
  src/docfx/cli/Docfx.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/StringUtility.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/docfx.test.yml
Labels: v3

#5336 🐛verify output path
  docs/specs/legacy.yml
  src/docfx/build/context/Output.cs
  src/docfx/build/legacy/LegacyUtility.cs
Labels: v3

#5337 [Breaking] Detect loc sxs from branch name
  docs/specs/git.yml
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/localization/LocalizationMapping.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#5340 Fix SplitUrl trimming end '/'
  docs/specs/redirection.yml
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/lib/UrlUtility.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#5334 ⚒ Consolidate config load with FileResolver
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFileMap.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5338 [Breaking] Retrieve OPS docset info
  azure-pipelines-v3.yml
  docs/specs/config.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
  src/docfx/restore/FileResolver.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5345 [Breaking] Move fallback error filtering to docfx
  docs/specs/legacy.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#5341 correctly find regions in xml based files
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/TripleSlashParserUnitTest.cs
Labels: v2

#5348 release 2.48
  RELEASENOTE.md
Labels: v2

#5349 PublishModel contains baseUrl
  docs/specs/output.yml
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5350 Turn circular-reference and include-not-found into error
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/output.yml
  docs/specs/resolve.yml
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#5353 fix cardF className
  src/Microsoft.Docs.Template/Views/Template/BuildItemListPartial.cshtml
Labels: v3

#5351 Explicitly control which docsets to build
  docs/designs/multiple-docsets.md
  docs/specs/config.yml
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/config/AppData.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/DocsetsConfig.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/PathUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#5355 update spec
  docs/designs/link-output.md
Labels: v3

#5346 [Breaking] Support docfx.json
  docs/specs/config.yml
  src/docfx/config/ConfigLoader.cs
Labels: v3

#5352 Pass basePath in publish model instead of baseUrl
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/output.yml
  docs/specs/redirection.yml
  docs/specs/xref.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/Document.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#5357 🚢🚢🚢
  azure-pipelines-v3.yml
  docs/designs/link-output.md
  docs/designs/multiple-docsets.md
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/output.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  docs/specs/xref.yml
  src/Microsoft.Docs.Template/Views/Template/BuildItemListPartial.cshtml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/Document.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/DocsetsConfig.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/PathUtilityTest.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5358 👷‍♀️ Add OpsMetadataRuleConverter
  src/docfx/config/ops/OpsMetadataRule.cs
  src/docfx/config/ops/OpsMetadataRuleConverter.cs
  test/docfx.Test/build/OpsMetadataRuleConverterTest.cs
  test/docfx.Test/build/XrefMapLoaderTest.cs
  test/docfx.Test/data/validation/allowlists.json
  test/docfx.Test/data/validation/rulesets.json
  test/docfx.Test/data/validation/schema.json
Labels: v3

#5359 Skip unprovision docsets
  docs/specs/config.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5360 Decouple validation from markdig extensions
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Validation/MarkdownObjectRewriterFactory.cs
  src/Microsoft.DocAsCode.MarkdigEngine/Validation/MarkdownObjectValidatorAdapter.cs
Labels: v2

#5356 [Breaking] Move validation, moniker definition config to docfx
  docs/specs/config.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/data/schemas/OpsMetadata.json
  src/docfx/lib/log/ErrorLevel.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateSchema.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5363 Support Resource config as part of build scope
  docs/specs/config.yml
  docs/specs/schema.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/document/DocumentProvider.cs
Labels: v3

#5365 Throw dowload-failed error when ops call failed
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5374 no need to set default locale for build in OPS
  src/docfx/config/ops/OpsConfigAdapter.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5369 Use extend config to restore ops service config
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5373 support LandingDataType `Grid`
  docs/specs/landingData.yml
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/Microsoft.Docs.Template/Views/Template/LandingData.cshtml
Labels: v3

#5366 fix: changed post processor manager to use updatedMetadata
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/PostProcessorsManager.cs
Labels: v2

#5375 Ignore git merge conflict marker inside code blocks
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/MergeConflict.cs
Labels: v3

#5377 update according to code
  docs/designs/dependency-repository.md
Labels: v3

#5379 [Breaking] Pass op build user token using http header
  docs/specs/config.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/git/MergeConflict.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5376 Add ConfigMonikerRange to publish model
  docs/specs/moniker.yml
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/publish/PublishItem.cs
Labels: v3

#5380 Output config base path as it is
  docs/specs/output.yml
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/Config.cs
  src/docfx/lib/path/BasePath.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5383 Support reading config from stdin with --stdin command line option
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
Labels: v3

#5385 refactor: one method to gather git dependencies
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#5368 [breaking]Consume ops xref api
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
Labels: v3

#5384 Publish docfx binary packages
  README.md
  azure-pipelines-v3.yml
  build.ps1
Labels: v3

#5389 Fix sandbox storage account name
  azure-pipelines-v3.yml
Labels: v3

#5388 Look up remote commit in case a branch does not have a local tracking branch
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#5382 fix: VisualStudioVersion including minor version breaks UWP project
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs
Labels: v2

#5391 fix: Fetch loc live branch to generate the correct contributor list
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#5392 Fetch git dependencies with --depth 1
  docs/specs/restore.yml
  src/docfx/Errors.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/DependencyConfig.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitFlags.cs
  src/docfx/restore/RestoreGitMap.cs
Labels: v3

#5393 Use updated_at to represent when a cache entry will expire
  docs/specs/validation.yml
  src/docfx/lib/cache/ICacheObject{TKey}.cs
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/msgraph/MicrosoftGraphUser.cs
  test/docfx.Test/lib/JsonDiskCacheTest.cs
Labels: v3

#5399 Fix pack binary
  build.ps1
Labels: v3

#5400 refactor: Clean up dependencies on `IsBranchRestored` and `DependencyLockProvider.ListAll`
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/config/AppData.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
Labels: v3

#5403 Add union properrty option for Json merge
  docs/specs/xref.yml
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5404 🚢🚢
  build.ps1
  docs/specs/xref.yml
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/AppData.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5406 fix xref restore for share base path repo
  src/docfx/config/ops/OpsConfigAdapter.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5407 Using win7-x64 as rid for windows package
  build.ps1
Labels: v3

#5408 🚢🚢
  build.ps1
  src/docfx/config/ops/OpsConfigAdapter.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5409 fix for xref restore order
  docs/specs/xref.yml
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5411 return null when get 404 from xref map API
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5412 🚢🚢
  docs/specs/xref.yml
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5413 Add external links to .links.json
  docs/specs/output.yml
  src/docfx/lib/markdown/LinkExtension.cs
Labels: v3
