Repository dotnet/docfx, pull requests merged in 2019-09, with the labels that each got.

#5052 Enable Microsoft.DocAsTest to be used as a nuget Package
  build.ps1
  src/Microsoft.DocAsTest/JsonDiff/JsonDiff.cs
  src/Microsoft.DocAsTest/JsonDiff/JsonDiffException.cs
  src/Microsoft.DocAsTest/Microsoft.DocAsTest.csproj
  src/Microsoft.DocAsTest/TestAdapter.cs
  src/Microsoft.DocAsTest/build/netstandard2.0/Microsoft.DocAsTest.props
  test/Microsoft.DocAsTest.NuGetTest/Microsoft.DocAsTest.NuGetTest.csproj
  test/Microsoft.DocAsTest.NuGetTest/NuGetTest.cs
  test/Microsoft.DocAsTest.NuGetTest/data/foo.md
  test/docfx.Test/TestUtility.cs
Labels: v3

#5056 Take zip file as external xref source
  docs/specs/xref.yml
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  test/docfx.Test/TestUtility.cs
Labels: v3

#5058 support @ symbol in toc title
  docs/specs/toc.yml
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
Labels: v3

#5034 📨 Add a basic input abstraction
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  src/docfx/Errors.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathUtility.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5057 MarkdownContext extends logger
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/ValidationTest.cs
Labels: v2

#5059 Optimize unnecessary calculation
  src/docfx/lib/path/PathUtility.cs
Labels: v3

#5044 flatten restored git lock and only restore first level dependencies
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitFlags.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/RestoreGitResult.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5063 🚢🚢🚢
  build.ps1
  docs/specs/git.yml
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/Microsoft.DocAsTest/JsonDiff/JsonDiff.cs
  src/Microsoft.DocAsTest/JsonDiff/JsonDiffException.cs
  src/Microsoft.DocAsTest/Microsoft.DocAsTest.csproj
  src/Microsoft.DocAsTest/TestAdapter.cs
  src/Microsoft.DocAsTest/build/netstandard2.0/Microsoft.DocAsTest.props
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitFlags.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/RestoreGitResult.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  test/Microsoft.DocAsTest.NuGetTest/Microsoft.DocAsTest.NuGetTest.csproj
  test/Microsoft.DocAsTest.NuGetTest/NuGetTest.cs
  test/Microsoft.DocAsTest.NuGetTest/data/foo.md
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/TestUtility.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5064 Content validation: extend logger
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#5066 Add test for filemetadata should overwrite H1
  docs/specs/metadata.yml
Labels: v3

#5065 support file groups
  docs/specs/config.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/config/Config.cs
  src/docfx/config/FileGroupConfig.cs
  src/docfx/lib/json/YamlUtility.cs
Labels: v3

#5067 docs: add SECURITY.md
  SECURITY.MD
Labels: v2

#5071 Remove host name if sharing with referencing xref
  docs/specs/xref.yml
  src/docfx/build/xref/XrefResolver.cs
Labels: v3

#5072 xref zip file loading order
  docs/specs/xref.yml
  src/docfx/build/xref/ExternalXrefMapLoader.cs
Labels: v3

#5073 Resolving monikerzone in token should base on root file's moniker
  docs/specs/moniker.yml
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#5047 support redirection url with bookmark and query
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#5078 🚢🚢
  docs/specs/config.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/Config.cs
  src/docfx/config/FileGroupConfig.cs
  src/docfx/docfx.csproj
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#5051 docs: fix bad command line in templates page
  Documentation/templates-and-plugins/templates-dashboard.yml
Labels: v2

#5070 support content in CRR(dependency) repositories
  docs/specs/localization.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/Config.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/DependencyPackageUrl.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5080 fix typo in PDF cover page template
  src/docfx.website.themes/pdf.default/cover.html.primary.tmpl
Labels: v2

#5061 Make RestoreGitMap.DependencyGitLock and docsetPath private
  src/docfx/build/Build.cs
  src/docfx/build/context/Input.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5081 Split cache path from state path
  docs/specs/git.yml
  src/docfx/config/AppData.cs
  src/docfx/config/EnvironmentVariable.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3

#5083 fix(search): seperator to separator
  src/docfx.website.themes/default/styles/search-worker.js
Labels: v2

#5084 remove host name for review
  docs/specs/xref.yml
  src/docfx/build/xref/XrefResolver.cs
Labels: v3

#5069 extend image Docs Markdown extension to support icons
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ChromelessFormExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonBlock.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ZoneExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/ImageTest.cs
Labels: v2

#5060 design spec for using content in CRR
  docs/designs/dependency-repository.md
  docs/specs/restore.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5086 feat(xref): stablize xref zip resolve order
  src/Microsoft.DocAsCode.DataContracts.Common/ExternalReferences/ExternalReferencePackageCollection.cs
Labels: v2

#5087 Revert "zip file loading order (#5072)"
  docs/specs/xref.yml
  src/docfx/build/xref/ExternalXrefMapLoader.cs
Labels: v3

#5088 🚢🚢
  docs/designs/dependency-repository.md
  docs/specs/git.yml
  docs/specs/localization.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/DependencyPackageUrl.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5090 hide dependency lock model from build and restore
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
Labels: v3

#5089 allow style attribute in table
  docs/specs/markdown.yml
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5092 Add test to verify git url and contributor info for CRR build content
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#5094 Reserve xref map order
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/XRefMaps/XRefCollection.cs
Labels: v2

#5030 Directly resolve link/content from dependency git without checking out
  docs/specs/casing.yml
  docs/specs/localization.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/config/AppData.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/lib/process/SharedAndExclusiveLock.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/index/DependencyGit.cs
  src/docfx/restore/index/DependencySlot.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/template/TemplateEngine.cs
  src/stylecop.ruleset
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5105 _tocRel prioritized by filepath
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#5104 refine git contribution for CRR content
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#5098 Refine url merge
  docs/specs/escape.yml
  docs/specs/markdown.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#5109 🚢🚢🚢
  docs/specs/casing.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/restore.yml
  docs/specs/toc.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/AppData.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PackageUrl.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/lib/process/SharedAndExclusiveLock.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/index/DependencyGit.cs
  src/docfx/restore/index/DependencySlot.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  src/stylecop.ruleset
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5111 filemetadata and global metadata should also be applied to redirection file and resource file
  docs/specs/moniker.yml
  src/docfx/build/metadata/MetadataProvider.cs
Labels: v3

#5110 rename extendToBuild
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/config/DependencyPackageUrl.cs
Labels: v3

#5062 output for links design spec
  docs/designs/link-output.md
Labels: v2, v3

#5099 Improve logging of template preprocessor errors
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Preprocessors/PreprocessorWithResourcePool.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Preprocessors/TemplateJintPreprocessor.cs
Labels: v2

#5108 try use file share and access to implement reader and writer lock
  src/docfx/lib/process/InterProcessReaderWriterLock.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/lib/process/SharedAndExclusiveLock.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#5113 Handle AbandonedMutexException
  src/docfx/lib/process/InterProcessMutex.cs
  src/docfx/lib/process/InterProcessReaderWriterLock.cs
Labels: v3

#4989 Adding support for notebook python code with markup notebook-python
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippet.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/CodeSnippetTest.cs
Labels: v2, v3

#5115 build: upgrade package Microsoft.DocAsCode.MarkdigEngine.Extensions to latest prereleased version
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/restore.yml
  src/docfx/docfx.csproj
Labels: v3

#5114 Add content validation extension
  NuGet.config
  docs/specs/validation.yml
  src/docfx/build/context/Context.cs
  src/docfx/config/Config.cs
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/validation/ContentValidationContext.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/lib/markdown/validation/ContentValidationLogger.cs
  src/docfx/restore/RestoreFile.cs
  src/stylecop.ruleset
Labels: v3

#5120 MarkdownUtility --> MarkdownEngine
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5123 Improve readability.
  Documentation/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.md
Labels: v2

#5119 monikers of external link/absolute link/non-versioning page node should be null
  docs/designs/conceptual-versioning.md
  docs/specs/moniker.yml
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#5121 support '#' in PackageUrl.url
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Input.cs
  src/docfx/config/DependencyPackageUrl.cs
  src/docfx/lib/path/PackageType.cs
  src/docfx/lib/path/PackageUrl.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5125 🐛 fix bug of calculating commits for bare crr repo
  docs/specs/git.yml
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
Labels: v3

#5129 fix bug of copying resource from crr
  docs/specs/restore.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/context/Output.cs
Labels: v3

#5093 fix: get token from resource to avoid duplicate warnings
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateProcessor.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateProcessorUtility.cs
Labels: v2

#5000 Update docfx_flavored_markdown.md
  Documentation/spec/docfx_flavored_markdown.md
Labels: v2

#5124 output .links.json
  docs/specs/output.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/xref/XrefResolver.cs
Labels: v3

#5130 nearest toc calculation
  docs/specs/toc.yml
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#5131 stablize .links.json
  docs/specs/output.yml
  src/docfx/build/link/FileLinkMapBuilder.cs
Labels: v3

#5133 Include pdb and source repo url in nuget package
  src/Directory.Build.props
Labels: v3

#5138 fix bug of file map for crr content
  docs/specs/restore.yml
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
Labels: v3

#5126 build redirection file with versioning info
  docs/specs/moniker.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#5139 Treat content output as required output
  docs/specs/moniker.yml
  docs/specs/output.yml
  docs/specs/restore.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/Microsoft.DocAsTest/JsonDiff/JsonDiffExtensions.cs
  src/Microsoft.DocAsTest/TestAdapter.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5141 build: upgrade package Microsoft.DocAsCode.MarkdigEngine.Extensions to latest prereleased version
  src/docfx/docfx.csproj
Labels: v3

#5142 Path in FilePath represents `path to main docset`
  docs/specs/localization.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/path/FilePath.cs
Labels: v3

#5118 refine repository and config loader
  docs/specs/config.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/config/AppData.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/RepositoryProvider.cs
  src/docfx/lib/InputUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFileMap.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5140 Extract MarkdigEngine.Extensions.Tests
  docfx.sln
  test/Microsoft.DocAsCode.Build.Common.Tests/FileLinkInfoTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/AggregatorTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ChromelessFormsTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeSnippetTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/EmojiTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/GeneralTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/InteractiveCodeTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/LineNumberTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/MathematicsTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests.csproj
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/MonikerRangeTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/NolocTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/QuoteSectionNoteTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/RenderZoneTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/RowsTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/TabGroupTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/TestUtility.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/TripleColonTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/XrefTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InteractiveCode/sample.code
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/NolocTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/RenderZoneTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/TripleColonTest.cs
Labels: v2, v3

#5136 update versioning-related error code
  docs/specs/legacy.yml
  docs/specs/moniker.yml
  docs/specs/output.yml
  src/docfx/Errors.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5128 Improves the default template for TypeScript documentation
  src/Microsoft.DocAsCode.Build.UniversalReference/BuildOutputs/ApiBuildOutput.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/BuildOutputs/ApiInheritanceTreeBuildOutput.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/BuildOutputs/ApiLanguageValuePairWithLevel.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/ModelConverter/ApiBuildOutputProfile.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/ModelConverter/ModelConverter.cs
  src/Microsoft.DocAsCode.DataContracts.UniversalReference/ItemViewModel.cs
  src/docfx.website.themes/common/ManagedReference.common.js
  src/docfx.website.themes/common/UniversalReference.common.js
  src/docfx.website.themes/common/partials/namespaceSubtitle.tmpl.partial
  src/docfx.website.themes/default/UniversalReference.html.primary.tmpl
  src/docfx.website.themes/default/partials/title.tmpl.partial
  src/docfx.website.themes/default/partials/uref/class.header.tmpl.partial
  src/docfx.website.themes/default/partials/uref/class.tmpl.partial
  src/docfx.website.themes/default/partials/uref/inheritance.tmpl.partial
  src/docfx.website.themes/default/partials/uref/namespace.tmpl.partial
  src/docfx.website.themes/default/token.json
Labels: v2

#5146 no need to prepend dependency name to path when globing build scope
  docs/specs/restore.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/lib/path/FilePath.cs
Labels: v3

#5147 use IReadOnlyCollection for monikers output
  docs/specs/moniker.yml
  src/docfx/Errors.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/SystemMetadata.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MonikerZoneExtension.cs
  src/docfx/lib/moniker/MonikerUtility.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5145 Update validations docfx adapter NuGet package
  src/docfx/docfx.csproj
Labels: v3

#5143 Move Error log inside build and restore
  src/docfx/build/Build.cs
  src/docfx/cli/Docfx.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/Log.cs
  src/docfx/lib/process/InterProcessMutex.cs
  src/docfx/lib/process/InterProcessReaderWriterLock.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/lib/ErrorLogTest.cs
Labels: v3

#5150 DependencyResolver --> LinkResolver
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/LinkResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5151 PackageUrl --> PackagePath
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/Config.cs
  src/docfx/config/DependencyConfig.cs
  src/docfx/docset/RepositoryProvider.cs
  src/docfx/lib/path/PackagePath.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5134 Removed an inaccurate warning for image-end
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
Labels: v2, v3

#5102 Add multiple docsets spec
  docs/designs/multiple-docsets.md
Labels: v3

#5153 Implement basic multiple docsets support
  docs/designs/multiple-docsets.md
  docs/specs/localization.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3
