Repository dotnet/docfx, pull requests merged in 2019-07, with the labels that each got.

#4807 Make error immutable
  docs/specs/config.yml
  src/docfx/build/Build.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/cli/Docfx.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#4808 check isdata from template dir
  docs/specs/schema.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/config/Config.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateSchema.cs
  test/docfx.Test/data/template/ContentTemplate/schemas/LandingData.schema.json
Labels: v3

#4812 Only produce XrefNotFound error from XrefMap
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  src/docfx/lib/markdown/XrefExtension.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4817 GetRelativeUrl should handle fragment and query
  docs/specs/resolve.yml
  src/docfx/lib/UrlUtility.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#4814 query in xref should be carried to output href
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
  src/Microsoft.DocAsCode.Common/UriUtility.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
Labels: v2

#4819 🚢🚢🚢
  docs/specs/resolve.yml
  src/docfx/lib/UrlUtility.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#4813 Rework markdown TOC parser
  docs/specs/markdown.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4816 refine build page data flow for conceptual and sdp
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputMetadata.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#4821 JsonSchema: minProperties and maxProperties
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4825 fix: link to Docs Portal
  src/docfx/Errors.cs
Labels: v3

#4831 Fix bug of restoring latest file content
  src/docfx/restore/RestoreFile.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4827 clean up code of netcore sdk support
  README.md
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs
Labels: v2

#4822 JsonSchema: propertyNames
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4833 Make Document comparable
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/docset/Document.cs
Labels: v3

#4832 Uid conflict in different files
  docs/specs/moniker.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4824 🎈Add validation that same uid should have same name
  docs/specs/moniker.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/ExternalXRefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4830 consist conceptual and landing data build
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ConceptualModel.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#4834 Add more logging to restore
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4826 find neareast toc by file path
  docs/specs/legacy.yml
  src/docfx/build/toc/TableOfContentsMap.cs
  test/docfx.Test/data/template/ContentTemplate/toc.json.js
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4828 JsonSchema: pattern
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4838 change toc missing name level from error to warning
  docs/specs/toc.yml
  src/docfx/Errors.cs
Labels: v3

#4823 Apply data schema
  docs/specs/schema.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateSchema.cs
Labels: v3

#4842 ignore update_at_date_time
  docs/specs/legacy.yml
  src/docfx/build/page/ContributionInfo.cs
Labels: v3

#4844 support return object with no content
  docs/specs/schema.yml
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4837 Fix loc integration test
  src/docfx/docset/Repository.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4836 Fix payload too large when creating github issue
  src/docfx/cli/Docfx.cs
Labels: v3

#4839 🎈Duplicated uids in one SDP file
  docs/specs/xref.yml
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  stylecop.ruleset
Labels: v3

#4687 Add Feature Requirements of XREF
  docs/designs/xref.md
Labels: ready-for-review, v3

#4848 Do not run jobs already in thread pool when WorkQueue encountered exception
  src/docfx/lib/collections/WorkQueue.cs
Labels: v3

#4849 avoid using same restore file in different spec tests
  docs/specs/config.yml
Labels: v3

#4845 Add .vsconfig
  .vsconfig
Labels: v3

#4846 JsonSchema: uniqueItems
  src/docfx/Errors.cs
  src/docfx/lib/json/JTokenDeepEqualsComparer.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4850 ✨sort properties during serialization
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4854 only HTML encode required chars
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4859 sort properties
  src/docfx/build/page/BuildPage.cs
Labels: v3

#4858 Do not validate bookmark if the target file doesn't report bookmarks
  docs/specs/localization.yml
  src/docfx/build/page/BookmarkValidator.cs
Labels: v3

#4860 fix resolve alias with more than one slashes
  docs/specs/resolve.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4840 share transformed model between transform xref and transform content
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/ReferenceEqualsComparer.cs
Labels: v3

#4861 Author can be excluded if it is not specified in YAML header
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#4863 fix adding post processor twice issue
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/HtmlPostProcessor.cs
Labels: v2

#4862 fix bug of page date after applying template
  docs/specs/legacy.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ContributionInfo.cs
Labels: v3

#4853 Update schema-not-found and empty-monikers message
  docs/specs/moniker.yml
  docs/specs/schema.yml
  src/docfx/Errors.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
Labels: v3

#4855 Refine SDP pipeline
  docs/specs/legacy.yml
  docs/specs/schema.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ConceptualModel.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/template/JavascriptEngine.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#4867 log template hash
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateManager.cs
Labels: v2

#4856 WorkQueue.Drain wait for pending jobs in case of exception
  src/docfx/lib/collections/WorkQueue.cs
Labels: v3

#4864 combine the xref spec builder and json schema xref loader
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4875 🚢🚢🚢
  .vsconfig
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/schema.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ConceptualModel.cs
  src/docfx/build/page/ContributionInfo.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/json/JTokenDeepEqualsComparer.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/lib/schema/ReferenceEqualsComparer.cs
  src/docfx/template/JavascriptEngine.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#4878 redirection files with conflicted document id should be built
  docs/specs/config.yml
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#4879 🐛remove unnecessary dependency
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4866 support has error flag in publish item file
  docs/specs/manifest.yml
  docs/specs/moniker.yml
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#4877 Metadata validation modify error message
  docs/specs/schema.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4887 🐛fix xref transform bug
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4886 data schema has merged metadata
  docs/specs/schema.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#4889 output stable order publish manifest
  docs/specs/legacy.yml
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#4882 JsonSchema: contains
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4888 Metadata validation: Additional errors
  src/docfx/lib/log/TelemetryName.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/lib/schema/OverwriteErrorSchema.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4871 Fix thread pool starve by adding parallel limit to workqueue
  docs/specs/validation.yml
  src/docfx/cli/Docfx.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/lib/RandomUtility.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/log/TelemetryName.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#4892 relocate the invalid file link
  docs/specs/config.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4881 JsonSchema: mutipleOf
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4851 change toc transform from replace to return new model
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4891 fix page title and metadata merge order
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/json/JsonUtility.cs
Labels: v3

#4900 🚢🚢🚢
  README.md
  azure-pipelines-v3.yml
  docs/roadmap.md
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/cli/Docfx.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/lib/RandomUtility.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/log/TelemetryName.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/lib/schema/OverwriteErrorSchema.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4896 add "from" to error and legacy error in the report
  docs/specs/legacy.yml
  docs/specs/localization.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/LegacyVersionProvider.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/template/TemplateSchema.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4901 🐛 Homepage only shows when topic href is set and href is not
  docs/specs/toc.yml
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4911 🚢🚢🚢
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/LegacyVersionProvider.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/template/TemplateSchema.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4904 JsonSchema: boolean schema
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaConverter.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4872 Check max line width and method complexity
  Menees.Analyzers.Settings.xml
  src/docfx/docfx.csproj
  stylecop.ruleset
Labels: v3

#4905 Update .editorconfig to include .NET style rules
  .editorconfig
Labels: v3

#4908 JsonSchema: items array form and additionalItems
  src/docfx/lib/json/UnionTypeConverter.cs
  src/docfx/lib/json/ValueOrObjectConverter.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4902 Add bookmark validation for SDP contents
  docs/specs/schema.yml
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/template/TemplateSchema.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4915 Fix stubble treats JObject as array
  src/docfx/docfx.csproj
  src/docfx/template/MustacheTemplate.cs
  test/docfx.Test/data/mustache/include.tmpl
  test/docfx.Test/data/mustache/section.tmpl
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#4907 Metadata validation: Enumdependenies rule supports self dependency
  src/docfx/lib/schema/EnumDependenciesSchema.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4916 Enable SourceLink
  src/docfx/docfx.csproj
Labels: v3

#4917 Metadata validation: Combine base message and additional message
  src/docfx/lib/schema/AdditionalErrorSchema.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4913 JsonSchema: dependencies as subschema
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4883 avoid duplicated call to get user by commits
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
Labels: v3

#4914 JsonSchema: date and time
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaStringFormat.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/data/jschema/LICENSE
  test/docfx.Test/data/jschema/draft7/optional/format/date.json
  test/docfx.Test/data/jschema/draft7/optional/format/time.json
  test/docfx.Test/data/jschema/draft7/ref.json
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4918 Add data-linktype to SDP content HTML
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/common/TestUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4921 🚢🚢🚢
  .editorconfig
  Menees.Analyzers.Settings.xml
  build.ps1
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/schema.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/docfx.csproj
  src/docfx/docset/Document.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/UnionTypeConverter.cs
  src/docfx/lib/json/ValueOrObjectConverter.cs
  src/docfx/lib/schema/AdditionalErrorSchema.cs
  src/docfx/lib/schema/EnumDependenciesSchema.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaConverter.cs
  src/docfx/lib/schema/JsonSchemaStringFormat.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateSchema.cs
  stylecop.ruleset
  test/docfx.Test/common/TestUtility.cs
  test/docfx.Test/data/jschema/LICENSE
  test/docfx.Test/data/jschema/draft7/optional/format/date.json
  test/docfx.Test/data/jschema/draft7/optional/format/time.json
  test/docfx.Test/data/jschema/draft7/ref.json
  test/docfx.Test/data/mustache/include.tmpl
  test/docfx.Test/data/mustache/section.tmpl
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#4909 Record ordered file in xref map
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/LinkPhaseHandler.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
Labels: v2

#4919 Fix stackoverflow exception caused by WorkQueue
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/collections/WorkQueue.cs
Labels: v3

#4924 Validate each metadata schema individually for multiple metadata schema definitions
  docs/specs/validation.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4920 Metadata Validation: Not validate TOC
  src/docfx/build/metadata/MetadataProvider.cs
Labels: v3

#4928 export master pipeline to yaml style
  azure-pipelines-master.yml
Labels: v2

#4931 Documented video markdown syntax
  Documentation/spec/docfx_flavored_markdown.md
Labels: v2, v3

#4934 Metadata validation: Not throw warning when null appear in enumdependencies
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4927 [v3]include the date to warning in message of InvalidInternalBookmark
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/schema.yml
  src/docfx/Errors.cs
Labels: v3

#4937 🎉🎉🎉Enable Codecov PR comment
  .gitignore
  azure-pipelines-v3.yml
  build.ps1
  test/docfx.Test/docfx.Test.csproj
Labels: v3

#4932 skip recursive lookup value for mustache template
  src/docfx/template/MustacheTemplate.cs
  test/docfx.Test/data/mustache/section.tmpl
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#4925 support titleOverwriteH1
  src/Microsoft.DocAsCode.Build.ConceptualDocuments/BuildConceptualDocument.cs
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/TocDocumentProcessorBase.cs
  src/Microsoft.DocAsCode.Common/XrefUtility.cs
  src/Microsoft.DocAsCode.DataContracts.Common/Constants.cs
  test/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests/ConceptualDocumentProcessorTest.cs
Labels: v2

#4926 [v2]include the date to warning in message of InvalidInternalBookmark
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/ValidateBookmark.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/ValidateBookmarkTest.cs
Labels: v2

#4941 pass along unknown queries while resolving uid
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/lib/UrlUtility.cs
Labels: v3

#4933 Allow error customization for all errors
  docs/specs/config.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/config/Config.cs
  src/docfx/lib/json/ShortHandConverter.cs
  src/docfx/lib/log/CustomError.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/schema/AdditionalErrorSchema.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3
