Repository dotnet/docfx, pull requests merged in 2019-02, with the labels that each got.

#3996 Log theme url and resolved theme version
  src/docfx/docset/Docset.cs
Labels: v3

#3998 add items to publish to legacy manifest file
  src/docfx/build/legacy/manifest/LegacyItemToPublish.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
Labels: v3

#4000 👏>90% code coverage
  build.ps1
Labels: v3

#3966 Change TOC pipeline to run jint post processor
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/toc.yml
  schemas/TOC.json
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/files/LegacyOutput.cs
  src/docfx/build/legacy/files/LegacyTableOfContents.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikersProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsInputItem.cs
  src/docfx/build/toc/parser/TableOfContentsInputModel.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateTransform.cs
  tools/CreateJsonSchema/Program.cs
Labels: v3

#3999 non-source files should not be included in file metadata changes when incremental build
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#4004 fix dependency map type
  src/docfx/build/legacy/manifest/LegacyManifest.cs
Labels: v3

#4008 Resolve Index.md to `./` over `.`
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/docset/Document.cs
  test/docfx.Test/build/DocumentTest.cs
Labels: v3

#4009 Toc href takes predecance over href
  docs/specs/toc.yml
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4006 make the max-exceeded-error message more clear
  src/docfx/Errors.cs
  src/docfx/lib/log/Report.cs
Labels: v3

#4015 fix location of xrefmap.json
  src/docfx/build/legacy/manifest/LegacyManifest.cs
Labels: v3

#4011 Support log level Suggestion in log listeners
  src/Microsoft.DocAsCode.Common/Loggers/ConsoleLogListener.cs
  src/Microsoft.DocAsCode.Common/Loggers/HtmlLogListener.cs
Labels: v2

#4019 Add dependencies to legacy aggregated file map
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyDependencyMapItem.cs
  src/docfx/build/legacy/LegacyDependencyMapType.cs
  src/docfx/build/legacy/LegacyFileMap.cs
Labels: v3

#4010 Add hash to publish manifest
  docs/specs/manifest.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/lib/PathUtility.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4025 split toc map and toc
  src/docfx/build/Build.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#4023 Html decode before extracting title
  docs/specs/markdown.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4001 📄 Add triage process
  docs/developer-guide.md
Labels: v3

#4040 Ignore perf trace files
  .gitignore
Labels: v3

#4045 fix missing DLLs under mono
  src/docfx/docfx.csproj
Labels: v2

#4038 no need restore if we already find any file/git path with version
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4048 Optimize ParseHeading by removing linq
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Aggregator/TabGroupAggregator.cs
Labels: v3

#4046 Url decode before resolving links
  docs/specs/escape.yml
  docs/specs/markdown.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/common/TestUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#3964 add noloc extension
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Noloc/NolocExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Noloc/NolocInline.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Noloc/NolocParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Noloc/NolocRender.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/NolocTest.cs
Labels: v2, v3

#4059 populate invisible metadata from op_schema.json in OPS plug-in
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4029 cache toc model, avoid to load twice for building toc and building toc map
  src/docfx/build/context/Cache.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4060 Resolve breadcrumb_path
  docs/specs/metadata.yml
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/build/page/BuildPage.cs
Labels: v3

#4055 Remove unnecessary dictionary copy
  src/docfx/build/Build.cs
  src/docfx/build/moniker/MonikerMap.cs
  src/docfx/build/moniker/MonikerMapBuilder.cs
Labels: v3

#4053 [ThreadStatic] --> ThreadLocal
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#4054 Ignore more perf trace files
  .gitignore
Labels: v3

#4056 use source repo's branch
  docs/specs/git.yml
  docs/specs/localization.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4031 update restore design spec for restore and gc improvement
  docs/designs/restore-and-gc.md
Labels: v3

#4061 🔒support cross process read write lock
  src/docfx/lib/ProcessUtility.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4062 📈Add basic application insight telemetry
  src/docfx/build/Build.cs
  src/docfx/cli/Program.cs
  src/docfx/docfx.csproj
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/log/Report.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/log/TelemetryName.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4065 🚀Optimize TOC markdown pipeline to only included what's needed
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveToc.cs
Labels: v3

#4063 🌏Flatten dependency map
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/schema.yml
  src/docfx/build/dependency/DependencyItem.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
Labels: v3

#4070 remove CODEOWNERS
  CODEOWNERS
Labels: v2

#4071 💬 TOC.md supports xml comment
  docs/specs/toc.yml
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#4074 remove HTML attribute
  src/Microsoft.Docs.Template/Models/LandingData.cs
Labels: v3

#4076 🔒remove sub dep lock support and change test
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/docset/Docset.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#4081 ✔Avoid null author legacy output
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4083 📄Blank content
  docs/specs/manifest.yml
  docs/specs/metadata.yml
  src/docfx/build/page/BuildPage.cs
Labels: v3

#4084 🌀make the nested detection more correct for RunInsideMutex
  src/docfx/lib/ProcessUtility.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4086 🎫Add back [Html], remove [Href].
  src/Microsoft.Docs.Template/Models/LandingData.cs
Labels: v3

#4089 🐞fix nested call detection and add test cases
  src/docfx/lib/ProcessUtility.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4088 keep `index` in asset_id
  src/docfx/build/legacy/LegacyUtility.cs
Labels: v3

#4087 Put ForceRebuild in prior to NoAvailableBuildCache detection
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
  src/Microsoft.DocAsCode.Common/Loggers/InfoCodes.cs
Labels: v2

#4091 add redirection file to filemap
  src/docfx/build/legacy/LegacyFileMapItem.cs
Labels: v3

#4092 ⬆Update NuGet packages
  src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj
  src/docfx/docfx.csproj
  src/docfx/lib/git/LibGit2.cs
  test/docfx.Test/docfx.Test.csproj
Labels: v3
