Repository dotnet/docfx, pull requests merged in 2019-04, with the labels that each got.

#4280 DocFX V3 PROD Release Deployment
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/Microsoft.Docs.Template/Views/Template/LandingData.cshtml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateTransform.cs
  test/docfx.Test/docfx.test.yml
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4270 🛠Keep the line info of config schema validation
  docs/specs/config.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4263 decode href in toc.yml/md to find file
  src/Microsoft.DocAsCode.Build.TableOfContents/BuildTocDocumentStepBase.cs
  test/Microsoft.DocAsCode.Build.TableOfContents.Tests/TocDocumentProcessorTest.cs
Labels: v2

#4271 👨‍🏭remove un-necessary await/async method and prepare for mutex changes
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/moniker/MonikersProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/ProcessUtility.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/lib/GitUtilityTest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4281 never transit metadata type dependency
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/DependencyGraph.cs
  src/Microsoft.DocAsCode.Plugins/DependencyTransitivity.cs
  src/Microsoft.DocAsCode.Plugins/DependencyType.cs
Labels: v2

#4279 Added the ability to change the default "Cover Page" title for the "Table of Contents" added as a bookmark to the PDF
  Documentation/tutorial/docfx.exe_user_manual.md
  RELEASENOTE.md
  src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs
  src/Microsoft.DocAsCode.HtmlToPdf/PdfOptions.cs
  src/docfx/Models/PdfJsonConfig.cs
  src/docfx/SubCommands/PdfCommand.cs
Labels: v2

#4283 Add test for metadata in index.yml
  docs/specs/metadata.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
Labels: v3

#4267 👨‍🏭combine template engine and transform to reduce confusion
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/Contributor.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4282 🧹remove get file commit history without cache
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
Labels: v3

#4287 Fix file naming convention and enable SA1649
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/config/OverwriteConfigIdentifier.cs
  src/docfx/docfx.csproj
  stylecop.json
  stylecop.ruleset
Labels: v3

#4286 ⚒add apply template and get commits time to telemtry
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/log/TelemetryName.cs
Labels: v3

#4291 log file which causes build collapse
  src/docfx/build/Build.cs
Labels: v3

#4288 🐛fix bug of key already added
  docs/specs/localization.yml
  src/docfx/lib/git/FileCommitProvider.cs
Labels: v3

#4266 Trim json string values in config
  docs/specs/config.yml
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/JsonUtility.cs
Labels: v3

#4265 🛠Consolidate JsonUtility and YamlUtility to share the same interface
  docs/specs/metadata.yml
  docs/specs/toc.yml
  src/docfx/build/context/Cache.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/YamlUtility.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4292 Add namespace to CommitsTimeItem
  src/docfx/build/metadata/CommitsTimeItem.cs
Labels: v3

#4295 📉add build item count and commit count to telemetry
  src/docfx/build/Build.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/log/TelemetryName.cs
Labels: v3

#4296 Drop json schema due to license issue
  build.ps1
  build.sh
  schemas/Conceptual.json
  schemas/ContextObject.json
  schemas/LandingData.json
  schemas/TOC.json
  schemas/TestData.json
  schemas/TestPage.json
  schemas/docfx.json
  tools/CreateJsonSchema/CreateJsonSchema.csproj
  tools/CreateJsonSchema/Program.cs
Labels: v3

#4299 Fix yaml header line info off by one error
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/toc.yml
  src/docfx/lib/markdown/ExtractYamlHeader.cs
Labels: v3

#4298 Add line info to github-user-not-found using SourceInfo<T>
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/Range.cs
  src/docfx/lib/log/SourceInfo.cs
  stylecop.ruleset
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4293 Make ProcessUtility.Execute sync
  src/docfx/lib/ProcessUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencySlotPool.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4303 Split contract resolvers from json utility
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
Labels: v3

#4290 Decouple get link logic from v2
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveLinkExtension.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
Labels: v3

#4301 remove dependency between toc and resource
  src/Microsoft.DocAsCode.Build.Engine/ManifestProcessor.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/BuildTocDocument.cs
Labels: v2

#4307 🐛fix bug of parsing vsts remote with collection
  src/docfx/lib/azure/AzureRepoUtility.cs
  test/docfx.Test/lib/AzureRepoUtility.cs
Labels: bug, v3

#4308 🧹remove tool folder from sln
  docfx.sln
Labels: v3

#4309 Skip tabbed content title when resolve links
  docs/specs/markdown.yml
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/ResolveLinkExtension.cs
Labels: v3

#4302 Remove json path from error in favor of line info
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/Report.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4310 warning => error for duplicate outputs
  src/Microsoft.DocAsCode.Build.Engine/ManifestUtility.cs
  src/Microsoft.DocAsCode.Common/Loggers/Codes/ErrorCodes.cs
  src/Microsoft.DocAsCode.Common/Loggers/Codes/InfoCodes.cs
  src/Microsoft.DocAsCode.Common/Loggers/Codes/WarningCodes.cs
Labels: v2

#4068 🔒Use globally named mutex over file locking
  src/docfx/lib/ProcessUtility.cs
Labels: v3

#4297 perf: save query dict in dependency cmd
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/DependencyGraph.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/ExpandedDependencyMap.cs
Labels: v2

#4300 perf: deserialize only needed in dependency cmd
  src/docfx/SubCommands/DependencyCommand.cs
Labels: v2

#4312 Suppress SA1629
  stylecop.ruleset
Labels: v3

#4313 Treat // as external URL
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4289 Prevent adding duplicate HTML files when generating a PDF
  Documentation/tutorial/docfx.exe_user_manual.md
  RELEASENOTE.md
  src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
  src/Microsoft.DocAsCode.HtmlToPdf/Microsoft.DocAsCode.HtmlToPdf.csproj
  src/Microsoft.DocAsCode.HtmlToPdf/PdfOptions.cs
  src/Microsoft.DocAsCode.HtmlToPdf/packages.config
  src/docfx/Models/PdfJsonConfig.cs
  src/docfx/SubCommands/PdfCommand.cs
Labels: v2

#4314 feat: resolve xref recursively
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/inputs/CatLibrary.ICat.yml
Labels: v2

#4324 trace file path for xref loading failure
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#4294 🔗Add line info for Toc href validation
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4327 support toc with extension data
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsModel.cs
Labels: v3

#4319 🧹 Deleted unused packages.config and removed support for OutlineOption.CustomOutline
  Documentation/guideline/engineering_guidelines.md
  RELEASENOTE.md
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
  src/Microsoft.DocAsCode.HtmlToPdf/OutlineOption.cs
  src/Microsoft.DocAsCode.HtmlToPdf/packages.config
Labels: v2

#4329 add log code MarkdownEngineName
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Common/Loggers/Codes/InfoCodes.cs
Labels: v2

#4330 support landing data with extension data, but don't serialize
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/docfx/build/toc/TableOfContentsModel.cs
Labels: v3

#4272 🔗Add line info for file-not-found
  docs/specs/config.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4332 🐛add more metadata name to black list
  docs/specs/legacy.yml
  src/docfx/build/metadata/MetadataValidator.cs
Labels: v3

#4338 👨‍🏭support link to deleted resource to get ride of tons of noisy warnings
  docs/specs/localization.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4344 🎫Clean up legacy tests
  docs/specs/legacy.yml
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/e2e/E2ESpec.cs
Labels: v3

#4345 fix for null reference
  docs/specs/metadata.yml
  src/docfx/lib/json/SourceInfoJsonConverter.cs
Labels: v3

#4343 🍂merge root level unknown fields to metadata for landing data
  docs/specs/legacy.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
Labels: future, v3

#4336 📝Xref line info
  docs/specs/localization.yml
  docs/specs/moniker.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4348 don't warn if xref template rendered empty
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
Labels: v2

#4311 Range --> SourceInfo
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/Range.cs
  src/docfx/lib/log/Report.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
Labels: v3

#4349 📝Line info
  docs/specs/toc.yml
  src/docfx/build/Build.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#4351 🍂support multiple hashtags for fragment
  docs/specs/markdown.yml
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4333 extract title from markdown if null/empty in YAML header
  src/Microsoft.DocAsCode.Build.ConceptualDocuments/BuildConceptualDocument.cs
  test/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests/ConceptualDocumentProcessorTest.cs
Labels: v2

#4342 Added support for a cover page when generating a PDF (#2004)
  Documentation/tutorial/docfx.exe_user_manual.md
  Documentation/tutorial/walkthrough/walkthrough_generate_pdf.md
  RELEASENOTE.md
  src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
  src/Microsoft.DocAsCode.HtmlToPdf/Microsoft.DocAsCode.HtmlToPdf.csproj
  src/Microsoft.DocAsCode.HtmlToPdf/PartialPdfModel.cs
  src/Microsoft.DocAsCode.HtmlToPdf/PdfOptions.cs
  src/docfx.website.themes/pdf.default/cover.html.primary.tmpl
  src/docfx/Models/PdfJsonConfig.cs
  src/docfx/SubCommands/PdfCommand.cs
Labels: v2

#4353 🐛fix context_object_type, change from "content" to "toc"
  docs/specs/legacy.yml
  src/docfx/build/legacy/manifest/LegacyManifest.cs
Labels: v3

#4355 Docfx v3 Prod Release Deployment
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/restore.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/Range.cs
  src/docfx/lib/log/Report.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/e2e/E2ESpec.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4356 Add file to JSON source info
  src/docfx/build/context/Cache.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4360 🌐always restore source master for loc non-live branch building
  docs/specs/localization.yml
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/build/ConfigTest.cs
Labels: v3

#4364 Revert "🍂support multiple hashtags for fragment (#4351)"
  docs/specs/markdown.yml
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4366 add test case for bookmark starting with #
  docs/specs/markdown.yml
Labels: v3

#4359 Add line info to merge conflict
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/lib/git/GitUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4362 Refine raw model for template part-1
  docs/specs/legacy.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/PageModel.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Document.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4369 🐛more fileds need to be removed from raw model
  docs/specs/legacy.yml
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4368 Fix NRE in IsDocfxException
  src/docfx/lib/log/DocfxException.cs
Labels: v3

#4365 Add support for <xref href="uid"/> in HTML inside markdown files
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4374 🐛fix document id
  docs/specs/legacy.yml
  src/docfx/docset/Document.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4373 Revert "warning => error for duplicate outputs (#4310)"
  src/Microsoft.DocAsCode.Build.Engine/ManifestUtility.cs
  src/Microsoft.DocAsCode.Common/Loggers/ErrorCodes.cs
  src/Microsoft.DocAsCode.Common/Loggers/InfoCodes.cs
  src/Microsoft.DocAsCode.Common/Loggers/WarningCodes.cs
Labels: v2

#4377 🐛 metadata merge order matters
  docs/specs/legacy.yml
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4372 small fix, no need generic for getting file metadata method
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#4370 warn user of drop project.json
  src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs
Labels: v2

#4363 should not check conflict id if the redirection file is out of scope
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/docset/Docset.cs
Labels: v3

#4371 👨‍🏭flatten page metadata in output model, template raw model part-2
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputModel.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4380 Add test for handling html encoding of xref resolving
  docs/specs/escape.yml
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4358 Add line info to invalid-redirect-to and invalid-redirection
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/config/Config.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4382 🛠Not Serialize empty Sourceinfo<>
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4387 Publish docfx to drop/docfx folder
  build.ps1
Labels: v3

#4388 release note 2.42
  RELEASENOTE.md
Labels: v2

#4393 Docfx V3 PROD Release Deployment
  build.ps1
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputModel.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4389 Fix for empty YAML header
  docs/specs/markdown.yml
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4386 🌐make sure the source repo are get only once during restore and build
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/build/ConfigTest.cs
Labels: v3

#4383 🌐 restore corresponding source branch firstly
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4397 Add line info for more error codes
  docs/specs/metadata.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4395 👨‍🏭 combine restore map and dependency lock in build pipeline
  src/docfx/build/Build.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#4402 fix NRE in dependency cmd
  src/docfx/SubCommands/DependencyCommand.cs
Labels: v2

#4399 ⚒remove duplicated file in errors and fix bug of toc md line info
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
  src/docfx/restore/RestoreMap.cs
Labels: v3

#4398 use null to overwrite when merge jObjects
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4404 config restore log path in output options
  src/docfx/cli/Program.cs
Labels: v3

#4403 parse xref config to jArray
  docs/specs/xref.yml
  src/docfx/config/ConfigLoader.cs
Labels: v3

#4396 codify azure-pipelines.yml, publish artifacts, deprecate stable branch
  .github/CONTRIBUTING.md
  README.md
  azure-pipelines.yml
  tools/Deployment/gulpfile.js
Labels: v2

#4405 🐛 restore with legacy option
  src/docfx/cli/Program.cs
Labels: v3

#4384 Validate metadata value must be scalar or scalar array
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/config/ConfigLoader.cs
Labels: v3

#4410 make git commit content url consistent with v2
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#4401 Support use commit build time for updated at
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/localization.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/lib/git/CommitBuildTime.cs
  src/docfx/lib/git/CommitBuildTimeItem.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/log/Report.cs
  src/docfx/restore/RestoreFile.cs
  test/docfx.Test/e2e/E2ESpec.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4414 📃 Unify metadata validation source info
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/json/JTokenJsonConverter.cs
  src/docfx/lib/json/JsonUtility.cs
Labels: v3

#4423 🍂 make the git content/commit url format consistent with legacy model
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#4408 📝Add line info for yaml-header-not-object and schema-not-found
  docs/specs/markdown.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/docset/Document.cs
  src/docfx/docset/Schema.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4426 💬Usage -> Getting Started
  README.md
Labels: v3

#4424 export non string to xref
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/XrefPropertiesInterpreter.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/TocDocumentProcessorBase.cs
  src/Microsoft.DocAsCode.Common/Loggers/WarningCodes.cs
  src/Microsoft.DocAsCode.Common/XrefUtility.cs
  src/Microsoft.DocAsCode.Plugins/XRefSpec.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/TemplateProcessorUnitTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/inputs/CatLibrary.ICat.yml
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/schemas/mref.test.schema.json
Labels: v2

#4381 👨‍🏭 move more logic out of `create raw model`
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/restore.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ContributionInfo.cs
  src/docfx/build/page/OutputModel.cs
  src/docfx/config/Config.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4432 Fix for index.png asset_id
  src/docfx/build/legacy/LegacyUtility.cs
Labels: v3

#4433 🐛 fix implicit restore bug
  src/docfx/restore/RestoreMap.cs
Labels: v3

#4435 👨‍🏭 reuse existing work-tree
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4436 fix legacy diff for _op_gitContributorInformation.update_at
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#4430 Get schema from documentType while YamlMime is YamlDocument
  docs/specs/legacy.yml
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/json/YamlUtility.cs
Labels: v3

#4438 remove checking for toc items
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsModel.cs
Labels: v3

#4425 Add custom metadata validation based on JSON schema
  docs/specs/metadata.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/config/Config.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaType.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  src/docfx/restore/RestoreFile.cs
  stylecop.ruleset
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4447 🐛always restore based on slot states
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4445 🛠Improve xrefmap.json de-serialization
  docs/specs/xref.yml
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/HttpClientUtility.cs
Labels: v3

#4448 🧪Test against JSON schema test suite
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/data/jschema/draft7/additionalItems.json
  test/docfx.Test/data/jschema/draft7/additionalProperties.json
  test/docfx.Test/data/jschema/draft7/allOf.json
  test/docfx.Test/data/jschema/draft7/anyOf.json
  test/docfx.Test/data/jschema/draft7/boolean_schema.json
  test/docfx.Test/data/jschema/draft7/const.json
  test/docfx.Test/data/jschema/draft7/contains.json
  test/docfx.Test/data/jschema/draft7/default.json
  test/docfx.Test/data/jschema/draft7/definitions.json
  test/docfx.Test/data/jschema/draft7/dependencies.json
  test/docfx.Test/data/jschema/draft7/enum.json
  test/docfx.Test/data/jschema/draft7/exclusiveMaximum.json
  test/docfx.Test/data/jschema/draft7/exclusiveMinimum.json
  test/docfx.Test/data/jschema/draft7/if-then-else.json
  test/docfx.Test/data/jschema/draft7/items.json
  test/docfx.Test/data/jschema/draft7/maxItems.json
  test/docfx.Test/data/jschema/draft7/maxLength.json
  test/docfx.Test/data/jschema/draft7/maxProperties.json
  test/docfx.Test/data/jschema/draft7/maximum.json
  test/docfx.Test/data/jschema/draft7/minItems.json
  test/docfx.Test/data/jschema/draft7/minLength.json
  test/docfx.Test/data/jschema/draft7/minProperties.json
  test/docfx.Test/data/jschema/draft7/minimum.json
  test/docfx.Test/data/jschema/draft7/multipleOf.json
  test/docfx.Test/data/jschema/draft7/not.json
  test/docfx.Test/data/jschema/draft7/oneOf.json
  test/docfx.Test/data/jschema/draft7/pattern.json
  test/docfx.Test/data/jschema/draft7/patternProperties.json
  test/docfx.Test/data/jschema/draft7/properties.json
  test/docfx.Test/data/jschema/draft7/propertyNames.json
  test/docfx.Test/data/jschema/draft7/ref.json
  test/docfx.Test/data/jschema/draft7/refRemote.json
  test/docfx.Test/data/jschema/draft7/required.json
  test/docfx.Test/data/jschema/draft7/type.json
  test/docfx.Test/data/jschema/draft7/uniqueItems.json
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4441 🧹Remove legacy switch used in dependency resolver
  docs/specs/resolve.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4452 🐞 Fixes weak etag parsing error
  src/docfx/restore/RestoreFile.cs
Labels: v3

#4451 Fix for document id of landing page
  docs/specs/metadata.yml
  src/docfx/docset/Document.cs
Labels: v3

#4454 🐞Fix one more weak etag
  src/docfx/lib/github/GitHubUserCache.cs
Labels: v3

#4456 🦄Json schema validation support union type
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  src/docfx/lib/schema/OneOrManyConverter.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3
