Repository dotnet/docfx, pull requests merged in 2019-01, with the labels that each got.

#3830 add theme to crrInfo
  src/docfx/build/legacy/LegacyCrossRepoReferenceInfo.cs
Labels: v3

#3851 fix branch name`
  build.ps1
Labels: v3

#3845 Split config data model and config loader
  docs/specs/metadata.yml
  src/docfx/config/Config.cs
  src/docfx/config/ConfigConstants.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationConvention.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
Labels: v3

#3844 Fetch with --prune to sync deleted branches
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#3857 build from loc folder is not supported
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/e2e/E2ESpec.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#3853 Resource metadata only needs locale and monikers
  src/docfx/build/legacy/files/LegacyResource.cs
Labels: v3

#3861 disable e2e test temporarily
  tools/Deployment/gulpfile.js
Labels: v2

#3840 fix cache corruption when shrink multiple times
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/BuildInfo.cs
  src/Microsoft.DocAsCode.Build.Engine/LinkPhaseHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/PostProcessorsHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Common/FileAbstractLayer/ManifestFileHelper.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Tests.Common/TestBase.cs
Labels: v2

#3859 log: add more detailed info to full build
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#3864 support build loc repo with docfx config
  docs/specs/localization.yml
  src/docfx/config/ConfigLoader.cs
  src/docfx/localization/LocalizationUtility.cs
Labels: v3

#3843 create file metadata cache
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadata.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataHelper.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/BuildVersionInfo.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#3771 Cyclic xref reference
  docs/specs/moniker.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XRefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/CollectionUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
Labels: v3

#3868 Test dotnet tool install
  build.ps1
  build.sh
Labels: v3

#3866 Update spec test guide
  docs/engineering/developer-guide.md
Labels: v3

#3876 Xref recursive reference check should consider `displayPropertyName`
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#3878 add test cases
  docs/specs/markdown.yml
Labels: v3

#3877 add JsonConverter for FileMetadata
  src/Microsoft.DocAsCode.Build.Engine/FileMetadata.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataConverter.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/BuildVersionInfo.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/JsonConverterTest.cs
Labels: v2

#3881 fix bug of get restored repo with branch staring with xxx-
  docs/specs/restore.yml
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#3890 fix an incremental test by providing template
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
Labels: v2

#3889 refactor xref map
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/log/Report.cs
Labels: v3

#3897 always need refresh the last write time for restored items
  src/docfx/build/legacy/LegacyCrossRepoReferenceInfo.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#3899 Make LandingData model complete to get rid of `unknown-field` warning
  schemas/LandingData.json
  src/Microsoft.Docs.Template/Models/LandingData.cs
Labels: v3

#3892 Generate original_content_git_url_template
  docs/specs/git.yml
  src/Microsoft.Docs.Template/Models/PageModel.cs
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
Labels: v3

#3902 Exclude original_content_git_url_template from html meta tags
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
Labels: v3

#3886 caculate the file metadata changes
  src/Microsoft.DocAsCode.Build.Engine/FileMetadata.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataHelper.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataItem.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
  src/Microsoft.DocAsCode.Common/CollectionUtility.cs
  src/Microsoft.DocAsCode.Glob/FileGlob.cs
  src/Microsoft.DocAsCode.Glob/GlobMatcher.cs
  src/Microsoft.DocAsCode.Glob/Microsoft.DocAsCode.Glob.csproj
  test/Microsoft.DocAsCode.Build.Engine.Tests/FileMetadataHelperTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Common.Tests/CollectionUtilityTest.cs
Labels: v2

#3904 log raw filemetadata before hash into cache
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#3901 Add source info and callstack to js crashes
  src/docfx/build/legacy/template/JavascriptEngine.cs
  src/docfx/build/legacy/template/LegacyTemplate.cs
  test/docfx.Test/data/javascript/foo.js
  test/docfx.Test/data/javascript/index.js
  test/docfx.Test/template/JavascriptEngineTest.cs
Labels: v3

#3875 Fix InclusionContext stack
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/HtmlInclusionBlockRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/HtmlInclusionInlineRenderer.cs
  src/Shared/base.netstandard.props
Labels: v2, v3

#3908 Remove prune
  docs/specs/git.yml
  src/docfx/Errors.cs
  src/docfx/lib/git/GitUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#3911 upgrade markdig to use the latest feature
  src/Microsoft.DocAsCode.Build.OverwriteDocuments/Microsoft.DocAsCode.Build.OverwriteDocuments.csproj
  src/Microsoft.DocAsCode.Build.SchemaDriven/Microsoft.DocAsCode.Build.SchemaDriven.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/Microsoft.DocAsCode.MarkdigEngine.Validators.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
  test/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests.csproj
  tools/YamlSplitter/YamlSplitter.csproj
Labels: v3

#3894 add resolve alias config to support ~
  docs/specs/resolve.yml
  schemas/docfx.json
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/config/Config.cs
  src/docfx/docset/Docset.cs
Labels: v3

#3913 change max leading count for toc
  docs/specs/toc.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveToc.cs
Labels: v3

#3915 Delete errors.md
  docs/errors.md
Labels: v3

#3909 Add console diagnostic logs with --verbose
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Program.cs
  src/docfx/lib/log/Log.cs
  src/docfx/lib/log/Progress.cs
Labels: v3

#3862 add back e2e tests
  tools/Deployment/gulpfile.js
Labels: v2

#3900 restore + dependency lock + gc design spec
  docs/designs/restore-and-gc.md
Labels: v3

#3910 error->out and print out the build log when error happens
  build.ps1
  build.sh
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#3914 Update publish output model
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/moniker.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/manifest/Manifest.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/e2e/E2ESpec.cs
Labels: v3

#3925 Add roadmap
  docs/roadmap.md
Labels: v3

#3905 Rewrite js require implementation
  src/docfx/build/legacy/template/JavascriptEngine.cs
  src/docfx/build/legacy/template/LegacyTemplate.cs
  test/docfx.Test/data/javascript/a/a.js
  test/docfx.Test/data/javascript/b/b.js
  test/docfx.Test/data/javascript/index.js
  test/docfx.Test/template/JavascriptEngineTest.cs
Labels: v3

#3920 remove baseDir from fileMetadataCache
  src/Microsoft.DocAsCode.Build.Engine/FileMetadata.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataConverter.cs
  src/Microsoft.DocAsCode.Build.Engine/FileMetadataHelper.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/BuildVersionInfo.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalUtility.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/FileMetadataHelperTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/JsonConverterTest.cs
Labels: v2

#3922 add comments to errors
  src/docfx/Errors.cs
Labels: v3

#3919 Move models needed by build into docfx
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/build/page/Contributor.cs
  src/docfx/build/page/PageModel.cs
  src/docfx/build/redirection/RedirectionModel.cs
  src/docfx/build/resource/ResourceModel.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/docset/Schema.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  stylecop.ruleset
  tools/CreateJsonSchema/Program.cs
Labels: v3

#3846 Update data modeling developer guide
  .github/CONTRIBUTING.md
  README.md
  docs/developer-guide.md
Labels: v3

#3929 update document for use docfx in CI
  Documentation/tutorial/docfx_getting_started.md
Labels: v2

#3928 Add metadata to .publish.json
  docs/designs/publish.md
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  src/docfx/build/Build.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionModel.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/resource/ResourceModel.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Document.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#3935 remove version from legacy, handle it in impact tool
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
Labels: v3

#3926 limit the repository creation, prepare for restore lock
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/docset/Repository.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/lib/GitUtilityTest.cs
Labels: v3

#3941 Always generate content-git-url
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#3947 LegacyTemplate ->TemplateEngine
  src/docfx/build/Build.cs
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/docset/Docset.cs
  src/docfx/template/JavascriptEngine.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/liquid/JavascriptTag.cs
  src/docfx/template/liquid/LiquidFilter.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  src/docfx/template/liquid/LocalizeTag.cs
  src/docfx/template/liquid/StyleTag.cs
Labels: v3

#3951 Fix legacy page html transform not run
  src/docfx/build/legacy/files/LegacyPage.cs
Labels: v3

#3944 use dependency lock in restore and build
  docs/specs/restore.yml
  schemas/docfx.json
  src/docfx/build/Build.cs
  src/docfx/config/Config.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/restore/lock/DependencyVersion.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#3952 fix NRE
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#3953 fix bug of redirection is empty
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#3939 log: add more tracing info when calculating change list with file metadata or dependency change
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#3937 feat: log per-processor file count in incremental build
  src/Microsoft.DocAsCode.Build.Engine/CompilePhaseHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Build.Engine/HostServiceCreatorWithIncremental.cs
  src/Microsoft.DocAsCode.Plugins/IncrementalInfo.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
Labels: v2

#3959 Refine a config test case
  docs/specs/config.yml
Labels: v3

#3956 Add a basic legacy test
  docs/specs/legacy.yml
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#3957 use process lock when loading dependency lock file
  src/docfx/build/Build.cs
  src/docfx/docset/Docset.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#3946 Remove legacy resource and redirection conversion
  src/docfx/build/legacy/files/LegacyOutput.cs
  src/docfx/build/legacy/files/LegacyPage.cs
  src/docfx/build/legacy/files/LegacyResource.cs
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/docset/Document.cs
Labels: v3

#3961 remove host name if sharing the same one during uid resolving
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#3932 npm update to fix sec issues
  src/docfx.website.themes/default/gulpfile.js
  src/docfx.website.themes/default/package.json
  src/docfx.website.themes/gulpfile.js
  src/docfx.website.themes/package.json
Labels: v2

#3955 Check redirect url
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/manifest.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#3962 Add full build reason code
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
  src/Microsoft.DocAsCode.Common/Loggers/InfoCodes.cs
  src/Microsoft.DocAsCode.Plugins/IncrementalInfo.cs
Labels: v2

#3963 Ignore empty list during JSON serialization
  docs/specs/git.yml
  docs/specs/manifest.yml
  docs/specs/moniker.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/build/legacy/metadata/LegacyMetadata.cs
  src/docfx/lib/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#3954 Remove legacy page conversion
  docs/specs/legacy.yml
  docs/specs/resolve.yml
  src/docfx/build/legacy/files/LegacyOutput.cs
  src/docfx/build/legacy/files/LegacyPage.cs
  src/docfx/build/legacy/metadata/LegacySchema.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateModel.cs
  src/docfx/template/TemplateTransform.cs
Labels: v3

#3971 fix null value for template
  src/docfx/template/TemplateTransform.cs
Labels: v3

#3973 Force verbose in testing
  src/docfx/lib/log/Log.cs
  test/docfx.Test/common/TestFramework.cs
Labels: v3

#3972 Apply html post process for sdp
  src/docfx/build/page/BuildPage.cs
Labels: v3

#3967 restore always generate and save dependency lock for build
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/config/AppData.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/restore/lock/DependencyLockModel.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#3974 Run impact in --ci mode
  impact.ps1
Labels: v3

#3976 Don't apply template transform for yaml data files
  src/docfx/build/page/BuildPage.cs
Labels: v3

#3975 Delete CODEOWNERS
  .github/CODEOWNERS
Labels: v3

#3934 Support multiple uid
  docs/specs/xref.yml
  schemas/TestData.json
  src/Microsoft.Docs.Template/Models/TestData.cs
  src/docfx/Errors.cs
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#3977 just return if configuration loading has errors
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreMap.cs
Labels: v3

#3980 add locale to dependency lock path
  src/docfx/build/Build.cs
  src/docfx/config/AppData.cs
  src/docfx/lib/log/Report.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreMap.cs
Labels: v3

#3970 Consolidate json serializers
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#3985 fix build error....
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/template/TemplateTransform.cs
Labels: v3

#3988 omit empty enumerable value during serializing
  docs/specs/restore.yml
  src/docfx/lib/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#3991 add host to legacy filemap
  src/docfx/build/legacy/LegacyFileMap.cs
Labels: v3

#3990 disable downloads lock as its not supported
  src/docfx/config/ConfigLoader.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/restore/lock/DependencyLockModel.cs
Labels: v3

#3993 fix commentId's null ref for assembly type item
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MergeComments/MergeCommentsHelper.cs
  test/docfx.Tests/Assets/test.dll.sample.1
  test/docfx.Tests/MetadataCommandTest.cs
Labels: v2

#3992 add suggestion to log level
  src/Microsoft.DocAsCode.Build.Engine/HostService.cs
  src/Microsoft.DocAsCode.Common/Loggers/LogLevel.cs
  src/Microsoft.DocAsCode.Common/Loggers/Logger.cs
  src/Microsoft.DocAsCode.Common/Loggers/ReportLogListener.cs
  src/Microsoft.DocAsCode.Plugins/IHostService.cs
Labels: v2

#3997 remove op_crr_info.json legacy output
  docs/specs/legacy.yml
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyCrossRepoReferenceInfo.cs
Labels: v3
