Repository dotnet/docfx, pull requests merged in 2019-05, with the labels that each got.

#4473 🐞fix for xrefmap.json within 1 line
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#4475 🐞fix for parsing uid spec string
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMap.cs
Labels: v3

#4462 report to default output if config is not found
  docs/specs/localization.yml
  src/docfx/build/Build.cs
  src/docfx/cli/Program.cs
  src/docfx/lib/log/Report.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/lib/ReportTest.cs
Labels: v3

#4474 update output path
  docs/specs/moniker.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Document.cs
Labels: v3

#4477 shouldn't append a sharp symbol when there is no bookmark
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4460 update conceptual versioning design spec:
  docs/designs/conceptual-versioning.md
  docs/designs/output.md
Labels: v3

#4479 remove siteBasePath from documentIdConfig and append it to BaseUrl
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/DocumentIdConfig.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4478 🐞Log error while ReadSchema from a file with invalid json
  docs/specs/schema.yml
  src/docfx/lib/json/JsonUtility.cs
Labels: v3

#4459 🚀Replace Concurrent with manual lock for add only operation
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/moniker/MonikerMap.cs
  src/docfx/build/moniker/MonikerMapBuilder.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/toc/TableOfContentsMapBuilder.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/collections/CollectionUtility.cs
  src/docfx/lib/collections/ConcurrentHashSet.cs
  src/docfx/lib/collections/DictionaryBuilder.cs
  src/docfx/lib/collections/ListBuilder.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4480 docfx changes need for `Docs.Build` regression test
  build.ps1
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/legacy/manifest/LegacyManifestItem.cs
Labels: v3

#4429 🛰Load html metadata name, reserved metadata from schema
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4457 avoid test crashed when options are wrong
  src/docfx/cli/Program.cs
Labels: v3

#4465 Allow multiple metadata schema definitions
  docs/specs/validation.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/restore/RestoreFile.cs
Labels: v3

#4476 Make yaml-duplicated-key a non fatal error
  docs/specs/markdown.yml
  src/docfx/lib/json/YamlUtility.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4453 remove implicit restore incorrect optimization
  docs/specs/casing.yml
  docs/specs/resolve.yml
  src/docfx/cli/Program.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
Labels: v3

#4464 fix message for duplicateOutputFiles
  src/Microsoft.DocAsCode.Build.Engine/ManifestUtility.cs
Labels: v2

#4482 fix NRE when ContainingNamespace is null
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/NameVisitor.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VisitorHelper.cs
Labels: v2

#4483 Generate dependency list
  docs/specs/legacy.yml
  src/docfx/build/legacy/LegacyDependencyMap.cs
  test/docfx.Test/e2e/E2ESpec.cs
Labels: v3

#4487 Schema error level
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/config/ConfigLoader.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4257 Sandcastle ref mapper
  All.sln
  build.ps1
  src/nuspec/SandcastleRefMapper/SandcastleRefMapper.nuspec
  tools/SandcastleRefMapper/Program.cs
  tools/SandcastleRefMapper/SandcastleRefMapper.csproj
Labels: v2

#4494 Ensure dependencylist is stable
  src/docfx/build/legacy/LegacyDependencyMap.cs
Labels: v3

#4492 Use OneOrManyJsonConverter to expand config
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/json/OneOrManyConverter.cs
Labels: v3

#4495 add more perf scope
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.Engine/SingleDocumentBuilder.cs
  src/docfx/SubCommands/DocumentBuilderWrapper.cs
Labels: v2

#4491 Remove sas token for blob url while create short folder name
  src/docfx/lib/PathUtility.cs
  test/docfx.Test/lib/PathUtilityTest.cs
Labels: v3

#4500 rename moniker Model properties
  docs/specs/moniker.yml
  docs/specs/toc.yml
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/Moniker.cs
  src/docfx/lib/moniker/MonikerComparer.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4490 📃Json/yaml deserialize must have file info
  docs/specs/moniker.yml
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/ProcessUtility.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4501 🎡 change error level to warning for yaml header syntax error and duplicated key
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
Labels: v3

#4497 🧹remove implicit restore feature
  README.md
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/restore.yml
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Program.cs
  test/docfx.Test/e2e/E2ESpec.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4504 Update 'config-not-found', 'download-failed'
  docs/specs/localization.yml
  docs/specs/restore.yml
  src/docfx/Errors.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/restore/RestoreFile.cs
Labels: v3

#4503 Update log code 'absolute-file-path', 'committish-not-found'
  docs/specs/git.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4508 fix restore private repo test
  docs/specs/restore.yml
Labels: v3

#4509 continue to fix deploy ci
  docs/specs/restore.yml
Labels: v3

#4507 Update `github-user-not-found`, `invalid-locale`
  docs/specs/config.yml
  docs/specs/git.yml
  src/docfx/Errors.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4499 🧹 Href --> Url
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/HttpClientUtility.cs
  src/docfx/lib/LinkType.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/azure/AzureRepoUtility.cs
  src/docfx/lib/github/GithubUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/AzureRepoUtility.cs
  test/docfx.Test/lib/GitHubUtilityTest.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4496 Create error logs using with append
  src/docfx/lib/log/Report.cs
Labels: v3

#4498 🧹report --> errorlog
  docs/designs/output.md
  docs/designs/xref.md
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/cli/Program.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ReportTest.cs
Labels: v3

#4512 Update log code `invalid-glob-pattern`, `invalid-moniker-range`
  src/docfx/Errors.cs
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/GlobUtilityTest.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4513 🆕 support new azure devops url
  docs/specs/config.yml
  docs/specs/git.yml
  src/docfx/lib/UrlUtility.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#4517 📝Increase column for line info of link within HTML block
  docs/specs/markdown.yml
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveLinkExtension.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4522 Fix tests due to bad merge
  docs/specs/config.yml
  docs/specs/markdown.yml
Labels: v3

#4484 🚁 change output model to template consuming raw model
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputModel.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4524 fix raw page generated for template
  docs/specs/legacy.yml
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4515 Update log code `schema-not-found`, `uid-conflict`
  docs/specs/moniker.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
Labels: v3

#4523 🐛force acquire new dependency slots
  src/docfx/lib/ProcessUtility.cs
  src/docfx/restore/index/DependencySlotPool.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4527 fix: use remove instead of add to remove duplicate items
  src/Microsoft.DocAsCode.Build.Engine/ManifestUtility.cs
Labels: v2

#4530 revert vsts test
  docs/specs/restore.yml
Labels: v3

#4519 🐛remove user token and name from git remote
  docs/specs/git.yml
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Repository.cs
Labels: v3

#4521 Implement yaml tags according to spec
  src/docfx/lib/json/YamlUtility.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4533 🌐 change template token path
  docs/specs/markdown.yml
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4514 Update log code `invalid-redirection`, `attribute-reserved`, `upload-failed`
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/redirection/RedirectionMap.cs
Labels: v3

#4502 Update log code 'at-uid-not-found'
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/moniker.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/ResolveXrefExtension.cs
Labels: v3

#4526 👨‍🏭 only trust slot status for restored work tree
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4511 Update log code `github-api-failed`, `git-log-error`, `git-not-found`
  src/docfx/Errors.cs
  src/docfx/lib/git/FileCommitProvider.cs
Labels: v3

#4532 Make dependencymap output deterministic
  docs/specs/manifest.yml
  docs/specs/schema.yml
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4537 Only call github once if we don't have access to the repo
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4531 update documents
  Documentation/templates-and-plugins/plugins-dashboard.yml
  Documentation/templates-and-plugins/plugins-dashboard.yml.md
  Documentation/templates-and-plugins/templates-dashboard.yml
  Documentation/templates-and-plugins/templates-dashboard.yml.md
  Documentation/tutorial/docfx.exe_user_manual.md
  Documentation/tutorial/docfx_getting_started.md
  README.md
Labels: v2

#4534 👨‍🏭improve error message for wrong version in dependency lock
  docs/specs/restore.yml
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4543 Skip restore private vsts repo test
  docs/specs/restore.yml
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4546 clean work tree folder before using
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/index/DependencySlotPool.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4539 resolve github user by commit email only
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
Labels: v3

#4541 Expose main method
  build.ps1
  src/docfx/cli/Docfx.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4540 fix output relative path in legacy manifest and filemap
  docs/specs/legacy.yml
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/redirection/BuildRedirection.cs
Labels: v3

#4538 Sanitized command line secrets in exception messages
  src/docfx/lib/ProcessUtility.cs
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#4561 Fix a silly sanitize message bug
  src/docfx/lib/ProcessUtility.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4560 fix output path in legacy filemap
  docs/specs/legacy.yml
  src/docfx/build/context/Output.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Document.cs
Labels: v3

#4564 Don't publish test result in CI, it is too slow.
  .deploy.yml
  build.ps1
Labels: v3

#4558 improve quote float in yaml serializer
  src/Microsoft.DocAsCode.YamlSerialization/Helpers/Regexes.cs
  src/Microsoft.DocAsCode.YamlSerialization/NodeTypeResolvers/ScalarYamlNodeTypeResolver.cs
  src/Microsoft.DocAsCode.YamlSerialization/ObjectDescriptors/BetterObjectDescriptor.cs
  test/Microsoft.DocAsCode.Common.Tests/YamlSerializationTest.cs
Labels: v2

#4536 Ensures updated_at fallbacks to now when updateTimeAsCommitBuildTime is true
  docs/specs/git.yml
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  test/docfx.Test/common/TestUtility.cs
Labels: v3

#4547 Log stderr generated in process utility
  build.ps1
  src/docfx/lib/ProcessUtility.cs
Labels: v3

#4551 csproj reference shared config
  tools/SandcastleRefMapper/SandcastleRefMapper.csproj
Labels: v2

#4553 remove msdn package generator
  All.sln
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/Cache.cs
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/Entities.cs
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/Extensions.cs
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/HttpClientExtensions.cs
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn.csproj
  tools/ExternalPackageGenerators/Microsoft.DocAsCode.ExternalPackageGenerators.Msdn/Program.cs
Labels: v2

#4562 customized 404 page is not supported, report warning
  docs/specs/markdown.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4549 remove azure markdown rewriter
  All.sln
  build.ps1
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureBlockquoteBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureHtmlMetadataBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureIncludeBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureMigrationHtmlMetadataBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureMigrationIncludeBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureMigrationVideoBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureNoteBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureSelectorBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockRules/AzureVideoBlockRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureBlockquoteBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureHtmlMetadataBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureIncludeBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureMigrationIncludeBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureNoteBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureSelectorBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureBlockTokens/AzureVideoBlockToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureEngineBuilder.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureFileInfo.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureInlineRules/AzureIncludeInlineRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureInlineRules/AzureMigrationIncludeInlineRule.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureInlineTokens/AzureIncludeInlineToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureInlineTokens/AzureMigrationIncludeInlineToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureMarkdownRenderer.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureMarked.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureMigrationEngineBuilder.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureMigrationMarked.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/AzureVideoInfo.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/BasicTokens/AzureIncludeBasicToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/BasicTokens/AzureMigrationIncludeBasicToken.cs
  src/Microsoft.DocAsCode.AzureMarkdownRewriters/Microsoft.DocAsCode.AzureMarkdownRewriters.csproj
  test/Microsoft.DocAsCode.MarkdownRewriters.Tests/AzureMarkdownRewritersTest.cs
  test/Microsoft.DocAsCode.MarkdownRewriters.Tests/Microsoft.DocAsCode.MarkdownRewriters.Tests.csproj
  tools/AzureMarkdownRewriterTool/AzureFileInformationCollection.cs
  tools/AzureMarkdownRewriterTool/AzureMarkdownRewriterTool.csproj
  tools/AzureMarkdownRewriterTool/AzureTransformArguments.cs
  tools/AzureMarkdownRewriterTool/AzureVideoHelper.cs
  tools/AzureMarkdownRewriterTool/AzureVideoRawInformation.cs
  tools/AzureMarkdownRewriterTool/Program.cs
  tools/AzureMarkdownRewriterTool/RewriterToolArguments.cs
Labels: v2

#4574 Legacy OutputRelativePath should target to logic output path instead of the physial path
  docs/specs/legacy.yml
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/resource/BuildResource.cs
Labels: v3

#4572 clean up solution
  All.sln
  tools/Shared/base.props
  tools/Shared/src/Extensions.cs
  tools/Shared/xproj.base.props
Labels: v2

#4573 drop project.json support
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/FileInformation.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/FileInformationExtension.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/FileType.cs
Labels: v2

#4505 Update 'file-not-found'
  docs/specs/config.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
Labels: needs-confirm, v3

#4575 upgrade net462 => net472
  build.ps1
  src/Microsoft.DocAsCode.Build.Common/Microsoft.DocAsCode.Build.Common.csproj
  src/Microsoft.DocAsCode.Build.Engine/Microsoft.DocAsCode.Build.Engine.csproj
  src/Microsoft.DocAsCode.Build.ManagedReference/Microsoft.DocAsCode.Build.ManagedReference.csproj
  src/Microsoft.DocAsCode.Build.TableOfContents/Microsoft.DocAsCode.Build.TableOfContents.csproj
  src/Microsoft.DocAsCode.Build.UniversalReference/Microsoft.DocAsCode.Build.UniversalReference.csproj
  src/Microsoft.DocAsCode.Common/Microsoft.DocAsCode.Common.csproj
  src/Microsoft.DocAsCode.DataContracts.Common/Microsoft.DocAsCode.DataContracts.Common.csproj
  src/Microsoft.DocAsCode.DataContracts.UniversalReference/Microsoft.DocAsCode.DataContracts.UniversalReference.csproj
  src/Microsoft.DocAsCode.Dfm/Microsoft.DocAsCode.Dfm.csproj
  src/Microsoft.DocAsCode.Glob/Microsoft.DocAsCode.Glob.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Microsoft.DocAsCode.Metadata.ManagedReference.Common.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/EnvironmentHelper.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Microsoft.DocAsCode.Metadata.ManagedReference.csproj
  src/Shared/base.netstandard.props
  src/Shared/base.props
  src/docfx/docfx.csproj
  test/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests.csproj
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/Microsoft.DocAsCode.Build.SchemaDriven.Tests.csproj
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/inputs/CatLibrary.ICat.yml
  test/Microsoft.DocAsCode.Build.TableOfContents.Tests/Microsoft.DocAsCode.Build.TableOfContents.Tests.csproj
  tools/DfmHttpService/DfmHttpService.csproj
  tools/MergeDeveloperComments/MergeDeveloperComments.csproj
  tools/MergeSourceInfo/MergeSourceInfo.csproj
  tools/XRefService/ManageXRefService/XRefService.Manage.csproj
  tools/XRefService/XRefService/XRefService.Get.csproj
Labels: v2

#4581 🆙 upgrade markdig extension version
  src/docfx/docfx.csproj
Labels: v3

#4580 ⬆Upgrade glob to allow spaces
  src/docfx/docfx.csproj
  test/docfx.Test/lib/GlobUtilityTest.cs
Labels: v3

#4589 extract monikers of publishItems to decrease the manifest file size
  docs/specs/moniker.yml
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/lib/moniker/MonikerUtility.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#4593 update log message for circular-reference
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/HtmlInclusionBlockRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/HtmlInclusionInlineRenderer.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2

#4565 🐱‍👤get correct contributor display name from github
  src/docfx/Errors.cs
  src/docfx/lib/github/GitHubAccessor.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4583 Open web browser to create issues on crash
  src/docfx/cli/Docfx.cs
Labels: v3

#4590 Implement additionalProperties
  src/docfx/lib/json/ValueOrObjectConverter.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4598 Remove hash from .publish.json
  docs/specs/manifest.yml
  src/docfx/build/context/Output.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/publish/PublishItem.cs
Labels: v3

#4584 Update log message for log code 'circular-reference'
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
Labels: v3

#4585 👨‍🏭 re-implement SDP pipeline(validation and transform) using JSON schema
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/data/ContextObject.json
  src/docfx/data/LandingData.json
  src/docfx/data/TestData.json
  src/docfx/data/TestPage.json
  src/docfx/docfx.csproj
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaContentType.cs
  src/docfx/lib/schema/JsonSchemaTransform.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4603 fix json schema path
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4602 min/max items validation
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4596 support parts of $ref and definitions for json schema
  src/docfx/data/LandingData.json
  src/docfx/data/TestData.json
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaContext.cs
  src/docfx/lib/schema/JsonSchemaTransform.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4607 fix landing data html diff
  src/docfx/lib/schema/JsonSchemaTransform.cs
Labels: v3

#4604 consume order property in monikerDefinition file
  docs/designs/conceptual-versioning.md
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/Moniker.cs
  src/docfx/lib/moniker/MonikerComparer.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4594 build should not faile when sdp reference an empty UID
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/XrefInterpreter.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/Microsoft.DocAsCode.Build.SchemaDriven.Tests.csproj
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/inputs/EmptyUidReference.yml
Labels: v2

#4608 add null type to all string type properties for landing data
  src/docfx/data/LandingData.json
Labels: v3

#4606 Environment.UserInteractive does not work as we expected
  src/docfx/cli/Docfx.cs
  src/docfx/lib/ProcessUtility.cs
Labels: v3

#4587 Consolidate HtmlPostProcess
  docs/specs/resolve.yml
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  test/docfx.Test/common/TestUtility.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#4609 Fix build break caused by PR not up to date
  src/docfx/lib/schema/JsonSchemaTransform.cs
Labels: v3

#4613 Temporarily move HtmlPostProcess after applying template
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/schema/JsonSchemaTransform.cs
Labels: v3

#4600 moniker related log code refine
  docs/specs/moniker.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/config/Config.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/MonikerZone.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4612 implement min/maxLength for string
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4616 work around error under azpipeline vs2019
  UpdateTemplate.ps1
  build.ps1
Labels: v2

#4619 consume original ShouldSerialize when serialize SourceInfo property
  docs/specs/moniker.yml
  src/docfx/lib/json/JsonContractResolver.cs
Labels: v3

#4566 Wait until dir is really deleted
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4618 Update azure-pipelines.yml to exclude v3 branches
  azure-pipelines.yml
Labels: v2

#4622 Use latest-prereleased version for Microsoft.DocAsCode.MarkdigEngine.Extensions
  docs/specs/manifest.yml
  src/docfx/docfx.csproj
Labels: v3

#4624 dont call github graph again when auth failed
  src/docfx/lib/github/GitHubAccessor.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#4626 Remove old ci scripts
  .deploy.yml
  azure-pipelines.yml
  impact.ps1
Labels: v3

#4629 Fixes CI failure
  README.md
  azure-pipelines.yml
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4625 prune work tree before adding
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4635 Enable integration testing for forked repos
  azure-pipelines.yml
  docs/specs/restore.yml
Labels: v3

#4614 replace AttributeTransfrom with JsonSchemaTransfrom
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransform.cs
Labels: v3

#4630 output monikers soted by OrdinalIgnoreCase stringComparer:
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4638 🧹remove transform attributes from strong model
  src/Microsoft.Docs.Template/Models/Attributes.cs
  src/Microsoft.Docs.Template/Models/ContextObject.cs
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/Microsoft.Docs.Template/Models/TestData.cs
  src/Microsoft.Docs.Template/Models/TestPage.cs
Labels: v3

#4639 👨‍🏭remove null value check because it will be covered by json schema
  docs/specs/config.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4595 upgrade msbuild locator to support msbuild 16
  Documentation/tutorial/docfx_getting_started.md
  Documentation/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.md
  azure-pipelines.yml
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Microsoft.DocAsCode.Metadata.ManagedReference.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs
Labels: v2

#4636 Resolving same uid with multiple versioning
  docs/designs/xref.md
Labels: v3

#4651 Fix pipeline conflict by rename
  azure-pipelines-v3.yml
Labels: v3

#4640 Warn on shallow clones
  src/docfx/Errors.cs
  src/docfx/lib/git/FileCommitProvider.cs
Labels: v3

#4627 use github graph api tro get github user by login
  src/docfx/docfx.csproj
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#4642 Allow git dependencies to be local files
  docs/specs/legacy.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/Config.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4643 date-time format validation
  src/docfx/Errors.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaStringFormat.cs
  src/docfx/lib/schema/JsonSchemaValidation.cs
  test/docfx.Test/data/jschema/draft7/optional/format/date-time.json
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4652 clean existing work tree: rename and then delete
  src/docfx/restore/RestoreGit.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#4658 Theme --> Template
  azure-pipelines-v3.yml
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/restore.yml
  src/docfx/config/Config.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4654 Add metadata validation rule: dependencies
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4649 Allow source info propagation for null values
  docs/specs/metadata.yml
  src/docfx/lib/json/JTokenJsonConverter.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4661 Add Behavior, Msg Reviewed Info
  src/docfx/Errors.cs
Labels: v3

#4663 😂😂😂disable restore one test until we found the root cause of failure
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4648 validate toc name during build
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4667 [skip ci] remove siteBasePath from routes and always prepend to sitePath
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  src/docfx/docset/Document.cs
Labels: v3

#4668 remove json utility attribute validation
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SchemaContractResolver.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4656 Fix monikers of toc node
  docs/designs/conceptual-versioning.md
  docs/specs/moniker.yml
  src/docfx/build/toc/BuildTableOfContents.cs
Labels: v3

#4671 Remove unknown field check from JsonUtility
  docs/specs/config.yml
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4673 Fix the bug in time format culture-affected
  src/docfx/cli/Docfx.cs
Labels: bug, v3

#4669 Add metadata validation rule: either and precludes
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4670 get inner exception message while sending github http request
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4641 Remove ConfigFileName in favor of source info
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/localization.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/restore/Restore.cs
Labels: v3

#4683 show line: null instead of 0
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
Labels: v2

#4660 Refactoring and handle comparison between different products
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/ExternalXRefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/lib/moniker/ComparatorExpression.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/IExpression.cs
  src/docfx/lib/moniker/LogicExpression.cs
  src/docfx/lib/moniker/MonikerComparer.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3
