Repository dotnet/docfx, pull requests merged in 2019-03, with the labels that each got.

#4093 🌐fix flattening dependency map
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
Labels: v3

#4079 🥽using pooling model to restore git dependencies
  src/docfx/build/Build.cs
  src/docfx/config/AppData.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/ProcessUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencyGit.cs
  src/docfx/restore/index/DependencyGitPool.cs
  src/docfx/restore/index/DependencySlot.cs
  src/docfx/restore/index/DependencySlotPool.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4097 only find up-level toc, same behavior like v2
  src/docfx/build/toc/TableOfContentsMap.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#4096 ⬆ netcoreapp2.2
  src/docfx/docfx.csproj
  test/docfx.Test/docfx.Test.csproj
  tools/CreateJsonSchema/CreateJsonSchema.csproj
Labels: v3

#4066 update readme
  Documentation/tutorial/docfx.exe_user_manual.md
  Documentation/tutorial/docfx_getting_started.md
  README.md
Labels: v2

#4099 🎰make dependency-map and op_aggregated_file_map_info deterministic
  src/docfx/build/legacy/LegacyDependencyMap.cs
Labels: v3

#4098 🧹clean up version support for file downloading
  src/docfx/build/Build.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  src/docfx/restore/lock/DependencyLockModel.cs
Labels: v3

#4101 fix missing documentType in build model cache
  src/Microsoft.DocAsCode.Build.Common/FileModelPropertySerialization.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentProcessors/YamlDocumentModel.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentProcessors/YamlDocumentProcessor.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
Labels: v2

#4102 🧹continually clean up restore file
  src/docfx/build/Build.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/lock/DependencyLockModel.cs
  src/docfx/restore/lock/DependencyVersion.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4105 🛀Clean up some TODOs
  src/docfx/docset/Document.cs
  src/docfx/lib/github/GithubUtility.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4106 ⬇🗄always restore one url to one place
  docs/designs/restore-and-gc.md
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/moniker/MonikersProvider.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/AppData.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4108 🧹clean up todo and gc in restore
  README.md
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Program.cs
  src/docfx/gc/GarbageCollector.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
Labels: v3

#4112 add stale bot, other minor update
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/stale.yml
Labels: v2

#4114 🐞Check publish items before writing output
  src/docfx/build/Build.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
Labels: v3

#4117 remove img alt according to v2
  src/Microsoft.Docs.Template/Views/Template/BuildItemListPartial.cshtml
Labels: v3

#4118 🐞Missing menu items
  schemas/LandingData.json
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/Microsoft.Docs.Template/Views/Template/LandingData.cshtml
Labels: v3

#4109 🌏Add &lrm; marker
  docs/specs/localization.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/localization/LocalizationUtility.cs
Labels: v3

#4121 🚢Push to MyGet prod feed from v3-release branch
  .deploy.yml
Labels: v3

#4122 fix: incremental build should replay suggestion level logs
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/BuildMessageInfo.cs
Labels: bug, v2

#4120 fix dependencyType when contains query string
  src/Microsoft.DocAsCode.Build.Engine/CompilePhaseHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkupResultUtility.cs
Labels: v2

#4111 🎶rename restore map and design spec
  docs/designs/restore-file-and-git.md
  src/docfx/build/Build.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/moniker/MonikersProvider.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencyGitPool.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#4126 📄handle YAML special string value
  src/docfx/lib/YamlUtility.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4128 🚮Don't gen .mta.json for resources
  docs/specs/legacy.yml
  src/docfx/build/resource/BuildResource.cs
Labels: v3

#4129 📄Document that line info is one based
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/Range.cs
  src/docfx/lib/log/Error.cs
Labels: v3

#4127 Expose markdown line info through MarkdownContext
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/HtmlInclusionBlockRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/InclusionBlockParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/HtmlInclusionInlineRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/InclusionInlineParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MonikerRange/MonikerRangeParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/NestedColumn/NestedColumnParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/QuoteSectionNote/QuoteSectionNoteParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Row/RowParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TabGroup/ActiveAndVisibleRewriter.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigEngine/Validation/TagValidator.cs
  src/Microsoft.DocAsCode.MarkdigEngine/YamlHeader/YamlHeaderRenderer.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/ValidationTest.cs
Labels: v3

#4133 Remove .mta.json entry from manifest
  src/docfx/build/legacy/manifest/LegacyManifest.cs
Labels: v3

#4135 📝log code update(spelling and unreferenced)
  src/docfx/Errors.cs
Labels: v3

#4134 📈 Limit telemetry flush time to 2s
  src/docfx/lib/log/Telemetry.cs
Labels: v3

#4130 📄Add line/column info to markdown errors
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/xref.yml
  src/docfx/docfx.csproj
  src/docfx/lib/log/Error.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveHtmlLinks.cs
  src/docfx/lib/markdown/ResolveXref.cs
Labels: v3

#4131 📝Add suggestion level
  schemas/docfx.json
  src/docfx/cli/Program.cs
  src/docfx/lib/log/ErrorLevel.cs
  src/docfx/lib/log/Report.cs
Labels: v3

#4132 remove non-UserDefinedTitle when validating conceptual metadata
  src/Microsoft.DocAsCode.Build.ConceptualDocuments/ValidateConceptualDocumentMetadata.cs
Labels: v2

#4147 glob apply exclude first
  src/docfx/lib/GlobUtility.cs
Labels: v3

#4146 resolve absolute file path as empty string
  docs/specs/resolve.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/lib/HrefType.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4148 ⏬ Keep using HtmlAgilityPack 1.4.9 during migration
  docs/specs/markdown.yml
  src/docfx/docfx.csproj
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  src/docfx/lib/YamlUtility.cs
Labels: v3

#4150 🔗Escape git related URLs
  docs/specs/escape.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#3903 Split null-array-value from null-value
  src/docfx/Errors.cs
  src/docfx/lib/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4153 Split bookmark-not-found
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BookmarkValidator.cs
Labels: v3

#4158 Compile a list of error code without line info
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4156 include-is-redirection should be error
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4152 📄Make JSON property deserialization case sensitive
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4157 log how long GitHub expect us to wait for retry
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4161 👀Remove [HTML] since there is no need to resolve href within HTML
  src/Microsoft.Docs.Template/Models/LandingData.cs
Labels: v3

#4170 Add back resolving href for landing page, mute file-not-found for landing page
  docs/specs/legacy.yml
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/AttributeTransformer.cs
Labels: v3

#4176 Update System.CommandLine
  src/docfx/docfx.csproj
Labels: v3

#4167 Update copyright text from 2018 to 2019.
  Documentation/docfx.json
  src/docfx.website.themes/default/partials/_footer.liquid
Labels: v2

#4168 🔗Do not escape all URLs
  docs/specs/escape.yml
  docs/specs/resolve.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
Labels: v3

#4183 stablize nearest toc
  src/Microsoft.DocAsCode.Build.Engine/SystemMetadataGenerator.cs
Labels: v2

#4184 🚢 V3 Release Deployment
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  schemas/docfx.json
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/FileMetadata.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/cli/Program.cs
  src/docfx/docfx.csproj
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/HrefType.cs
  src/docfx/lib/HrefUtility.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  src/docfx/lib/YamlUtility.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLevel.cs
  src/docfx/lib/log/Report.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveHtmlLinks.cs
  src/docfx/lib/markdown/ResolveXref.cs
  src/docfx/template/TemplateTransform.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/HrefUtilityTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4140 add vsts test cases for docfx restore
  docs/specs/restore.yml
Labels: v3

#4186 🐛fix test and add todo
  docs/specs/restore.yml
Labels: v3

#4188 Update build.ps1 to generate correct version number
  build.ps1
Labels: v3

#4189 🚢Ship
  build.ps1
  docs/specs/restore.yml
Labels: v3

#4187 🦑Fix GitHub user cache making unnecessary API calls
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4190 💬Log docfx version in verbose mode
  src/docfx/cli/Program.cs
  src/docfx/lib/log/Progress.cs
Labels: v3

#4192 `== null` --> `is null`
  src/docfx/build/Build.cs
  src/docfx/build/dependency/DependencyItem.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/docset/Document.cs
  src/docfx/docset/Repository.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/Levenshtein.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/lib/YamlUtility.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/log/Report.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/moniker/ExpressionCreator.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencySlotPool.cs
  src/docfx/template/liquid/LiquidFilter.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/RetryUtilityTest.cs
  tools/CreateJsonSchema/Program.cs
Labels: v3

#4193 Do not log github-user-not-found error in GetByCommit
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4185 perf: don't apply global/file metadata for resource
  src/Microsoft.DocAsCode.Build.Engine/HostServiceCreator.cs
  src/Microsoft.DocAsCode.Build.ResourceFiles/ResourceDocumentProcessor.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
Labels: v2

#4195 🧹Remove MarkupResult.HasHtml
  src/docfx/lib/markdown/MarkupResult.cs
  src/docfx/lib/markdown/ResolveHtmlLinks.cs
Labels: v3

#4179 Add _noindex to fileMetadata in user guide
  Documentation/tutorial/docfx.exe_user_manual.md
Labels: v2

#4166 ✍contributor, author, updated_at for vsts repo
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4198 Make metadata validation case sensitive
  docs/specs/metadata.yml
  src/docfx/build/metadata/MetadataValidator.cs
Labels: v3

#4199 🐛add auth token and log for spec test
  .deploy.yml
  docs/specs/git.yml
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4196 🚁show (original) content git (branch/commit) url for azure repo
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/azure/AzureRepoUtility.cs
  src/docfx/lib/github/GithubUtility.cs
  test/docfx.Test/lib/AzureRepoUtility.cs
  test/docfx.Test/lib/GitHubUtilityTest.cs
Labels: v3

#4202 🐛fix private azure repo test since it's never executed before...
  docs/specs/restore.yml
Labels: v3

#4205 🐛fix flaky test for restoring with dependency lock
  docs/specs/restore.yml
Labels: v3

#4207 add line info to test which only run during deployment build
  docs/specs/restore.yml
Labels: bug, v3

#4151 🌐☁add spec test for localization convention vsts support
  docs/specs/localization.yml
Labels: v3

#4208 🌐Bulk get GitHub commits
  src/docfx/build/context/Context.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4200 🐞 Make legacy output deterministic in case of conflict
  docs/specs/legacy.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/docset/Document.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4211 fix legacy aggregated file map diff
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
Labels: v3

#4212 perf: avoid multiple enumeration when creating glob matcher
  src/Microsoft.DocAsCode.Glob/FileGlob.cs
Labels: v2

#4203 perf: use StringComparison.Ordinal(IgnoreCase)
  plugins/Microsoft.DocAsCode.Build.MemberLevelManagedReference/SplitClassPageToMemberLevel.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/FileCollection.cs
  src/Microsoft.DocAsCode.Build.Engine/LinkPhaseHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/DfmJsonTokenTreeServiceProvider.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/JsonTokenTreeServiceProvider.cs
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/PostProcessorsHandlerWithIncremental.cs
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/SitemapGenerator.cs
  src/Microsoft.DocAsCode.Build.Engine/SystemMetadataGenerator.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Preprocessors/TemplateJintPreprocessor.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Template.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/ViewRenderers/ParseTemplateHelper.cs
  src/Microsoft.DocAsCode.Build.Engine/XRefMaps/XRefRedirectionReader.cs
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
  src/Microsoft.DocAsCode.Build.OverwriteDocuments/OverwriteUtility.cs
  src/Microsoft.DocAsCode.Build.RestApi/RestApiHelper.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/HrefInterpreter.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/TagInterpreters/PatternedTagInterpreter.cs
  src/Microsoft.DocAsCode.Common/CompositeDictionary.cs
  src/Microsoft.DocAsCode.Common/FileAbstractLayer/LinkFileWriter.cs
  src/Microsoft.DocAsCode.Common/FileAbstractLayer/RealFileReader.cs
  src/Microsoft.DocAsCode.Common/Path/PathUtility.cs
  src/Microsoft.DocAsCode.Common/Path/RelativePath.cs
  src/Microsoft.DocAsCode.Common/StringExtension.cs
  src/Microsoft.DocAsCode.Common/YamlMime.cs
  src/Microsoft.DocAsCode.Dfm/DfmInclusionLoader.cs
  src/Microsoft.DocAsCode.Dfm/DfmRenderer.cs
  src/Microsoft.DocAsCode.Glob/GlobMatcher.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippet.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Interactive/InteractiveBaseRewriter.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigMarkdownRewriters/MarkdigMarkdownRenderer.cs
  src/Microsoft.DocAsCode.MarkdownLite/JsonTokenTreeRenderer.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Models/ReferenceItem.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpCompilation.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpProjectInfo.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/NameVisitor.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/EnvironmentHelper.cs
  src/Microsoft.DocAsCode.Plugins/FileModel.cs
  src/Microsoft.DocAsCode.YamlSerialization/ObjectDescriptors/BetterObjectDescriptor.cs
  src/Microsoft.DocAsCode.YamlSerialization/TypeInspectors/EmitTypeInspector.cs
Labels: v2

#4213 save one ToArray, check exclude patterns
  src/docfx/Glob/GlobUtility.cs
Labels: v2

#4214 Update docfx_flavored_markdown.md
  Documentation/spec/docfx_flavored_markdown.md
Labels: v2

#4215 🧚‍♀️Support inclusion in titles
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/ExtractTitle.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/MarkupResult.cs
Labels: v3

#4218 Fix landing page
  src/Microsoft.Docs.Template/Views/Template/LandingData.cshtml
Labels: v3

#4220 Log whether repo cache or git commit cache is hit
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#4223 remove ending '/' in git remote url
  src/docfx/lib/HrefUtility.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#4217 minor improve incremental message, log => verbose
  src/Microsoft.DocAsCode.Build.Engine/Incrementals/IncrementalBuildContext.cs
Labels: v2

#4224 Fix h1 extraction skipping non empty text
  docs/specs/markdown.yml
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4221 🧹Remove MarkupResult and ConceptualMarkdown
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/lib/markdown/MarkdownPipelineType.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/ResolveXref.cs
Labels: v3

#4229 open_to_public_contributors is a template only metadata
  docs/specs/git.yml
  docs/specs/manifest.yml
  schemas/docfx.json
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/PageModel.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4228 Update GitHubUserCache to handle multiple emails
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/github/GitHubUserCache.cs
Labels: v3

#4227 stablize nearest toc dependency
  src/Microsoft.DocAsCode.Build.TableOfContents/BuildTocDocument.cs
Labels: v2

#4230 resolve title from h1 - h3
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4231 perf: cut resource meta
  src/Microsoft.DocAsCode.Build.ResourceFiles/ResourceDocumentProcessor.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
Labels: v2

#4216 🐛get true latest version of dependency git without lock
  docs/specs/restore.yml
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencySlotPool.cs
Labels: bug, v3

#4194 🛠Config validation
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/MetadataValidator.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/JsonUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4235 Do not modify collection during iteration.
  docs/specs/config.yml
  src/docfx/config/ConfigLoader.cs
Labels: v3

#4236 Turn whitespaces into <div></div>
  src/docfx/build/page/BuildPage.cs
Labels: v3

#4197 Move resolve link outside markdown extension core
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigEngine/ResolveLink/ResolveLinkExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2, v3

#4234 Prefer existing user name when updating user cache from commit
  src/docfx/lib/github/GitHubUserCache.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4238 fix abstract for landing page
  src/Microsoft.Docs.Template/Views/Template/LandingData.cshtml
Labels: v3

#4239 fix landing page link resolver hacking
  docs/specs/legacy.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/AttributeTransformer.cs
Labels: v3

#4237 Add line info for bookmark validation
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/lib/JsonUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4240 🐛fix h1 remove and extract logic
  docs/specs/markdown.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4242 Show line: 0 instead of an empty string
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
Labels: v2

#4243 🐛set title to null instead of empty string if the title can't be resolved
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  src/docfx/build/page/BuildPage.cs
Labels: v3

#4244 🐛make metadata black list case sensitive
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4245 ✨redirection out scope `warning` -> `info`
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/Errors.cs
Labels: v3

#4246 Uri.UnescapeDataString --> HtmlUtility.UrlDecode
  docs/specs/escape.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4251 remove include-is-redirection
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4247 fix unexpected warning on self bookmark in included file
  docs/specs/resolve.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BookmarkValidator.cs
Labels: v3

#4252 only assign value to raw title when title is removed from html
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#4254 trim ext name in redirection href
  docs/specs/legacy.yml
  src/docfx/docset/Document.cs
Labels: v3

#4248 add rawTitle to ManifestProperties
  src/Microsoft.DocAsCode.Build.ConceptualDocuments/BuildConceptualDocument.cs
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/ValidateBookmark.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/ValidateBookmarkTest.cs
Labels: v2

#4260 remove rawTitle from final manifest
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/RemoveDebugInfo.cs
Labels: v2

#4261 🐛never expire test user cache
  test/docfx.Test/docfx.test.yml
Labels: v3

#4262 ⚒split docset and template
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/page/AttributeTransformer.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/docset/Docset.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateTransform.cs
Labels: v3

#4268 update release note
  RELEASENOTE.md
Labels: v2

#4269 include group info in DuplicateOutputFiles warning
  src/Microsoft.DocAsCode.Build.Engine/ManifestUtility.cs
Labels: v2
