Repository dotnet/docfx, pull requests merged in 2019-06, with the labels that each got.

#4688 💣 Fix a critical test validation bug and corresponding cases
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/schema.yml
  test/docfx.Test/common/TestUtility.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4692 update axios
  tools/Deployment/package.json
Labels: v2

#4690 Some user doesn't have name, use login instead
  src/docfx/lib/github/GitHubAccessor.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#4685 Metadata validation extension rules: 'dateFormat', 'dateRange', 'deprecated'
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4696 add code owner back to suppress draft pr notification
  .github/CODEOWNERS
Labels: v3

#4679 RunInsideMutex --> InterProcessMutex
  src/docfx/lib/process/InterProcessMutex.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/index/DependencySlotPool.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#4684 Use actual file name casing
  docs/specs/casing.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/docset/Docset.cs
Labels: v3

#4707 🐛add retry for intermittent http request io exception
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#4706 Fix linux test failure
  docs/specs/casing.yml
  src/docfx/docset/Docset.cs
Labels: v3

#4710 disable incremental when schema changes
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Models/DocumentSchema.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/SchemaDrivenDocumentProcessor.cs
Labels: v2

#4716 Add integration test PR comment
  azure-pipelines-v3.yml
Labels: v3

#4715 test disable incremental when schema changes
  Documentation/spec/docfx_document_schema.md
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/Microsoft.DocAsCode.Build.Engine.Tests.csproj
  test/Microsoft.DocAsCode.Tests.Common/TestBase.cs
Labels: v2

#4700 update the moniker resolved spec for different types of Toc node
  docs/designs/conceptual-versioning.md
  docs/specs/moniker.yml
Labels: v3

#4674 Fix for populating xref map
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/build/xref/XrefMapLoader.cs
  src/docfx/docfx.csproj
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/build/XrefMapLoaderTest.cs
Labels: auto-merge, v3

#4711 Consolidate MetadataProvider and MonikerProvider
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/ExternalXRefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: auto-merge, v3

#4724 add homepage back in toc output
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4712 add locale checker before appending locale to absolute url
  src/docfx/lib/HtmlUtility.cs
  src/docfx/localization/LocalizationUtility.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: auto-merge, v3

#4708 VS2019 MSBuild adaptions
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs
  src/docfx/app.config
Labels: v2

#4720 add log code for fatal error
  src/Microsoft.DocAsCode.Common/Loggers/ErrorCodes.cs
  src/docfx/Program.cs
Labels: v2

#4729 release 2.43
  RELEASENOTE.md
Labels: v2

#4730 homepage only shows when topic href is set
  docs/specs/toc.yml
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4702 resolve toc node moniker inside LoadToc function since the document info is lost after LoadToc
  docs/specs/moniker.yml
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: auto-merge, v3

#4731 DataContracts support netstandard
  src/Microsoft.DocAsCode.DataContracts.Common/Microsoft.DocAsCode.DataContracts.Common.csproj
  src/Microsoft.DocAsCode.DataContracts.ManagedReference/Microsoft.DocAsCode.DataContracts.ManagedReference.csproj
  src/Microsoft.DocAsCode.DataContracts.RestApi/Microsoft.DocAsCode.DataContracts.RestApi.csproj
  src/Microsoft.DocAsCode.DataContracts.UniversalReference/Microsoft.DocAsCode.DataContracts.UniversalReference.csproj
Labels: v2

#4734 build toc file as the same time with other type of document and remove MonikerMap
  docs/specs/moniker.yml
  src/docfx/build/Build.cs
  src/docfx/build/moniker/MonikerMap.cs
  src/docfx/build/moniker/MonikerMapBuilder.cs
  src/docfx/build/toc/BuildTableOfContents.cs
Labels: auto-merge, v3

#4732 Add {APP_BASE_PATH} for testing purpose
  docs/specs/moniker.yml
  test/docfx.Test/data/monikers.json
  test/docfx.Test/e2e/E2ETest.cs
Labels: auto-merge, v3

#4723 Remove error level info
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/docset/Docset.cs
  src/docfx/lib/log/ErrorLevel.cs
  test/docfx.Test/docfx.test.yml
  test/docfx.Test/lib/ErrorLogTest.cs
Labels: auto-merge, v3

#4736 UID resolving should respect the order of xref list config.
  docs/specs/xref.yml
  src/docfx/build/xref/XrefMapBuilder.cs
Labels: v3

#4693 do not warn if referenced xref propery is null
  src/Microsoft.DocAsCode.Common/XrefUtility.cs
Labels: v2

#4739 add sourcePath to publish manifest
  docs/specs/manifest.yml
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/publish/PublishItem.cs
Labels: v3

#4740 🚢🚢🚢 Ship v3 prod
  docs/specs/config.yml
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/manifest.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Cache.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerMap.cs
  src/docfx/build/moniker/MonikerMapBuilder.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/ExternalXRefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/build/xref/XrefMapLoader.cs
  src/docfx/docfx.csproj
  src/docfx/docset/Docset.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/log/ErrorLevel.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/localization/LocalizationUtility.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/build/XrefMapLoaderTest.cs
  test/docfx.Test/data/monikers.json
  test/docfx.Test/docfx.test.yml
  test/docfx.Test/e2e/E2ETest.cs
  test/docfx.Test/lib/ErrorLogTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#4725 🧹 Remove GitHub user cache remote update
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/config/AppData.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/lib/HttpClientUtility.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/github/GitHubUserCacheFile.cs
  src/docfx/restore/RestoreFile.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: auto-merge, v3

#4694 transform `xref` property to `xref spec`(object) instead of `href`(string)
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4749 Add metadata validation rule: dependentEnums
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4743 resolve relative redirect-url
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/docset/Document.cs
  src/docfx/lib/PathUtility.cs
  test/docfx.Test/lib/PathUtilityTest.cs
Labels: v3

#4735 Turn SourceInfo<T> into a struct
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/docset/Schema.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#4722 append version and is_moniker_range info in filemap.json
  docs/specs/legacy.yml
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
Labels: v3

#4752 republish asset and chocolatey
  tools/Deployment/gulpfile.js
Labels: v2

#4755 fix deploy scripts
  tools/Deployment/gulpfile.js
  tools/Deployment/lib/github.ts
  tools/Deployment/lib/githubApi.ts
Labels: v2

#4756 Whitelist #top during bookmark validation
  docs/specs/markdown.yml
  src/docfx/build/page/BookmarkValidator.cs
Labels: v3

#4753 remove schema from document and delete some strong models
  src/Microsoft.Docs.Template/Models/ContextObject.cs
  src/Microsoft.Docs.Template/Models/TestData.cs
  src/Microsoft.Docs.Template/Models/TestPage.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/docset/Document.cs
  src/docfx/docset/Schema.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/template/RazorTemplateTest.cs
Labels: v3

#4718 Render original content for short xref inline inside links
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Xref/HtmlXrefInlineRender.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/XrefTest.cs
Labels: v2, v3

#4757 trim trailing 'index' in rediret to when with id
  docs/specs/metadata.yml
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/docset/Document.cs
Labels: v3

#4759 update git-clone-failed message
  src/docfx/Errors.cs
Labels: v3

#4659 👨‍🏭 respect xrefProperties to generate xref spec
  docs/specs/xref.yml
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/data/TestData.json
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/RetryUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#4762 Redirections are dependent on build scope
  docs/specs/config.yml
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/docset/Docset.cs
Labels: v3

#4760 Add JsonSchema const validation
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4764 🐛 fix one JSON schema transform test failure
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4766 All.sln --> docfx.sln
  Documentation/guideline/engineering_guidelines.md
  README.md
  docfx.sln
Labels: v2

#4763 Fix for parsing query string when typo happens.
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyResolver.cs
Labels: v3

#4744 register mono msbuild path
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs
Labels: v2

#4768 🧹no need href info anymore since it's calculated in parser
  src/docfx/build/context/Cache.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#4726 👨‍🏭 keep user write metadata as much as possible
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputModel.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4588 Use absolute URL for intermediate representation
  docs/specs/resolve.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/LinkType.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/markdown/MonikerZoneExtension.cs
  src/docfx/lib/markdown/ResolveLinkExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#4761 Add JSON schema number validation
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4774 enable debug info by flag in docfx.json
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/HtmlPostProcessor.cs
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/PostProcessorsManager.cs
Labels: v2

#4773 split output model and output metadata, consistent conceptual and sdp build pipeline
  docs/specs/legacy.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/Microsoft.Docs.Template/Models/Attributes.cs
  src/Microsoft.Docs.Template/Models/Conceptual.cs
  src/Microsoft.Docs.Template/Models/LandingData.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputMetadata.cs
Labels: v3

#4769 remove toc load, use toc parser directly
  src/docfx/build/context/Cache.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4767 change json schema transform from `replace` to `return`
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4779 only transform based on schema defined in properties
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4780 ResolveLink --> ResolveAbsoluteLink
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4772 ✔xref resolving
  docs/specs/localization.yml
  docs/specs/moniker.yml
  docs/specs/xref.yml
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#4776 Support JsonSchema patternProperties
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#4771 Fixed truncated string in the "IN THIS ARTICLE" section
  src/docfx.website.themes/default/styles/docfx.css
Labels: v2

#4770 Fixed issues when clicking on anchor links of the default website template
  src/docfx.website.themes/default/styles/docfx.js
Labels: v2

#4775 Extract BuildScope outside Docset
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsMapBuilder.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/docset/Docset.cs
  src/docfx/localization/LocalizationUtility.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#4786 release 2.43.2
  RELEASENOTE.md
Labels: v2

#4787 change output model to _tocRel
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/toc.yml
  src/docfx/build/metadata/InputMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputMetadata.cs
Labels: v3

#4790 lazy toc map and xref map in context, control the init order
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/lib/collections/WorkQueue.cs
  test/docfx.Test/lib/WorkQueueTest.cs
Labels: v3

#4795 remove bilingual type from output metadata, just use enable_loc_sxs
  src/docfx/build/page/OutputMetadata.cs
Labels: v3

#4794 append version info to legacy fileMap, dependencyMap and aggregatedFileMap
  docs/specs/legacy.yml
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyDependencyMapItem.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyVersionProvider.cs
Labels: v3

#4788 Make BaseUrl respect LowerCaseUrl
  docs/specs/metadata.yml
  src/docfx/config/Config.cs
  src/docfx/lib/json/JsonContractResolver.cs
Labels: v3

#4798 remove dependencyMap from manifest
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  test/docfx.Test/e2e/E2ESpec.cs
Labels: v3

#4789 Resolve template schema
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/rendering.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionMap.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefMapBuilder.cs
  src/docfx/data/schemas/LandingData.json
  src/docfx/docset/Document.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  src/docfx/lib/schema/JsonSchemaContentType.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/DocumentTest.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/data/template/ContentTemplate/Conceptual.mta.json.js
  test/docfx.Test/data/template/ContentTemplate/schemas/ContextObject.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/LandingData.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestData.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestPage.schema.json
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4754 flatten toc (folder) inclusion dependency map
  docs/specs/toc.yml
  src/docfx/build/dependency/DependencyType.cs
  src/docfx/build/toc/parser/TableOfContentsParser.cs
Labels: v3

#4783 Handle xref monikers at build time
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMap.cs
  src/docfx/build/xref/XrefMapModel.cs
  src/docfx/lib/collections/ListBuilder.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/build/XrefMapLoaderTest.cs
Labels: v3

#4801 all errors which are reported by thrown canot be adjusted by user
  docs/specs/toc.yml
  src/docfx/build/Build.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/parser/MarkdownTocMarkup.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#4796 Update markdig extensions
  azure-pipelines-v3.yml
  src/docfx/docfx.csproj
Labels: v3

#4784 Refactor bookmark validator
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/lib/GitUtilityTest.cs
Labels: v3

#4804 Don't throw need restore when the content is empty
  docs/specs/restore.yml
  src/docfx/restore/RestoreMap.cs
  test/docfx.Test/e2e/E2ETest.cs
Labels: v3

#4803 🧹 Remove WithSourceInfo
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/github/GitHubUserCache.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/markdown/MarkdownUtility.cs
  test/docfx.Test/lib/GitHubUserCacheTest.cs
Labels: v3

#4802 Remove filePath and etag from `GetRestoredFileContent`
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/docset/Docset.cs
  src/docfx/restore/RestoreFile.cs
  src/docfx/restore/RestoreMap.cs
  src/docfx/restore/lock/DependencyLock.cs
Labels: v3

#4799 Metadata validation extension rules: microsoftAlias
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/MicrosoftGraphConfig.cs
  src/docfx/docfx.csproj
  src/docfx/lib/msgraph/MicrosoftAlias.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphAuthenticationProvider.cs
  src/docfx/lib/msgraph/MicrosoftGraphCache.cs
  src/docfx/lib/msgraph/MicrosoftGraphCacheFile.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/lib/schema/MicrosoftAliasSchema.cs
Labels: v3

#4806 only apply template for conceptual content
  docs/specs/legacy.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputMetadata.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#4809 Remove TemplateEngine.PreprocessMetadata
  docs/specs/legacy.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/OutputMetadata.cs
  src/docfx/template/JavascriptEngine.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/template/JavascriptEngineTest.cs
Labels: v3
