Repository dotnet/docfx, pull requests merged in 2020-05, with the labels that each got.

#5854 Detect circular redirection
  docs/specs/redirection.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5862 credential key should be case-insensitive
  src/docfx/config/PreloadConfig.cs
Labels: v3

#5861 only encode ampersand and double quotes for metadata value
  src/docfx/lib/HtmlUtility.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5863 always output object style report
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/ecma2Yaml.yml
  docs/specs/escape.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/ops.yml
  docs/specs/output.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/static.yml
  docs/specs/toc.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5864 Apply source map for dependency map
  docs/specs/output.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyItem.cs
  src/docfx/build/dependency/DependencyMap.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/XrefResolver.cs
Labels: v3

#5857 211833 change code error to warning
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ChromelessFormExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ZoneExtension.cs
Labels: v2, v3

#5858 Pass default user style sheet to wkhtmltopdf only if it exists
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfOptions.cs
Labels: v2

#5865 Add empty heading validation rule
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5866 validation skip level headings
  docs/specs/validation.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5867 fix bugs of headings in inclusion
  docs/specs/validation.yml
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5868 apply source map for more output
  docs/specs/output.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/publish/PublishItem.cs
Labels: v3

#5871 Handle <xref> with neither href nor uid
  docs/specs/xref.yml
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5870 Fix missing-paired-attribute error rename
  src/docfx/Errors.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5877 update ecma2yaml nuget
  docs/specs/ecma2Yaml.yml
  src/docfx/docfx.csproj
Labels: v3

#5879 fix crash on versioning file redirect to url of non-versioning file
  docs/specs/redirection.yml
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5875 Process toc nodes in parallel
  docs/specs/output.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
Labels: v3

#5880 Move strip tags to HtmlExtension
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlToken.cs
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5884 211317 downgrade error to warning for complex image
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
Labels: v2, v3

#5882 msgraph cache missing users
  azure-pipelines-v3.yml
  docs/specs/validation.yml
  src/docfx/config/AppData.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphUser.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5885 🚆🚆
  azure-pipelines-v3.yml
  docs/specs/ecma2Yaml.yml
  docs/specs/output.yml
  docs/specs/redirection.yml
  docs/specs/toc.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/config/AppData.cs
  src/docfx/docfx.csproj
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlToken.cs
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphUser.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5887 Pin markdig extension version
  src/docfx/docfx.csproj
Labels: v3

#5889 Support name**.yml
  src/docfx/lib/GlobUtility.cs
  test/docfx.Test/lib/GlobUtilityTest.cs
Labels: v3

#5874 check if the markdown object is visible
  src/docfx/lib/markdown/MarkdigUtility.cs
  test/docfx.Test/lib/MarkdigUtilityTest.cs
Labels: v3

#5894 Print library version
  src/docfx/cli/Docfx.cs
Labels: v3

#5891 Deprecate and decouple InclusionContext
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/HtmlInclusionBlockRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/HtmlInclusionInlineRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/ResolveLink/ResolveLinkExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/TestUtility.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2, v3

#5896 Upgrade markdig extensions
  docs/specs/escape.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MarkdownTelemetryExtension.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  test/docfx.Test/lib/MarkdownElementTelemetryExtensionTest.cs
Labels: v3

#5897 Use inline codesign
  azure-pipelines-master.yml
  azure-pipelines-stable.yml
  codesign_policy.json
Labels: v2

#5899 Skip circular redirection validation for redirection with query string
  docs/specs/redirection.yml
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5901 early break for some visible nodes
  src/docfx/lib/markdown/MarkdigUtility.cs
  test/docfx.Test/lib/MarkdigUtilityTest.cs
Labels: v3

#5890 Add heading no content validation
  docs/specs/validation.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/validation/ContentValidator.cs
  test/docfx.Test/lib/MarkdigUtilityTest.cs
Labels: v3

#5904 Use resolved to mark xref resolved in SDP
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/MustacheXrefTagParser.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5906 Referenced image in fallback origin should also be built in static output mode
  docs/specs/static.yml
  src/docfx/build/Build.cs
Labels: v3

#5908 add logging for ecma2yaml
  src/docfx/build/Build.cs
  src/docfx/config/ops/OpsPreProcessor.cs
Labels: v3

#5907 Precompute FilePath hashcode
  src/docfx/lib/path/FilePath.cs
Labels: v3

#5903 214972 code snippet fix
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetExtractor.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2, v3

#5910 Skip logging when error code is missing
  src/docfx/config/ops/OpsPreProcessor.cs
Labels: v3

#5911 Attach FilePath to markdown node
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/TableOfContentsParser.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/IncludeExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MonikerZoneExtension.cs
  src/docfx/lib/markdown/XrefExtension.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5912 Turn InclusionBlock into ContainerBlock
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/ExtensionsHelper.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/InclusionBlock.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionBlock/InclusionBlockParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/InclusionInline.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Inclusion/InclusionInline/InclusionInlineParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs
Labels: v2, v3

#5913 Add roslyn-api and sql-docs to integration-test
  azure-pipelines-v3.yml
Labels: v3

#5920 Add parent source info list
  docs/specs/validation.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5923 Fork regression test
  docfx.sln
  test/Directory.Build.props
  test/docfx.RegressionTest/Options.cs
  test/docfx.RegressionTest/RegressionTest.cs
  test/docfx.RegressionTest/docfx.RegressionTest.csproj
  test/docfx.Test/docfx.Test.csproj
Labels: v3

#5924 Monikers should be aggregated from YAML files generated from .xml
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
Labels: v3

#5914 Update test and make log file relative to docset path
  docs/specs/ecma2Yaml.yml
  src/docfx/docfx.csproj
Labels: v3

#5916 Added ability to set the path to wkhtmltopdf.exe instead of requiring it to be set in the PATH environment variable
  Documentation/tutorial/docfx.exe_user_manual.md
  src/Microsoft.DocAsCode.HtmlToPdf/Constants.cs
  src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfOptions.cs
  src/Microsoft.DocAsCode.HtmlToPdf/PdfOptions.cs
  src/docfx/Models/WkhtmltopdfJsonConfig.cs
  src/docfx/SubCommands/DocumentBuilderWrapper.cs
  src/docfx/SubCommands/PdfCommand.cs
  test/docfx.Tests/JsonConverterTest.cs
Labels: v2

#5925 Integrate new version with Docfx v3
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5922 File reference in fallback origin should also be resolved to docs site URL in static output mode
  docs/specs/static.yml
  src/docfx/build/link/LinkResolver.cs
Labels: v3

#5928 Fix WriteStartTag size hint
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlWriter.cs
Labels: v3

#5929 Upgrade markdig extensions
  docs/specs/markdown.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/FilePathExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
Labels: v3

#5921 Expand markdown include syntax tree
  docs/specs/output.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/lib/markdown/FencedCodeExtension.cs
  src/docfx/lib/markdown/IncludeExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5932 JValue empty string as falsy
  src/docfx/template/MustacheTemplate.cs
  test/docfx.Test/data/mustache/list.tmpl
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#5927 218505 add video extension
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/QuoteSectionNote/QuoteSectionNoteRender.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/VideoExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/VideoTest.cs
Labels: v2, v3

#5933 Upgrade markdig to the latest version
  src/Microsoft.DocAsCode.Build.OverwriteDocuments/Microsoft.DocAsCode.Build.OverwriteDocuments.csproj
  src/Microsoft.DocAsCode.Build.SchemaDriven/Microsoft.DocAsCode.Build.SchemaDriven.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/Microsoft.DocAsCode.MarkdigEngine.Validators.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
  test/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests.csproj
  tools/YamlSplitter/YamlSplitter.csproj
Labels: v2, v3

#5935 Fix nullability warnings for CompareTo and Equals
  azure-pipelines-v3.yml
  src/docfx/build/document/Document.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/publish/PublishItemComparer.cs
Labels: v3

#5934 Avoid mutating command line options when running in parallel
  src/docfx/build/Build.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5936 Upgrade markdig extensions
  docs/specs/escape.yml
  src/docfx/docfx.csproj
Labels: v3

#5938 Update validation version to 1.2.26-beta002
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5939 Fix misleading chakra exception when require callback throws
  src/docfx/cli/Docfx.cs
  src/docfx/lib/js/ChakraCoreJsEngine.cs
Labels: v3

#5940 Remove LiquidFilter
  src/docfx/template/liquid/LiquidFilter.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/template/LiquidFilterTest.cs
Labels: v3

#5941 Use HtmlReader in MustacheXrefTagParser
  src/docfx/template/MustacheXrefTagParser.cs
Labels: v3

#5937 Move extract title to markdown engine
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ConceptualModel.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/collections/CollectionUtility.cs
  src/docfx/lib/markdown/ExtractTitleExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5942 stop publishing to myget, now azdevops only
  README.md
  tools/Deployment/config_gulp.json
  tools/Deployment/gulpfile.js
  tools/Deployment/lib/nuget.ts
Labels: v2

#5943 Upgrade ecma2yaml
  src/docfx/docfx.csproj
Labels: v3

#5948 fix nuget push
  tools/Deployment/lib/nuget.ts
Labels: v2

#5950 Link definition before h1 is treated as invisible
  docs/specs/markdown.yml
  src/docfx/lib/markdown/MarkdigUtility.cs
Labels: v3

#5951 Update integration test repos
  azure-pipelines-v3.yml
Labels: v3

#5947 Remove myget
  README.md
  azure-pipelines-v3.yml
Labels: v3

#5952 Handle inline include with multiple paragraphs
  docs/specs/markdown.yml
  src/docfx/lib/markdown/IncludeExtension.cs
Labels: v3

#5949 release 2.54
  RELEASENOTE.md
Labels: v2

#5955 Update validation version to 1.2.26-beta004
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5958 🚢🚢
  docs/specs/validation.yml
  src/docfx/build/Build.cs
  src/docfx/docfx.csproj
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5945 214972 code snippet fix
  src/Microsoft.DocAsCode.Dfm/CodeRenderer/DfmFencesBlockPathQueryOptions/TagNameBlockPathQueryOption.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetExtractor.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2, v3

#5953 Remove host
  azure-pipelines-v3.yml
  docs/specs/markdown.yml
  docs/specs/xref.yml
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/Config.cs
  src/docfx/lib/UrlUtility.cs
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#5895 Replace HtmlUtility with HtmlReader
  src/docfx/build/page/BuildPage.cs
  src/docfx/docfx.csproj
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlToken.cs
  src/docfx/lib/html/HtmlWriter.cs
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5960 Setting a default `Manifest SourceBasePath` when a repo doesn't have …
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
Labels: v2

#5961 fix searching methods by name
  src/docfx.website.themes/default/styles/search-worker.js
Labels: v2

#5962 docfx output is now readable in white background
  src/Microsoft.DocAsCode.Common/ConsoleUtility.cs
  src/Microsoft.DocAsCode.Common/Loggers/ConsoleLogListener.cs
Labels: v2

#5963 Directory.GetFiles -> System.IO.Enumeration
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Input.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/path/PathString.cs
Labels: v3

#5965 Limit info message count
  src/docfx/config/Config.cs
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#5966 Remove unused expansive read file code when building xrefmap
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#5969 Cache git urls to speed up AddFileLink
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#5968 Turn HtmlCodeSnippetRenderer laungage extractors static
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetExtractor.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
Labels: v2, v3

#5972 Run regression test success
  src/docfx/docfx.csproj
  src/docfx/properties/AssemblyInfo.cs
  test/docfx.RegressionTest/RegressionTest.cs
  test/docfx.RegressionTest/docfx.RegressionTest.csproj
Labels: v3

#5973 Optimize link resolver file exists check
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/lib/path/PathString.cs
Labels: v3

#5977 Manage cache&state inside testdata
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5976 Fix GlobFiles crash
  src/docfx/build/context/BuildScope.cs
Labels: v3

#5974 Clear href for invalid external links
  docs/specs/resolve.yml
  src/docfx/build/link/LinkResolver.cs
  src/docfx/lib/UrlUtility.cs
Labels: v3

#5983 Log GetCommitHistory search steps
  src/docfx/lib/git/FileCommitProvider.cs
Labels: v3

#5984 Retire IntegrationTest with RegressionTest
  azure-pipelines-v3.yml
  test/docfx.RegressionTest/Options.cs
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5985 Fix RegressionTest adding cwd when calling exec
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5986 Fix RegressionTest push branch
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5987 Fix WriteStartTag emitting /0 string
  docs/specs/markdown.yml
  src/docfx/lib/html/HtmlWriter.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
Labels: v3

#5989 Enable regression-test commit cache
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5990 Fix regression-test cache path
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#5991 🚢🚢
  azure-pipelines-v3.yml
  docs/specs/markdown.yml
  src/docfx/lib/html/HtmlWriter.cs
  test/docfx.RegressionTest/Options.cs
  test/docfx.RegressionTest/RegressionTest.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
Labels: v3
