Repository dotnet/docfx, pull requests merged in 2020-03, with the labels that each got.

#5578 179017 snippet validation
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2

#5582 Enable nullable checks for TOC
  src/docfx/Errors.cs
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsMapBuilder.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/lib/UrlUtility.cs
Labels: v3

#5586 Enable nullable for loc, build and input
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/path/PackagePath.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/ConfigTest.cs
Labels: v3

#5589 Enable nullable checks for legacy
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyDependencyMapItem.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyItemToPublish.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/legacy/manifest/LegacyManifestItem.cs
  src/docfx/build/legacy/manifest/LegacyManifestOutput.cs
  src/docfx/build/legacy/manifest/LegacyManifestOutputItem.cs
Labels: v3

#5588 Enable nullable checks for publish
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/lib/moniker/MonikerUtility.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModel.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5587 also publish packages to azdevops
  azure-pipelines-master.yml
  azure-pipelines-stable.yml
  tools/Deployment/config_gulp.json
  tools/Deployment/gulpfile.js
Labels: v2

#5592 Enable nullable checks for remaining files
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/Contributor.cs
  src/docfx/config/ops/OpsMetadataRule.cs
  src/docfx/config/ops/OpsMetadataRuleConverter.cs
  src/docfx/lib/js/chakra/JavaScriptPropertyId.cs
  src/docfx/lib/js/chakra/JavaScriptRuntime.cs
  src/docfx/lib/js/chakra/JavaScriptSourceContext.cs
  src/docfx/lib/js/chakra/Native.cs
  src/docfx/lib/moniker/ExpressionCreator.cs
Labels: v3

#5594 use latest stable version of package Microsoft.DocAsCode.MarkdigEngine.Extensions
  docs/specs/markdown.yml
  src/docfx/docfx.csproj
Labels: v3

#5596 ensure contribution branch for included in build CRR
  docs/specs/git.yml
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5597 Categorize error codes
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMarkup.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/StringUtility.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/MergeConflict.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5593 Support fallback of xref map
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/XRefMaps/XRefCollection.cs
  src/Microsoft.DocAsCode.Build.Engine/XRefMaps/XRefMapDownloader.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/XRefMapDownloaderTest.cs
Labels: v2

#5591 Enable nullable reference type for xref and build page
  src/docfx/Errors.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/page/ConceptualModel.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/ExternalXrefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefMapModel.cs
  src/docfx/build/xref/XrefProperties.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/XrefExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/RazorTemplate.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5603 replace \r in razor render result to eliminate diff in integration-test
  src/docfx/template/RazorTemplate.cs
Labels: v3

#5604 Fix for progress updating all the time
  src/docfx/lib/log/Progress.cs
Labels: v3

#5601 Add retry logic for fetch method
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5607 add comment for canonical url
  docs/specs/metadata.yml
  src/docfx/build/document/DocumentProvider.cs
Labels: v3

#5613 Pick last updated github user if id is the same
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#5615 remove unneeded items in .vsconfig
  .vsconfig
Labels: v3

#5612 Print CRR dependency committish
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/restore/PackageResolver.cs
Labels: v3

#5616 Do not hardcode remote name, prefer origin
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/LibGit2.cs
Labels: v3

#5620 Remove docfx watch command
  docs/specs/watch.yml
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/watch/Watch.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3

#5621 Remove PublishModelBuilder.ExcludeFromOutput
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5622 support docset unique in json schema validation
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5618 Consolidate repository provider
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathString.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/lib/GitUtilityTest.cs
  test/docfx.Test/lib/PathUtilityTest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#5626 bug fix for duplicated unique keys in json schema
  src/docfx/lib/schema/JsonSchema.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5627 Update dotnet SDK to fix a null check bug
  azure-pipelines-v3.yml
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#5624 assign code DocumentError to DocumentException
  src/Microsoft.DocAsCode.Build.Common/MarkdownReader.cs
  src/Microsoft.DocAsCode.Build.Engine/HostService.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Preprocessors/TemplateUtility.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/TagInterpreters/PatternedTagInterpreter.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/ModelConverter/ModelConverter.cs
  src/Microsoft.DocAsCode.Common/Loggers/ErrorCodes.cs
  src/Microsoft.DocAsCode.Plugins/DocumentException.cs
  src/docfx/Program.cs
  src/docfx/SubCommands/DocumentBuilderWrapper.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
Labels: v2

#5628 187277 id not always working
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2, v3

#5623 Make build sync
  src/docfx/build/Build.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/cli/Docfx.cs
  src/docfx/docfx.csproj
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
  test/docfx.Test/lib/JsonDiskCacheTest.cs
  test/docfx.Test/lib/WorkQueueTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5632 Update .NET SDK for better null check
  azure-pipelines-v3.yml
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#5630 Fix JsonSchemaTransfomer traversal algorithm
  docs/specs/xref.yml
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaContentType.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5625 Calculate repository url based on remote tracking origin
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/LibGit2.cs
  test/docfx.Test/lib/GitUtilityTest.cs
Labels: v3

#5631 Prefer SourceInfo over FilePath for duplicated attribute reporting
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/lib/collections/ValueTupleEqualityComparer.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5633 Report duplicate-uid based on source info
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5638 Fix xref property cache not caching in all cases
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5639 Map document id from first to last
  docs/specs/config.yml
  src/docfx/build/document/DocumentProvider.cs
Labels: v3

#5640 DocumentException should not re-throw DocfxException.
  src/docfx/SubCommands/DocumentBuilderWrapper.cs
Labels: v2

#5642 Include log code in serialization info for DocumentException.
  src/Microsoft.DocAsCode.Plugins/DocumentException.cs
Labels: v2

#5646 release 2.51
  RELEASENOTE.md
Labels: v2

#5637 Update to latest FSharp.Compiler.Service
  NuGet.config
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpCompilation.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpProject.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/FSharpCompilationTests.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/FSharpProjectTests.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests.fsproj
  test/docfx.Tests/app.config
Labels: v2

#5645 fix for SDP with non-root uid, which is the only one
  docs/specs/xref.yml
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5651 Fix statictoc in Edge and IE
  src/docfx.website.themes/default/styles/docfx.js
Labels: v2

#5656 integrate with docs.validation extension
  NuGet.config
  docs/specs/validation.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#5647 Restore dependencies in parallel for implicity restore
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/TestQuirks.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/restore/FetchOptions.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3

#5643 add max/min length rule
  docs/specs/validation.yml
  src/docfx/config/ops/OpsMetadataRule.cs
  src/docfx/config/ops/OpsMetadataRuleConverter.cs
  test/docfx.Test/data/validation/rulesets.json
  test/docfx.Test/data/validation/schema.json
Labels: v3

#5658 Upgrade ValueTuple from 4.4 to 4.5 to be compatible with OPS plugin
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj
Labels: v2

#5663 Add robots metadata for customized 404 page
  docs/specs/markdown.yml
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/page/BuildPage.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5664 log allow list, metadata rules and converted json schema
  src/docfx/config/ops/OpsMetadataRuleConverter.cs
Labels: v3

#5661 Preprocess xref tag in mustache template
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/MustacheXrefTagParser.cs
  test/docfx.Test/data/mustache/partials/dotnet/xref-name.tmpl
  test/docfx.Test/data/mustache/xref-list.tmpl
  test/docfx.Test/data/mustache/xref-partial.tmpl
  test/docfx.Test/data/mustache/xref.tmpl
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5662 DocumentException in DocFX v2 should be user error.
  plugins/Microsoft.DocAsCode.Build.MemberLevelManagedReference/SplitClassPageToMemberLevel.cs
  src/Microsoft.DocAsCode.Build.Common/MarkdownReader.cs
  src/Microsoft.DocAsCode.Build.Common/Reference/ApplyOverwriteDocument.cs
  src/Microsoft.DocAsCode.Build.Common/Reference/OverwriteDocumentReader.cs
  src/Microsoft.DocAsCode.Build.Engine/HostService.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Preprocessors/TemplateUtility.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/ApplyOverwriteDocument.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/FileInterpreter.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/HrefInterpreter.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/SchemaDrivenDocumentProcessor.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/TagInterpreters/PatternedTagInterpreter.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/MarkdownTocReader.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/TocDocumentProcessorBase.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/TocHelper.cs
  src/Microsoft.DocAsCode.Build.TableOfContents/TocResolver.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/ModelConverter/ModelConverter.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/UniversalReferenceDocumentProcessor.cs
  src/Microsoft.DocAsCode.Common/Loggers/ErrorCodes.cs
  src/Microsoft.DocAsCode.Plugins/DocumentException.cs
  src/Microsoft.DocAsCode.Plugins/DocumentExceptionExtensions.cs
  src/docfx/Program.cs
  src/docfx/SubCommands/BuildCommand.cs
  src/docfx/SubCommands/DocumentBuilderWrapper.cs
  src/docfx/SubCommands/MergeCommand.cs
  src/docfx/SubCommands/MetadataCommand.cs
  src/docfx/SubCommands/PdfCommand.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
Labels: v2

#5665 🚢🚢
  NuGet.config
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/restore.yml
  docs/specs/template.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/TestQuirks.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsMetadataRule.cs
  src/docfx/config/ops/OpsMetadataRuleConverter.cs
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/restore/FetchOptions.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/MustacheXrefTagParser.cs
  src/docfx/validation/ContentValidator.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
  test/docfx.Test/data/mustache/partials/dotnet/xref-name.tmpl
  test/docfx.Test/data/mustache/xref-list.tmpl
  test/docfx.Test/data/mustache/xref-partial.tmpl
  test/docfx.Test/data/mustache/xref.tmpl
  test/docfx.Test/data/validation/rulesets.json
  test/docfx.Test/data/validation/schema.json
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5667 TOC respect global and file metadata
  docs/specs/metadata.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMarkup.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
Labels: v3

#5657 Downgrade output-path-conflict to warning
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/legacy.yml
  docs/specs/moniker.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/publish/PublishItemComparer.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5673 Remove \r in mustache partial
  src/docfx/template/MustacheTemplate.cs
Labels: v3

#5675 Move op spec tests to ops.yml
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/metadata.yml
  docs/specs/ops.yml
  docs/specs/redirection.yml
Labels: v3

#5672 Add FileFormat
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/lib/path/FileFormat.cs
  src/docfx/lib/path/FilePath.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5636 Fix #5635
  docs/specs/casing.yml
  docs/specs/git.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/RepositoryProvider.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/restore/PackageResolver.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5677 Remove \r in ResolveContent
  src/docfx/build/link/LinkResolver.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5668 Xref name property
  docs/specs/template.yml
  src/docfx/build/xref/ExternalXrefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/template/MustacheXrefTagParser.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5678 🐛 skip docset unique check for null and empty values
  docs/specs/validation.yml
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#5681 fix for lock not working
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5682 Refactor TOC test to not depend on build internals
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5684 remove incorrect h1 line number
  docs/specs/validation.yml
  src/docfx/validation/ContentValidator.cs
Labels: v3

#5691 support v3 only validation rules in apex validation
  docs/specs/validation.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/validation/ContentValidationContext.cs
Labels: v3

#5688 Add BuildFileType metric telemetry
  src/docfx/build/Build.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/log/TelemetryName.cs
Labels: v3

#5689 Sdp xref href relative resolve
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/build/xref/ExternalXrefSpec.cs
  src/docfx/build/xref/IXrefSpec.cs
  src/docfx/build/xref/InternalXrefSpec.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5692 Fix incorrect source info for duplicate value
  docs/specs/validation.yml
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5687 Relocate error file path, git urls based on source map
  docs/specs/output.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/Config.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/SourceMap.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/restore/FileResolver.cs
Labels: v3

#5698 Sort document id config by path descending
  docs/specs/config.yml
  src/docfx/build/document/DocumentProvider.cs
Labels: v3

#5697 Handle telemetry client crash when metric dimension is empty
  src/docfx/lib/log/Telemetry.cs
Labels: v3

#5685 warning when enum dependency missed
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#5686 Allow "Monikers" for user metadata
  docs/specs/moniker.yml
  src/docfx/Errors.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#5699 make moniker config nullable
  docs/specs/moniker.yml
  src/docfx/Errors.cs
  src/docfx/build/legacy/LegacyDependencyMapItem.cs
  src/docfx/build/legacy/LegacyFileMapItem.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/build/toc/TableOfContentsMetadata.cs
  src/docfx/config/Config.cs
  src/docfx/config/GroupConfig.cs
  src/docfx/lib/json/YamlUtility.Shared.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MonikerZoneExtension.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/publish/PublishItem.cs
Labels: v3

#5700 Update nuget packages
  build.ps1
  src/Directory.Build.props
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/docfx.csproj
  src/docfx/validation/ContentValidator.cs
  test/Directory.Build.props
  test/docfx.Test/docfx.Test.csproj
  test/docfx.Test/lib/GlobUtilityTest.cs
Labels: v3

#5701 use the stable version of apex validation adapter
  src/docfx/docfx.csproj
Labels: v3

#5703 Make TocLoader return TocNode
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMarkup.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/build/toc/TableOfContentsNode.cs
Labels: v3

#5705 Build rename history in parallel
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3
