Repository dotnet/docfx, pull requests merged in 2020-02, with the labels that each got.

#5511 update nuget package
  src/docfx/docfx.csproj
Labels: v3

#5512 Loc minor clean-up
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
Labels: v3

#5513 Log the last 5 characters instead of the first 5
  src/docfx/lib/process/ProcessUtility.cs
Labels: v3

#5510 171009 code extention bug
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
Labels: v2, v3

#5518 Remove GitShallowFetch
  src/docfx/config/Config.cs
  src/docfx/restore/PackageResolver.cs
Labels: v3

#5517 Gracefully handle global cache data corruption
  docs/specs/git.yml
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/git/GitCommitCache.cs
  src/docfx/lib/process/ProcessUtility.cs
Labels: v3

#5519 Lowercase locale
  docs/specs/config.yml
  docs/specs/localization.yml
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/Config.cs
  src/docfx/config/LocalizationConfig.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5516 Enable more nullable reference types
  src/docfx/Errors.cs
  src/docfx/lib/cache/ICacheObject{TKey}.cs
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/collections/CollectionUtility.cs
  src/docfx/lib/collections/ConcurrentHashSet.cs
  src/docfx/lib/collections/DictionaryBuilder.cs
  src/docfx/lib/collections/ListBuilder.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/git/CommitBuildTime.cs
  src/docfx/lib/git/CommitBuildTimeItem.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/github/GitHubQueries.cs
  src/docfx/lib/github/GitHubUser.cs
  src/docfx/lib/json/ShortHandConverter.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/msgraph/MicrosoftGraphAuthenticationProvider.cs
  src/docfx/lib/msgraph/MicrosoftGraphUser.cs
  src/docfx/lib/process/InterProcessMutex.cs
  src/docfx/lib/schema/EnumDependenciesSchema.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaConverter.cs
  src/docfx/lib/schema/JsonSchemaDefinition.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/lib/schema/MicrosoftAliasSchema.cs
  src/docfx/lib/schema/ReferenceEqualsComparer.cs
Labels: v3

#5521 fix github auth
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#5522 Add a vsts loc test case
  azure-pipelines-v3.yml
Labels: v3

#5523 Add build history for CRR
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
Labels: v3

#5526 TOC.md title supports trailing spaces
  docs/specs/toc.yml
Labels: v3

#5525 Bump validation package version to 1.2.19
  src/docfx/docfx.csproj
Labels: v3

#5528 Load OPS config from repository root folder
  docs/specs/config.yml
  docs/specs/metadata.yml
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsConfigLoader.cs
Labels: v3

#5529 Load OPS redirection config from repository root folder
  docs/specs/redirection.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/redirection/RedirectionItem.cs
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5532 update integration-test repo branch
  azure-pipelines-v3.yml
Labels: v3

#5520 Enable nullable checks for moniker parser, js engine, json, yaml and restore
  src/docfx/Errors.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/js/ChakraCoreJsEngine.cs
  src/docfx/lib/js/IJavaScriptEngine.cs
  src/docfx/lib/js/JintJsEngine.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/YamlUtility.Shared.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/log/CustomError.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/moniker/ComparatorExpression.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/ExpressionCreator.cs
  src/docfx/lib/moniker/IExpression.cs
  src/docfx/lib/moniker/LogicExpression.cs
  src/docfx/lib/moniker/Moniker.cs
  src/docfx/lib/moniker/MonikerComparer.cs
  src/docfx/lib/moniker/MonikerDefinitionModel.cs
  src/docfx/lib/moniker/MonikerRangeException.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  src/docfx/lib/moniker/MonikerUtility.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5531 Handle the case that relative path outside docset folder
  docs/specs/markdown.yml
  src/docfx/build/dependency/LinkResolver.cs
Labels: v3

#5533 Enable nullable checks for config
  src/docfx/build/context/BuildScope.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/DependencyConfig.cs
  src/docfx/config/DocsetsConfig.cs
  src/docfx/config/DocumentIdConfig.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/config/FileMappingConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/config/GroupConfig.cs
  src/docfx/config/HttpConfig.cs
  src/docfx/config/MicrosoftGraphConfig.cs
  src/docfx/config/OutputConfig.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/config/ops/OpsDependencyConfig.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
Labels: v3

#5535 Filter expired cache item when saving
  src/docfx/lib/cache/JsonDiskCache.cs
Labels: v3

#5538 Replace \r in mustache
  src/docfx/template/MustacheTemplate.cs
Labels: v3

#5540 Change the order of static environment initialize
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5541 🚢🚢
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5544 Abort upon load source model error
  docs/specs/schema.yml
  src/docfx/build/page/BuildPage.cs
Labels: v3

#5537 decode specical chars `(` and `)` after Uri.EscapeDataString()
  src/Microsoft.DocAsCode.Common/Path/RelativePath.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.WithPlugins.Tests/SplitClassPageToMemberLevelTest.cs
Labels: v2

#5524 Avoid non-deterministic output
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/ExtractSearchIndex.cs
  src/Microsoft.DocAsCode.Plugins/IncrementalInfo.cs
Labels: v2

#5534 Enable nullable checks for markdown, TOC markdown, git
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/toc/TableOfContentsItem.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsMarkup.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/git/GitCommit.cs
  src/docfx/lib/git/GitCommitCache.cs
  src/docfx/lib/git/GitCommitProvider.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/git/LibGit2.cs
  src/docfx/lib/git/MergeConflict.cs
  src/docfx/lib/git/Repository.cs
  src/docfx/lib/markdown/ExtractYamlHeader.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MonikerZoneExtension.cs
  src/docfx/lib/markdown/XrefExtension.cs
  src/docfx/lib/markdown/validation/ContentValidationContext.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/lib/markdown/validation/ContentValidationLogger.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
Labels: v3

#5543 monikerParser should be case-insensitive
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#5548 fix for xref tag not found
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5549 Always add publish-item in buildPage
  docs/specs/schema.yml
  src/docfx/build/page/BuildPage.cs
Labels: v3

#5555 disable codesign injection
  azure-pipelines-v3.yml
Labels: v3

#5551 sort properties recursively
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/json/JsonUtility.cs
Labels: v3

#5556 Fields should be private
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/GlobalMetadata.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/Config.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/DocsetsConfig.cs
  src/docfx/config/DocumentIdConfig.cs
  src/docfx/config/FileMappingConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/config/GroupConfig.cs
  src/docfx/config/HttpConfig.cs
  src/docfx/config/MicrosoftGraphConfig.cs
  src/docfx/config/OutputConfig.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/TestQuirks.cs
  src/docfx/config/ops/OpsConfig.cs
  src/docfx/config/ops/OpsDependencyConfig.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/log/CustomError.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/stylecop.ruleset
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#5558 [Breaking] integration test using artifact
  azure-pipelines-v3.yml
Labels: v3

#5559 keep using StringComparer.Ordinal for moniker sorting
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#5550 [Breaking] Flatten config entries
  docs/specs/casing.yml
  docs/specs/config.yml
  docs/specs/git.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/metadata.yml
  docs/specs/moniker.yml
  docs/specs/output.yml
  docs/specs/schema.yml
  docs/specs/template.yml
  docs/specs/validation.yml
  src/docfx/build/Build.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ContributionConfig.cs
  src/docfx/config/GitHubConfig.cs
  src/docfx/config/MicrosoftGraphConfig.cs
  src/docfx/config/OutputConfig.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/lib/StringUtility.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/build/TocTest.cs
  test/docfx.Test/lib/GitHubAccessorTest.cs
Labels: v3

#5560 fix: Ensure a single key has only one entry in JsonDiskCache
  src/docfx/lib/cache/JsonDiskCache.cs
  src/docfx/lib/github/GitHubAccessor.cs
Labels: v3

#5546 177269 code ext fixes
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/CodeTest.cs
Labels: v2

#5568 Update integration-test branch
  azure-pipelines-v3.yml
Labels: v3

#5566 Improve base path handling
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/path/BasePath.cs
  src/docfx/publish/PublishModelBuilder.cs
Labels: v3

#5561 Safe guard against not existing definition when inheriting doc
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/CopyInheritedDocumentation.cs
Labels: v2

#5571 fix: perf url fix in OpsConfigAdapter
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5570 Support xrefmap fallback for localization
  docs/specs/xref.yml
  src/docfx/build/context/Context.cs
  src/docfx/restore/FileResolver.cs
Labels: v3

#5390 Update config doc
  docs/designs/config.md
Labels: v3

#5567 Update jQuery and fix removed API.
  src/docfx.website.themes/default/bower.json
  src/docfx.website.themes/default/styles/docfx.js
Labels: v2

#5574 Gracefully handle git crash
  src/docfx/restore/PackageResolver.cs
Labels: v3

#5563 162897 borders and lightboxes
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2

#5575 Enable nullable checks for template and other simple classes
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/page/BookmarkValidator.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/RazorTemplate.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/TemplateModel.cs
  src/docfx/template/TemplateSchema.cs
  src/docfx/template/liquid/JavaScriptTag.cs
  src/docfx/template/liquid/LiquidFilter.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  src/docfx/template/liquid/LocalizeTag.cs
  src/docfx/template/liquid/StyleTag.cs
  src/docfx/watch/Watch.cs
Labels: v3

#5573 Enable nullable checks for metadata
  docs/specs/git.yml
  docs/specs/legacy.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/GlobalMetadata.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/page/ContributionInfo.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/collections/CollectionUtility.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  test/docfx.Test/lib/YamlUtilityTest.cs
Labels: v3

#5581 Update test to cover author multiple occurence in contributors
  docs/specs/git.yml
Labels: v3

#5579 release 2.50
  RELEASENOTE.md
Labels: v2
