Repository dotnet/docfx, pull requests merged in 2020-04, with the labels that each got.

#5702 skip log InvalidInputFile error if from DocumentException
  src/Microsoft.DocAsCode.Build.Engine/HostServiceCreator.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Models/DocumentSchema.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Validators/SchemaValidateService.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Validators/SchemaValidator.cs
  src/Microsoft.DocAsCode.Common/Loggers/ErrorCodes.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
Labels: v2

#5706 Use standalone appdata path for each test case
  docs/specs/casing.yml
  src/docfx/config/AppData.cs
  src/docfx/config/TestQuirks.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5707 Move TOC deserialization to TOC parser
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsParser.cs
Labels: v3

#5696 refactor: Docset/LocProvider -> BuildOptions
  src/docfx/build/Build.cs
  src/docfx/build/BuildOptions.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/Document.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/config/Config.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/lib/LocalizationUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageFetchOptions.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/lib/ErrorLogTest.cs
Labels: v3

#5710 [Breaking] Support overwrite buildtime through config
  docs/specs/legacy.yml
  src/docfx/config/Config.cs
  src/docfx/lib/git/CommitBuildTimeProvider.cs
Labels: v3

#5709 Handle TOC build scope in TocMap
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#5711 improvement: refine error message on custom 404 page
  docs/specs/markdown.yml
  src/docfx/Errors.cs
Labels: v3

#5713 Report source info when missing name in toc.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsNode.cs
  src/docfx/build/toc/TableOfContentsParser.cs
Labels: v3

#5712 Skip moniker range config validation for reference
  docs/specs/moniker.yml
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
Labels: v3

#5716 add azure-docs-rest-apis integration-test
  azure-pipelines-v3.yml
Labels: v3

#5715 Merge TocMap and TocMapBuilder and make it constructor injectable
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsMapBuilder.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5717 Run js once, force content property
  docs/specs/template.yml
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5718 Ignore __global property for output, it is HUGE
  src/docfx/lib/js/ChakraCoreJsEngine.cs
  src/docfx/lib/js/JintJsEngine.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/lib/JavascriptEngineTest.cs
Labels: v3

#5721 Enable telemetry in integration test
  azure-pipelines-v3.yml
Labels: v3

#5722 enable nuget debug for docs-validation package
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5719 Add metric telemetry 'MarkdownElement'
  src/docfx/lib/StringUtility.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/markdown/MarkdownElementTelemetryExtension.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/lib/MarkdownElementTelemetryExtensionTest.cs
  test/docfx.Test/lib/StringUtilityTest.cs
Labels: v3

#5720 Parallel invoke pre and post build actions
  src/docfx/build/Build.cs
  src/docfx/build/metadata/MetadataProvider.cs
Labels: v3

#5725 Refine missing-toc-name error message
  docs/specs/toc.yml
  src/docfx/Errors.cs
Labels: v3

#5730 Mustache array empty
  src/docfx/template/MustacheTemplate.cs
  test/docfx.Test/data/mustache/list.tmpl
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#5735 remove appending locale to theme
  docs/specs/template.yml
  src/docfx/lib/LocalizationUtility.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5704 Moniker validation
  docs/specs/moniker.yml
  src/docfx/Errors.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/StringUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/moniker/ComparatorExpression.cs
  src/docfx/lib/moniker/EvaluatorWithMonikersVisitor.cs
  src/docfx/lib/moniker/ExpressionCreator.cs
  src/docfx/lib/moniker/IExpression.cs
  src/docfx/lib/moniker/LogicExpression.cs
  src/docfx/lib/moniker/MonikerRangeException.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#5737 simplify MonikerRangeParser
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/moniker/MonikerComparer.cs
  src/docfx/lib/moniker/MonikerRangeParser.cs
  test/docfx.Test/lib/MonikerRangeParserTest.cs
Labels: v3

#5738 Transform <xref> tag in mustache partial
  docs/specs/template.yml
  src/docfx/template/MustacheTemplate.cs
Labels: v3

#5727 Add publish url validator
  docs/specs/validation.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#5728 Remove content output from LinkResolver.ResolveContent
  src/docfx/build/context/Context.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/toc/TableOfContentsParser.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5736 Add TOC splitItemsBy design
  docs/designs/toc-split-items-by.md
Labels: v3

#5740 Refactor TOC link type
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsLinkType.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/lib/log/SourceInfo{T}.cs
Labels: v3

#5747 Move exception handling to ParallelUtility
  src/docfx/build/Build.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/lib/collections/WorkQueue.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/lib/WorkQueueTest.cs
Labels: v3

#5750 GetHeadCommit --> GetRepoInfo
  azure-pipelines-v3.yml
  src/docfx/lib/LocalizationUtility.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/PackageResolver.cs
Labels: v3

#5733 196190 change image error
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
Labels: v2

#5693 Improve readability of default theme
  src/docfx.website.themes/default/styles/docfx.css
Labels: v2

#5751 Remove tocHref and topicHref from output
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsLoader.cs
Labels: v3

#5729 Implement TOC splitItemsBy
  docs/specs/localization.yml
  docs/specs/redirection.yml
  docs/specs/toc.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/toc/TableOfContentsNode.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/path/FileOrigin.cs
  src/docfx/lib/path/FilePath.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5753 Support uid attribute in <xref>
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/XrefExtension.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5752 WorkQueue to run items on enqueue
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/lib/collections/WorkQueue.cs
  test/docfx.Test/lib/WorkQueueTest.cs
Labels: v3

#5755 release 2.52
  RELEASENOTE.md
Labels: v2

#5763 Parent TOC not participating in _tocRel resolve
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsLoader.cs
Labels: v3

#5754 Add publish url segment unique validation
  docs/specs/validation.yml
  src/docfx/docfx.csproj
Labels: v3

#5746 Fixes PDF outline issue #5490
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
Labels: v2

#5762 Development experience improvement: Fallback to use opBuildUserToken in keyVault if no secret set
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/docfx.csproj
Labels: v3

#5770 add source_file_url and source_line to spec
  docs/designs/link-output.md
Labels: v3

#5769 Leave user-undefined xref property null
  docs/specs/template.yml
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5766 Output document_id for redirection file for BI usage
  docs/specs/ops.yml
  docs/specs/redirection.yml
  src/docfx/build/redirection/BuildRedirection.cs
Labels: v3

#5776 Consume "alt" in Uid
  docs/specs/xref.yml
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#5779 Export href for uid declaration
  docs/specs/template.yml
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5780 Update Validations.DocFx.Adapter version
  src/docfx/docfx.csproj
Labels: v3

#5777 apply xref-property-conflict for all xref properties
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
Labels: v3

#5787 ship to prod 🚄🚄🚄🚄
  NuGet.config
  docs/designs/link-output.md
  docs/specs/ops.yml
  docs/specs/redirection.yml
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/docfx.csproj
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5783 Fix perf regression caused by tracking markdown element telemetry
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/markdown/MarkdownTelemetryExtension.cs
  test/docfx.Test/lib/MarkdownElementTelemetryExtensionTest.cs
Labels: v3

#5788 SDP unresolved xref default as object
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/MustacheXrefTagParser.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5789 Add source file info for broken links
  docs/specs/git.yml
  docs/specs/output.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/path/PathString.cs
  test/docfx.Test/lib/PathUtilityTest.cs
Labels: v3

#5781 Return type.uid if other types don't contain required property
  src/docfx.website.themes/common/UniversalReference.common.js
Labels: v2

#5793 remove the dependency of MetadataProvider on DocumentProvider
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
Labels: v3

#5794 support xrefService as build parameter
  src/docfx/Models/BuildCommandOptions.cs
  src/docfx/SubCommands/BuildCommand.cs
Labels: v2

#5792 198685 lightbox bug
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
Labels: v2

#5772 Add a forward-only HtmlReader
  docs/specs/resolve.yml
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlTokenType.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  test/docfx.Test/lib/HtmlReaderTest.cs
Labels: v3

#5797 Split git commit URL from content url
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
Labels: v3

#5795 set mimeType of conceptual to 'Conceptual'
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#5799 Take the latter value when there are duplicate key in liquid object
  docs/specs/template.yml
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/template/LiquidTemplateTest.cs
Labels: v3

#5801 🛳🛳
  docs/specs/git.yml
  docs/specs/output.yml
  docs/specs/resolve.yml
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/link/FileLinkItem.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlTokenType.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/MarkdownTelemetryExtension.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/MustacheXrefTagParser.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  src/docfx/validation/ContentValidator.cs
  test/docfx.Test/lib/HtmlReaderTest.cs
  test/docfx.Test/lib/MarkdownElementTelemetryExtensionTest.cs
  test/docfx.Test/lib/PathUtilityTest.cs
  test/docfx.Test/template/LiquidTemplateTest.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
  test/docfx.Test/template/MustacheXrefTagParserTest.cs
Labels: v3

#5744 Clean up dependency map
  docs/specs/casing.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/output.yml
  docs/specs/restore.yml
  docs/specs/schema.yml
  docs/specs/toc.yml
  docs/specs/xref.yml
  src/docfx/build/dependency/DependencyMapBuilder.cs
  src/docfx/build/dependency/DependencyType.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyDependencyMap.cs
  src/docfx/build/legacy/LegacyDependencyMapItem.cs
  src/docfx/build/legacy/LegacyDependencyMapType.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5803 add environment variable DOCFX_KEEP_DEBUG_INFO
  src/Microsoft.DocAsCode.Build.Engine/PostProcessors/HtmlPostProcessor.cs
Labels: v2

#5805 Report warning on toc folder-inclusion not found
  docs/specs/legacy.yml
  docs/specs/toc.yml
  src/docfx/Errors.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/restore/FileResolver.cs
Labels: v3

#5814 Warning upon href defined side-by-side with uid
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5810 F#: Cache project infos
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpProject.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/FSharpCompilationTests.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/FSharpProjectTests.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests.fsproj
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/TestData/NetCoreLibProjectCopy/Library.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/TestData/NetCoreLibProjectCopy/NetCoreLibProjectCopy.fsproj
Labels: v2

#5798 Refactor markdown context to pass GetLink delegate
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/ResolveLink/ResolveLinkExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ChromelessFormExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/TripleColonParser.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ZoneExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigEngine/ResolveLink/ResolveLinkExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2, v3

#5784 Integrate Ecma2Yaml
  docs/specs/ecma2Yaml.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsConfig.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/config/ops/OpsDocsetConfig.cs
  src/docfx/config/ops/OpsPreProcessor.cs
  src/docfx/docfx.csproj
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
  test/docfx.Test/TestUtility.cs
Labels: v3

#5817 Reuse 'attribute-reserved' for uid overwrite href case
  docs/specs/legacy.yml
  docs/specs/metadata.yml
  docs/specs/redirection.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5818 Generate metadata dependency for PR comment preview link
  docs/specs/toc.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/DependencyType.cs
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#5811 F#: Fix crash when overriding methods on System.Object
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpCompilation.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/FSharpProjectTests.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/TestData/NetCoreProject/InterfaceImpls.fs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests/TestData/NetCoreProject/NetCoreProject.fsproj
Labels: v2

#5806 Support static output
  docs/specs/markdown.yml
  docs/specs/schema.yml
  docs/specs/static.yml
  docs/specs/template.yml
  docs/specs/xref.yml
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/legacy/manifest/LegacyManifestItem.cs
  src/docfx/build/legacy/manifest/LegacyManifestOutput.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/toc/TableOfContentsModel.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/config/Config.cs
  src/docfx/config/OutputType.cs
  src/docfx/config/OutputUrlType.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/ModuleInitializer.cs
Labels: v3

#5822 Relative plugin config path to docset root
  docs/specs/ecma2Yaml.yml
  src/docfx/config/ops/OpsConfigLoader.cs
Labels: v3

#5821 integrate .sourcemap.json
  docs/specs/ecma2Yaml.yml
  docs/specs/output.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/ops/OpsConfigLoader.cs
  src/docfx/docfx.csproj
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/SourceMap.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/lib/ErrorLogTest.cs
Labels: v3

#5824 Upgrade ecma-2-yaml varsion
  src/docfx/docfx.csproj
  src/docfx/lib/collections/WorkQueue.cs
Labels: v3

#5804 196807 icon border
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2

#5827 Treat ".yml" as ".md" while calculating document id
  docs/specs/redirection.yml
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/template/TemplateEngine.cs
Labels: v3

#5826 Always use Docs URL to check redirection rule with document_id as true
  docs/specs/static.yml
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5828 update nuget package
  docs/specs/ecma2Yaml.yml
  src/docfx/docfx.csproj
Labels: v3

#5830 Make default value of CopyResource as true and remove TODO
  src/docfx/config/Config.cs
Labels: v3

#5809 Add HtmlWriter, extract HtmlExtension
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlAttributeType.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlToken.cs
  src/docfx/lib/html/HtmlWriter.cs
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/XrefExtension.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
  test/docfx.Test/lib/HtmlUtilityTest.cs
Labels: v3

#5820 Report a warning if the liquid is not found when generating html output
  docs/specs/markdown.yml
  docs/specs/static.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  test/docfx.Test/template/LiquidTemplateTest.cs
Labels: v3

#5835 Add and track Error.Name
  src/docfx/Errors.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#5834 Virtual node name match glob pattern
  docs/specs/toc.yml
  src/docfx/build/context/Input.cs
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#5836 sort metadata monikers for reference
  docs/specs/moniker.yml
  src/docfx/lib/moniker/MonikerRangeParser.cs
Labels: v3

#5823 Validate html by allowlist
  docs/specs/markdown.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
Labels: v3

#5839 Split toc wrap into items
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#5840 Remove HtmlReader.Back()
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlToken.cs
Labels: v3

#5841 Add HTML source text range info to HtmlReader
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/xref.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/html/HtmlAttribute.cs
  src/docfx/lib/html/HtmlReader.cs
  src/docfx/lib/html/HtmlTextPosition.cs
  src/docfx/lib/html/HtmlTextRange.cs
  src/docfx/lib/html/HtmlToken.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  test/docfx.Test/lib/HtmlReaderWriterTest.cs
Labels: v3

#5843 fix url of index page in ugly outputUrlType
  docs/specs/static.yml
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/toc/BuildTableOfContents.cs
Labels: v3

#5832 Enabled ESRPCodeSign for docfx v2 - dev
  azure-pipelines-stable.yml
  build.ps1
  codesign_policy.json
  common.ps1
  pack.ps1
  tools/Deployment/gulpfile.js
Labels: v2

#5831 traverse all headings from AST and integrate with validation headings interfaces
  docs/specs/validation.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#5845 Reduce toc child node monikers
  docs/specs/moniker.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#5847 fix generated toc path route
  docs/specs/toc.yml
  src/docfx/build/toc/TableOfContentsMap.cs
Labels: v3

#5812 Updated Validations.DocFx.Adapter to 1.2.24-beta006
  src/docfx/docfx.csproj
Labels: v3

#5848 support validate setex headings
  docs/specs/validation.yml
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3

#5849 Pick new github loc test repo
  azure-pipelines-v3.yml
Labels: v3

#5846 Enabled ESRPCodeSign for docfx v2 - master
  azure-pipelines-master.yml
  tools/Deployment/gulpfile.js
Labels: v2

#5842 Only validate user HTML
  docs/specs/markdown.yml
  docs/specs/resolve.yml
  docs/specs/validation.yml
  src/docfx/Errors.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/HtmlExtension.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
Labels: v3

#5853 Add --no-cache option to build
  src/docfx/build/Build.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5852 mustache treat "false" as true
  src/docfx/template/MustacheTemplate.cs
  test/docfx.Test/template/MustacheTemplateTest.cs
Labels: v3

#5850 expand headings in inclusions
  docs/specs/validation.yml
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/markdown/validation/ContentValidationExtension.cs
Labels: v3
