Repository dotnet/docfx, pull requests merged in 2020-01, with the labels that each got.

#5405 Simplify git restore with PackageResolver
  docs/specs/git.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/DependencyConfig.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/restore/PackageFetchOptions.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitFlags.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/RestoreGitResult.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
Labels: v3

#5420 🚢🚢🚢
  README.md
  docs/specs/git.yml
  docs/specs/output.yml
  docs/specs/restore.yml
  src/docfx/build/Build.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/AppData.cs
  src/docfx/config/Config.cs
  src/docfx/config/DependencyConfig.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/markdown/LinkExtension.cs
  src/docfx/restore/PackageFetchOptions.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/restore/RestoreGit.cs
  src/docfx/restore/RestoreGitFlags.cs
  src/docfx/restore/RestoreGitMap.cs
  src/docfx/restore/RestoreGitResult.cs
  src/docfx/restore/lock/DependencyGitLock.cs
  src/docfx/restore/lock/DependencyLockProvider.cs
Labels: v3

#5415 Add --dry-run option to build that does not produce artifacts
  docs/specs/git.yml
  docs/specs/legacy.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/Config.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3

#5419 Fix file extension in docs
  Documentation/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.md
Labels: v2

#5422 perf: replace ls-tree with directory search
  src/docfx/build/context/Input.cs
  src/docfx/lib/git/GitUtility.cs
Labels: v3

#5424 fix: Use a random test output path
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5421 perf: Optimize GetMetadata and GetMonikerRange
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
Labels: v3

#5417 refactor: Remove absolute link resolve for token cache
  src/docfx/build/dependency/LinkResolver.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5414 [breaking]upgrade to dotnet core 3.1
  azure-pipelines-v3.yml
  src/Directory.Build.props
  src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj
  src/docfx/docfx.csproj
  src/docfx/template/RazorTemplate.cs
  test/docfx.Test/docfx.Test.csproj
Labels: v3

#5427 Upgrade Csharp version
  src/Directory.Build.props
  src/docfx/build/Build.cs
  src/docfx/build/context/Input.cs
  src/docfx/build/context/Output.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/toc/MarkdownTocMarkup.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/lib/git/GitCommitCache.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/json/YamlUtility.cs
  src/docfx/lib/markdown/MarkdownEngine.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/RazorTemplate.cs
  test/Directory.Build.props
  test/docfx.Test/TestUtility.cs
  test/docfx.Test/lib/ErrorLogTest.cs
  test/docfx.Test/lib/ExtractYamlHeaderTest.cs
  test/docfx.Test/lib/GitUtilityTest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#5426 Handle AggregatedException
  docs/specs/git.yml
  docs/specs/validation.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/git/FileCommitProvider.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/restore/Restore.cs
Labels: v3

#5428 [Breaking] Run integration test in parallel
  azure-pipelines-v3.yml
Labels: v3

#5430 perf: Skip post markup in dry run
  src/docfx/build/page/BuildPage.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#5436 remove redundant net462 checks
  src/Microsoft.DocAsCode.Build.Common/Microsoft.DocAsCode.Build.Common.csproj
  src/Microsoft.DocAsCode.Build.Engine/Microsoft.DocAsCode.Build.Engine.csproj
  src/Microsoft.DocAsCode.Build.ManagedReference/Microsoft.DocAsCode.Build.ManagedReference.csproj
  src/Microsoft.DocAsCode.Build.TableOfContents/Microsoft.DocAsCode.Build.TableOfContents.csproj
  src/Microsoft.DocAsCode.Build.UniversalReference/Microsoft.DocAsCode.Build.UniversalReference.csproj
  src/Microsoft.DocAsCode.Common/Microsoft.DocAsCode.Common.csproj
  src/Microsoft.DocAsCode.DataContracts.Common/Microsoft.DocAsCode.DataContracts.Common.csproj
  src/Microsoft.DocAsCode.DataContracts.UniversalReference/Microsoft.DocAsCode.DataContracts.UniversalReference.csproj
  src/Microsoft.DocAsCode.Dfm/Microsoft.DocAsCode.Dfm.csproj
  src/Microsoft.DocAsCode.Glob/Microsoft.DocAsCode.Glob.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Microsoft.DocAsCode.Metadata.ManagedReference.Common.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Microsoft.DocAsCode.Metadata.ManagedReference.csproj
  src/Shared/base.props
  src/docfx/docfx.csproj
  test/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests.csproj
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/Microsoft.DocAsCode.Build.SchemaDriven.Tests.csproj
  test/Microsoft.DocAsCode.Build.TableOfContents.Tests/Microsoft.DocAsCode.Build.TableOfContents.Tests.csproj
  tools/MergeDeveloperComments/MergeDeveloperComments.csproj
  tools/MergeSourceInfo/MergeSourceInfo.csproj
Labels: v2

#5437 Remove build from en-us for LOC
  src/docfx/build/Build.cs
  src/docfx/build/document/RepositoryProvider.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5429 perf: Process redirections in parallel
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/TableOfContentsMap.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/restore/Restore.cs
  test/Directory.Build.props
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5439 [breaking]update Polly.Extensions.Http
  src/docfx/docfx.csproj
Labels: v3

#5433 feat: track telemetry on log
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/lib/log/Telemetry.cs
Labels: v3

#5449 fix: Merge validation and markdig extension to the same project
  docfx.sln
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Validation/IMarkdownObjectValidator.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Validation/IMarkdownObjectValidatorProvider.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Validation/MarkdownLambdaObjectValidator.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Validation/MarkdownObjectValidatorFactory.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/Microsoft.DocAsCode.MarkdigEngine.Validators.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
Labels: P0

#5459 Create azure-pipelines-stable.yml
  README.md
  azure-pipelines-stable.yml
Labels: v2

#5462 fix: skip flappy test
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
Labels: v2

#5434 fix xunit asserts
  test/Microsoft.DocAsCode.Build.Common.Tests/MarkdownReaderTest.cs
  test/Microsoft.DocAsCode.Build.Common.Tests/ModelAttributeHandlerTest.cs
  test/Microsoft.DocAsCode.Build.Common.Tests/ReflectionHelperTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/IncrementalBuildTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/PostProcessors/PostProcessorsHandlerTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/TemplatePageLoaderUnitTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/TemplatePreprocessorLoaderUnitTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/TemplateRendererLoaderUnitTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/ValidateBookmarkTest.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/ManagedReferenceDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.WithPlugins.Tests/SplitClassPageToMemberLevelTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.Tests/RestApiDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.Tests/SwaggerJsonParserTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.WithPlugins.Tests/SplitRestApiToOperationLevelTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.WithPlugins.Tests/SplitRestApiToTagLevelTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaMergerTest.cs
  test/Microsoft.DocAsCode.Build.TableOfContents.Tests/MarkdownTocReaderTest.cs
  test/Microsoft.DocAsCode.Build.TableOfContents.Tests/TocDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.UniversalReference.Tests/UniversalReferenceDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Common.Tests/CompositeDictionaryTest.cs
  test/Microsoft.DocAsCode.Glob.Tests/GlobFileTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Tests/InclusionTest.cs
  test/Microsoft.DocAsCode.MarkdownLite.Tests/SourceInfoTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/ApiFilterUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/ConvertToViewModelUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromVBUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/TripleSlashParserUnitTest.cs
  test/docfx.Tests/ArgsParserTest.cs
Labels: v2

#5464 fix: remove duplicate error when TOC is invalid
  src/Microsoft.DocAsCode.Build.TableOfContents/TocHelper.cs
Labels: v2

#5455 - Bump up Validations.Docfx.Adapter version to 1.2.17
  src/docfx/docfx.csproj
Labels: v3

#5465 update MarkdigEngine.Extensions
  src/docfx/docfx.csproj
Labels: v3

#5463 Cleanup LOC
  docs/designs/conceptual-localization.md
  docs/specs/localization.yml
  src/docfx/build/localization/LocalizationMapping.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/LocalizationConfig.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/build/ConfigTest.cs
Labels: v3

#5478 fix for invalid ending json
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5477 [Breaking]Add force restore option
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/restore/FetchOptions.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5479 Add version tag to build
  build.ps1
Labels: v3

#5480 Tag version in pipeline
  build.ps1
Labels: v3

#5481 [breaking]restore latest as default behavior
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/restore/FetchOptions.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageResolver.cs
  test/docfx.Test/DocfxTest.cs
Labels: v3

#5484 update pipeline yaml
  azure-pipelines-v3.yml
Labels: v3

#5485 Fix docs-help-pr integration-test url
  azure-pipelines-v3.yml
Labels: v3

#5488 Revert markdig validation API contract changes
  docfx.sln
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Rewriter/MarkdownObjectRewriterFactory.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Rewriter/MarkdownObjectValidatorAdapter.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/IMarkdownObjectValidator.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/IMarkdownObjectValidatorProvider.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/MarkdownLambdaObjectValidator.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/MarkdownObjectValidatorFactory.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/Microsoft.DocAsCode.MarkdigEngine.Validators.csproj
Labels: v2

#5487 Add CheckAdditionalContent option for de-serialization JSON Stream
  src/docfx/lib/json/JsonUtility.cs
  test/docfx.Test/lib/JsonUtilityTest.cs
Labels: v3

#5471 Fix Bug: Toc filter returns unrelated results #5401
  src/docfx.website.themes/default/styles/docfx.js
Labels: v2

#5438 Start the NRE hunt
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/Log.cs
  src/docfx/lib/log/PerfScope.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/path/BasePath.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/lib/path/PathUtility.cs
Labels: v3

#5486 fix: remove TrackValue value per dimension limit
  src/docfx/lib/log/Telemetry.cs
Labels: v3

#5493 fix: handle circular redirection
  docs/specs/redirection.yml
  src/docfx/build/redirection/RedirectionProvider.cs
Labels: v3

#5482 Remove shared *.schema.json in spec tests
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/markdown.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  test/docfx.Test/data/template/ContentTemplate/schemas/ContextObject.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestData.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestPage.schema.json
Labels: v3

#5491 Improve inheritdoc
  Documentation/spec/triple_slash_comments_spec.md
  RELEASENOTE.md
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Models/MetadataItem.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/FSharpCompilation.fs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VisitorHelper.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/MergeComments/MergeCommentsHelper.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/CopyInheritedDocumentation.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/TripleSlashParserUnitTest.cs
Labels: v2

#5497 🚢🚢
  azure-pipelines-v3.yml
  build.ps1
  docs/designs/conceptual-localization.md
  docs/specs/escape.yml
  docs/specs/legacy.yml
  docs/specs/localization.yml
  docs/specs/markdown.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  docs/specs/schema.yml
  docs/specs/xref.yml
  src/docfx/Errors.cs
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/localization/LocalizationMapping.cs
  src/docfx/build/localization/LocalizationUtility.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/LocalizationConfig.cs
  src/docfx/docfx.csproj
  src/docfx/lib/json/JsonUtility.cs
  src/docfx/lib/log/DocfxException.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ISourceInfo.cs
  src/docfx/lib/log/Log.cs
  src/docfx/lib/log/PerfScope.cs
  src/docfx/lib/log/Progress.cs
  src/docfx/lib/log/SourceInfo.cs
  src/docfx/lib/log/SourceInfo{T}.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/path/BasePath.cs
  src/docfx/lib/path/FilePath.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/lib/path/PathUtility.cs
  src/docfx/restore/FetchOptions.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/build/ConfigTest.cs
  test/docfx.Test/data/template/ContentTemplate/schemas/ContextObject.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestData.schema.json
  test/docfx.Test/data/template/ContentTemplate/schemas/TestPage.schema.json
  test/docfx.Test/lib/JsonUtilityTest.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5495 fix: Trim directory name in case file path contain whitespace
  docs/specs/markdown.yml
  src/docfx/build/document/DocumentProvider.cs
Labels: v3

#5498 Enable more nullable checks
  src/Directory.Build.props
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/HashUtility.cs
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/Levenshtein.cs
  src/docfx/lib/ParallelUtility.cs
  src/docfx/lib/ReflectionUtility.cs
  src/docfx/lib/StringUtility.cs
  src/docfx/lib/UrlUtility.cs
  src/docfx/lib/json/JTokenDeepEqualsComparer.cs
  src/docfx/lib/json/JTokenJsonConverter.cs
  src/docfx/lib/json/JsonContractResolver.cs
  src/docfx/lib/json/OneOrManyConverter.cs
  src/docfx/lib/json/ShortHandConverter.cs
  src/docfx/lib/json/SourceInfoJsonConverter.cs
  src/docfx/lib/json/UnionTypeConverter.cs
  src/docfx/lib/process/InterProcessMutex.cs
  src/docfx/lib/process/InterProcessReaderWriterLock.cs
  src/docfx/lib/process/ProcessUtility.cs
  src/stylecop.ruleset
  test/docfx.Test/lib/UrlUtilityTest.cs
Labels: v3

#5500 Update validation service endpoint
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/markdown/validation/ContentValidationContext.cs
Labels: v3

#5502 refactor: remove Config from Docset
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/dependency/LinkResolver.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/LegacyAggregatedFileMap.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/legacy/LegacyUtility.cs
  src/docfx/build/legacy/manifest/LegacyManifest.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5504 refactor: Move Locale to LocalizationProvider
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/document/Docset.cs
  src/docfx/build/document/DocumentProvider.cs
  src/docfx/build/legacy/Legacy.cs
  src/docfx/build/legacy/LegacyFileMap.cs
  src/docfx/build/localization/LocalizationProvider.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/redirection/BuildRedirection.cs
  src/docfx/build/resource/BuildResource.cs
  src/docfx/build/toc/BuildTableOfContents.cs
  test/docfx.Test/build/TocTest.cs
Labels: v3

#5440 Build implicitly restore dependencies if not cached.
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  src/docfx/config/AppData.cs
  src/docfx/config/TestQuirks.cs
  src/docfx/lib/git/GitUtility.cs
  src/docfx/lib/log/Log.cs
  src/docfx/lib/path/PackagePath.cs
  src/docfx/lib/path/PathString.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/ModuleInitializer.cs
  test/docfx.Test/restore/RestoreTest.cs
Labels: v3

#5503 docs: update readme and contributing
  .github/CONTRIBUTING.md
  Documentation/tutorial/docfx_getting_started.md
  README.md
Labels: v2
