Repository dotnet/docfx, pull requests merged in 2020-11, with the labels that each got.

#6717 Update dependencies with known vulnerabilities
  src/docfx.website.themes/default/bower.json
Labels: dependencies, v2

#6715 Update json schema test cases
  src/docfx/lib/json/JTokenDeepEqualsComparer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  test/docfx.Test/data/jschema/draft7/additionalItems.json
  test/docfx.Test/data/jschema/draft7/additionalProperties.json
  test/docfx.Test/data/jschema/draft7/allOf.json
  test/docfx.Test/data/jschema/draft7/anyOf.json
  test/docfx.Test/data/jschema/draft7/const.json
  test/docfx.Test/data/jschema/draft7/contains.json
  test/docfx.Test/data/jschema/draft7/dependencies.json
  test/docfx.Test/data/jschema/draft7/enum.json
  test/docfx.Test/data/jschema/draft7/if-then-else.json
  test/docfx.Test/data/jschema/draft7/maxProperties.json
  test/docfx.Test/data/jschema/draft7/maximum.json
  test/docfx.Test/data/jschema/draft7/minimum.json
  test/docfx.Test/data/jschema/draft7/multipleOf.json
  test/docfx.Test/data/jschema/draft7/oneOf.json
  test/docfx.Test/data/jschema/draft7/pattern.json
  test/docfx.Test/data/jschema/draft7/patternProperties.json
  test/docfx.Test/data/jschema/draft7/ref.json
  test/docfx.Test/data/jschema/draft7/refRemote.json
  test/docfx.Test/data/jschema/draft7/type.json
  test/docfx.Test/data/jschema/draft7/uniqueItems.json
  test/docfx.Test/data/jschema/remotes/baseUriChange/folderInteger.json
  test/docfx.Test/data/jschema/remotes/baseUriChangeFolder/folderInteger.json
  test/docfx.Test/data/jschema/remotes/baseUriChangeFolderInSubschema/folderInteger.json
  test/docfx.Test/data/jschema/remotes/integer.json
  test/docfx.Test/data/jschema/remotes/name-defs.json
  test/docfx.Test/data/jschema/remotes/name.json
  test/docfx.Test/data/jschema/remotes/subSchemas-defs.json
  test/docfx.Test/data/jschema/remotes/subSchemas.json
Labels: v3

#6720 Move schema validation before schema transform
  docs/specs/schema.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
Labels: v3

#6721 🚢🚢
  .editorconfig
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  .github/workflows/spelling.yml
  Directory.Build.props
  docs/specs/schema.yml
  docs/specs/validation/heading-validation.yml
  docs/specs/zonepivot.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/zonepivot/ZonePivotProvider.cs
  src/docfx/docfx.csproj
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/json/JTokenDeepEqualsComparer.cs
  src/docfx/lib/markdown/validation/DocsValidationExtension.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/validation/ContentValidator.cs
  test/docfx.Test/data/jschema/draft7/additionalItems.json
  test/docfx.Test/data/jschema/draft7/additionalProperties.json
  test/docfx.Test/data/jschema/draft7/allOf.json
  test/docfx.Test/data/jschema/draft7/anyOf.json
  test/docfx.Test/data/jschema/draft7/const.json
  test/docfx.Test/data/jschema/draft7/contains.json
  test/docfx.Test/data/jschema/draft7/dependencies.json
  test/docfx.Test/data/jschema/draft7/enum.json
  test/docfx.Test/data/jschema/draft7/if-then-else.json
  test/docfx.Test/data/jschema/draft7/maxProperties.json
  test/docfx.Test/data/jschema/draft7/maximum.json
  test/docfx.Test/data/jschema/draft7/minimum.json
  test/docfx.Test/data/jschema/draft7/multipleOf.json
  test/docfx.Test/data/jschema/draft7/oneOf.json
  test/docfx.Test/data/jschema/draft7/pattern.json
  test/docfx.Test/data/jschema/draft7/patternProperties.json
  test/docfx.Test/data/jschema/draft7/ref.json
  test/docfx.Test/data/jschema/draft7/refRemote.json
  test/docfx.Test/data/jschema/draft7/type.json
  test/docfx.Test/data/jschema/draft7/uniqueItems.json
  test/docfx.Test/data/jschema/remotes/baseUriChange/folderInteger.json
  test/docfx.Test/data/jschema/remotes/baseUriChangeFolder/folderInteger.json
  test/docfx.Test/data/jschema/remotes/baseUriChangeFolderInSubschema/folderInteger.json
  test/docfx.Test/data/jschema/remotes/integer.json
  test/docfx.Test/data/jschema/remotes/name-defs.json
  test/docfx.Test/data/jschema/remotes/name.json
  test/docfx.Test/data/jschema/remotes/subSchemas-defs.json
  test/docfx.Test/data/jschema/remotes/subSchemas.json
  test/docfx.Test/lib/GlobUtilityTest.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#6724 fix service page output path
  docs/specs/toc/service-page.yml
  src/docfx/build/toc/ServicePageGenerator.cs
Labels: v3

#6727 don't generate service pages if the docfx.json file filters them.
  docs/specs/toc/service-page.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/toc/ServicePageGenerator.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
Labels: v3

#6726 Update Mapping Error-Code, include-not-found
  src/docfx/data/schemas/module-error-mapping.json
  src/docfx/data/schemas/moduleunit-error-mapping.json
Labels: v3

#6722 Support transform oneOf, anyOf, if/then/else
  docs/specs/schema.yml
  src/docfx/build/context/Context.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/lib/schema/JsonSchemaMap.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#6729 Support new site name `StartUps`
  src/docfx/config/ops/OpsConfigAdapter.cs
Labels: v3

#6730 Support JsonSchema $ref resolve using JsonPointer and $id
  src/docfx/build/context/Context.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaDefinition.cs
  src/docfx/lib/schema/JsonSchemaLoader.cs
  src/docfx/lib/schema/JsonSchemaReferenceResolver.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#6736 Diable codecov
  azure-pipelines-v3.yml
Labels: v3

#6737 JSON schemas $ref supports local file or HTTP
  docs/specs/schema.yml
  src/docfx/build/context/Context.cs
  src/docfx/lib/log/SourceMap.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaConverter.cs
  src/docfx/lib/schema/JsonSchemaLoader.cs
  src/docfx/lib/schema/JsonSchemaResolver.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/validation/MetadataValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#6741 🚢🚢
  docs/specs/schema.yml
  docs/specs/static.yml
  src/docfx/Errors.cs
  src/docfx/build/context/Context.cs
  src/docfx/lib/log/SourceMap.cs
  src/docfx/lib/schema/JsonSchema.cs
  src/docfx/lib/schema/JsonSchemaConverter.cs
  src/docfx/lib/schema/JsonSchemaLoader.cs
  src/docfx/lib/schema/JsonSchemaResolver.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/restore/FileResolver.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/template/liquid/LiquidTemplate.cs
  src/docfx/validation/MetadataValidator.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
  test/docfx.Test/template/LiquidTemplateTest.cs
Labels: v3

#6740 expose git contributor information
  docs/specs/git.yml
  docs/specs/legacy.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/BuildPage.cs
Labels: v3

#6747 Load external xrefmap in parallel
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/lib/collections/DictionaryBuilder.cs
  src/docfx/lib/collections/ListBuilder.cs
Labels: v3

#6711 add monikers for root node of split toc
  docs/specs/toc/split-toc.yml
  src/docfx/build/toc/TableOfContentsLoader.cs
Labels: v3

#6703 Disable TripleCrown for Default Locale
  docs/specs/learn.yml
  src/Microsoft.Docs.LearnValidation/LearnValidationConfig.cs
  src/Microsoft.Docs.LearnValidation/LearnValidationEntry.cs
  src/Microsoft.Docs.LearnValidation/PartialPublish/InvalidFilesProvider.cs
  src/Microsoft.Docs.LearnValidation/Validator.cs
  src/Microsoft.Docs.LearnValidation/Validators/AchievementValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/ModuleValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/PathValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/TokenValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/UnitValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/ValidatorBase.cs
  src/docfx/build/Build.cs
  src/docfx/config/ops/OpsPostProcessor.cs
Labels: v3

#6748 Fix Console.BufferWidth throw
  src/docfx/cli/New.cs
Labels: v3

#6750 🚢🚢
  docs/specs/git.yml
  docs/specs/learn.yml
  docs/specs/legacy.yml
  docs/specs/toc/split-toc.yml
  src/Microsoft.Docs.LearnValidation/LearnValidationConfig.cs
  src/Microsoft.Docs.LearnValidation/LearnValidationEntry.cs
  src/Microsoft.Docs.LearnValidation/PartialPublish/InvalidFilesProvider.cs
  src/Microsoft.Docs.LearnValidation/Validator.cs
  src/Microsoft.Docs.LearnValidation/Validators/AchievementValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/ModuleValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/PathValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/TokenValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/UnitValidator.cs
  src/Microsoft.Docs.LearnValidation/Validators/ValidatorBase.cs
  src/docfx/build/Build.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/build/toc/TableOfContentsLoader.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/cli/New.cs
  src/docfx/config/ops/OpsPostProcessor.cs
  src/docfx/docfx.csproj
  src/docfx/lib/collections/DictionaryBuilder.cs
  src/docfx/lib/collections/ListBuilder.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests.csproj
  test/docfx.Test/docfx.Test.csproj
Labels: v3

#6746 Expose contributor fix comments
  docs/specs/git.yml
  docs/specs/legacy.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/data/schemas/OpsMetadata.json
Labels: v3

#6751 🚢🚢🚢
  docs/specs/git.yml
  docs/specs/legacy.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/BuildPage.cs
  src/docfx/data/schemas/OpsMetadata.json
Labels: v3

#6756 refactor Errors.cs to trigger Validation Pipline
  src/docfx/Errors.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
Labels: v3

#6753 add debug tutorials
  docs/developer-guide.md
Labels: v3

#6762 fix spell check
  .github/actions/spell-check/dictionary/custom-dictionary.txt
Labels: v3

#6760 Make command line path args relative to cwd
  src/docfx/cli/CommandLineOptions.cs
Labels: v3

#6769 Parallel load external xrefmap respect order
  src/docfx/build/xref/ExternalXrefMap.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/XrefResolver.cs
  test/docfx.Test/build/XrefMapLoaderTest.cs
Labels: v3

#6752 Validation consider zone pivot
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  docs/specs/validation/heading-validation.yml
  docs/specs/validation/image-validation.yml
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TripleColon/ZoneExtension.cs
  src/docfx/docfx.csproj
  src/docfx/lib/markdown/MarkdigUtility.cs
  src/docfx/lib/markdown/validation/DocsValidationExtension.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#6713 Error override by build rules
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  azure-pipelines-v3.yml
  docs/specs/error.yml
  docs/specs/learn.yml
  docs/specs/validation/content-validation.yml
  src/docfx/build/Build.cs
  src/docfx/build/context/Context.cs
  src/docfx/config/Config.cs
  src/docfx/config/ops/OpsAccessor.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/log/CustomRule.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorBuilder.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/lib/schema/JsonSchemaValidator.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/validation/CustomRuleProvider.cs
  src/docfx/validation/JsonSchemaValidatorExtension.cs
  src/docfx/validation/MetadataValidator.cs
  test/docfx.RegressionTest/Options.cs
  test/docfx.RegressionTest/RegressionTest.cs
Labels: v3

#6771 Add regression repos
  azure-pipelines-v3.yml
Labels: v3

#6778 Should not add locale for api links
  docs/specs/resolve.yml
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/LocalizationUtility.cs
Labels: v3

#6774 Use Quickenshtein to get levenshtein distance
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  src/docfx/docfx.csproj
  src/docfx/lib/Levenshtein.cs
  src/docfx/lib/StringUtility.cs
  test/docfx.Test/lib/LevenshteinTest.cs
Labels: v3

#6749 Optimize sensitive term detection
  docs/specs/validation/content-validation.yml
  src/docfx/docfx.csproj
  src/docfx/validation/ContentValidator.cs
Labels: v3

#6782 🏎🏎🏎
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  docs/specs/resolve.yml
  docs/specs/validation/content-validation.yml
  src/docfx/config/ops/OpsAccessor.cs
  src/docfx/docfx.csproj
  src/docfx/lib/HtmlUtility.cs
  src/docfx/lib/Levenshtein.cs
  src/docfx/lib/LocalizationUtility.cs
  src/docfx/lib/StringUtility.cs
  src/docfx/validation/ContentValidator.cs
  test/docfx.Test/lib/LevenshteinTest.cs
Labels: v3

#6783 ignore contributors_to_exclude for github_contributors
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
Labels: v3

#6792 🚢🚢
  docs/specs/git.yml
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/cli/Docfx.cs
  src/docfx/docfx.csproj
Labels: v3

#6787 Log details on exception
  src/docfx/config/ops/OpsAccessor.cs
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
Labels: v3

#6793 Throttle msgraph call
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
Labels: v3

#6784 Add Watch<T>
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  src/docfx/lib/watch/ContainerFunction.cs
  src/docfx/lib/watch/IFunction.cs
  src/docfx/lib/watch/LeafFunction{T}.cs
  src/docfx/lib/watch/Watcher.cs
  src/docfx/lib/watch/Watch{T}.cs
  test/docfx.Test/lib/WatcherTest.cs
Labels: v3

#6794 🚢🚢🚢
  .github/actions/spell-check/dictionary/custom-dictionary.txt
  src/docfx/config/ops/OpsAccessor.cs
  src/docfx/lib/GlobUtility.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/watch/ContainerFunction.cs
  src/docfx/lib/watch/IFunction.cs
  src/docfx/lib/watch/LeafFunction{T}.cs
  src/docfx/lib/watch/Watcher.cs
  src/docfx/lib/watch/Watch{T}.cs
  test/docfx.Test/lib/WatcherTest.cs
Labels: v3

#6798 Update error for redirected-file-not-removed
  docs/specs/legacy.yml
  docs/specs/redirection.yml
  docs/specs/resolve.yml
  src/docfx/Errors.cs
  src/docfx/publish/PublishUrlMap.cs
Labels: v3

#6800 Suppress ca1001 and cleanup disposable
  .editorconfig
  src/docfx/build/DocsetBuilder.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/ops/OpsAccessor.cs
  src/docfx/lib/collections/DisposableCollector.cs
  src/docfx/lib/git/RepositoryProvider.cs
  src/docfx/lib/github/GitHubAccessor.cs
  src/docfx/lib/log/Telemetry.cs
  src/docfx/lib/msgraph/MicrosoftGraphAccessor.cs
  src/docfx/lib/process/InterProcessReaderWriterLock.cs
  src/docfx/restore/PackageResolver.cs
  src/docfx/restore/Restore.cs
  src/docfx/template/TemplateEngine.cs
  test/docfx.Test/build/OpsConfigAdapterTest.cs
  test/docfx.Test/lib/ProcessUtilityTest.cs
Labels: v3

#6803 Downgrade YamlDotNet
  azure-pipelines-v3.yml
  src/docfx/docfx.csproj
Labels: v3

#6796 Share docset builder, build scope, metadata across builds
  src/docfx/build/Builder.cs
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/log/ErrorLog.cs
Labels: v3

#6807 Support building a subset of files
  docs/specs/ecma2Yaml.yml
  docs/specs/maml2Yaml.yml
  docs/specs/single-file.yml
  src/docfx/build/Builder.cs
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/context/BuildScope.cs
  src/docfx/build/redirection/RedirectionProvider.cs
  src/docfx/build/toc/ServicePageGenerator.cs
  src/docfx/cli/CommandLineOptions.cs
  src/docfx/cli/Docfx.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3

#6814 update to new nuget tool installer to fix pipeline
  azure-pipelines-master.yml
  azure-pipelines-stable.yml
  azure-pipelines.yml
Labels: v2

#6802 Code sign: cover FSharp dll which is not signed
  azure-pipelines-master.yml
  azure-pipelines-stable.yml
Labels: v2

#6813 Share template engine across build
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/link/LinkResolver.cs
  src/docfx/build/page/PageBuilder.cs
  src/docfx/build/toc/TocBuilder.cs
  src/docfx/config/ops/OpsConfig.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/lib/schema/JsonSchemaTransformer.cs
  src/docfx/template/MustacheTemplate.cs
  src/docfx/template/TemplateEngine.cs
  src/docfx/validation/ContentValidator.cs
Labels: v3

#6812 add ms.author to errors.log
  docs/specs/metadata.yml
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/metadata/UserMetadata.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/log/Error.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/validation/CustomRuleProvider.cs
Labels: v3

#6816 Fix perf regression cause by retrieving metadata twice
  src/docfx/build/metadata/MetadataProvider.cs
  src/docfx/build/moniker/MonikerProvider.cs
  src/docfx/lib/log/ErrorList.cs
Labels: v3

#6815 Publish manifest for single file build is single file
  docs/specs/single-file.yml
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/link/FileLinkMapBuilder.cs
  src/docfx/build/page/PageBuilder.cs
  src/docfx/build/redirection/RedirectionBuilder.cs
  src/docfx/build/resource/ResourceBuilder.cs
  src/docfx/build/toc/TocBuilder.cs
  src/docfx/publish/PublishItem.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/lib/JsonSchemaTest.cs
Labels: v3

#6821 Building a simple markdown file in dry run mode does not touch xrefmap
  docs/specs/moniker.yml
  docs/specs/single-file.yml
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/xref/ExternalXrefMapLoader.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/publish/PublishModelBuilder.cs
  test/docfx.Test/DocfxTest.cs
  test/docfx.Test/DocfxTestSpec.cs
Labels: v3
