Repository dotnet/docfx, pull requests merged in 2022-06, with the labels that each got.

#8036 🚀🚀🚀
  .github/actions/spelling/expect.txt
  docs/specs/metadata.yml
  docs/specs/redirection.yml
  docs/specs/schema.yml
  docs/specs/validation/metadata-validation.yml
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/ImageExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonBlock.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonBlockParser.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonInline.cs
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/metadata/SystemMetadata.cs
  src/docfx/build/page/PageBuilder.cs
  src/docfx/build/xref/InternalXrefMapBuilder.cs
  src/docfx/build/xref/XrefResolver.cs
  src/docfx/docfx.csproj
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/template/TemplateEngine.cs
  test/Microsoft.Docs.MarkdigExtensions.Tests/ImageTest.cs
Labels: v3

#8040 use publish repository url to get docsets
  src/docfx/build/Builder.cs
  src/docfx/build/DocsetBuilder.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/restore/Restore.cs
Labels: v3

#8038 Video Extension: Added functionality for allowing Video Entry GUID in Video Extension
  src/Microsoft.Docs.MarkdigExtensions/QuoteSectionNote/QuoteSectionNoteParser.cs
  test/Microsoft.Docs.MarkdigExtensions.Tests/QuoteSectionNoteTest.cs
Labels: v3

#8044 design doc of repository urls
  docs/designs/repository-urls.md
Labels: v3

#8047 Source url in publish.json and .error.log for PR builds
  docs/specs/error.yml
  docs/specs/output.yml
  src/docfx/build/Builder.cs
  src/docfx/build/DocsetBuilder.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/Restore.cs
Labels: v3

#8054 🚢🚢🚢
  docs/designs/repository-urls.md
  docs/specs/error.yml
  docs/specs/output.yml
  src/Microsoft.Docs.MarkdigExtensions/QuoteSectionNote/QuoteSectionNoteParser.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/ChromelessFormExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/CodeExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/ImageExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonBlock.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonBlockParser.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonInline.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/TripleColonInlineParser.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/VideoExtension.cs
  src/Microsoft.Docs.MarkdigExtensions/TripleColon/ZoneExtension.cs
  src/docfx/build/metadata/ContributionProvider.cs
  src/docfx/config/ConfigLoader.cs
  src/docfx/config/EnvironmentVariable.cs
  src/docfx/config/PreloadConfig.cs
  src/docfx/config/ops/OpsConfigAdapter.cs
  src/docfx/lib/log/ErrorLog.cs
  src/docfx/publish/PublishModelBuilder.cs
  src/docfx/restore/Restore.cs
  test/Microsoft.Docs.MarkdigExtensions.Tests/QuoteSectionNoteTest.cs
Labels: v3

#8065 Upgrade Newtonsoft.Json to 13.0.1 to fix vulnerabilities.
  src/Microsoft.Docs.Build.Specialized/Microsoft.Docs.Build.Specialized.csproj
  src/Microsoft.Docs.Build.Specialized/views/Template/LandingData.cshtml
Labels: v3, dependencies, .NET

#8069 Disable learn-pr temporarily for regression test
  azure-pipelines-v3.yml
Labels: v3

#8062 Update Newtonsoft.Json.Schema and Newtonsoft.Json
  azure-pipelines.yml
  src/Microsoft.DocAsCode.Build.SchemaDriven/Microsoft.DocAsCode.Build.SchemaDriven.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Microsoft.DocAsCode.Metadata.ManagedReference.Common.csproj
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn.csproj
  src/Microsoft.DocAsCode.Plugins/Microsoft.DocAsCode.Plugins.csproj
  tools/GEmojiCodeGenerators/GEmojiCodeGenerators.csproj
  tools/YamlSplitter/YamlSplitter.csproj
Labels: v2

#8072 apply codeql
  .github/actions/spelling/expect.txt
  azure-pipelines-lgtm.yml
Labels: v3
