Repository dotnet/docfx, pull requests merged in 2023-09, with the labels that each got.

#9154 feat: support modern template localization
  templates/default(zh-cn)/token.json
  templates/default/token.json
  templates/modern/layout/_master.tmpl
  templates/modern/src/helper.ts
  templates/modern/src/markdown.ts
  templates/modern/src/nav.ts
  templates/modern/src/search.ts
  templates/modern/src/theme.ts
  templates/modern/src/toc.ts
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ConstantInterpolatedStrings.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.Issue7737.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ParameterlessStructConstructors.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ReadOnlyRecordStruct.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.RecordClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.RecordStruct.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.CheckedUserDefinedOperators-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.RequiredModifier.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.ScopedModifier.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.StaticAbstractMembersInInterfaces.IGetNext-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.StaticAbstractMembersInInterfaces.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DefaultInterfaceMembers.IA.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DefaultInterfaceMembers.Nested.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DefaultInterfaceMembers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DisposableRefStructs.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.Issue4007.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.Misc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.NullableReferenceTypes.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.ReadOnlyMembers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.FunctionPointers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.InitOnlySetters.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.NativeSizedIntegers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.Person.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.Teacher.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyEvent.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyProperty.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/index.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#9140 chore: Refactor docfx command related code
  src/Docfx.App/Helpers/Constants.cs
  src/Docfx.App/RunBuild.cs
  src/Docfx.App/RunMerge.cs
  src/Docfx.App/RunMetadata.cs
  src/Docfx.App/RunPdf.cs
  src/Docfx.App/RunServe.cs
  src/Docfx.DataContracts.Common/Constants.cs
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  src/docfx/Models/CommandHelper.cs
  src/docfx/Models/InitCommand.cs
  src/docfx/Models/MetadataCommand.cs
Labels: engineering

#9159 feat: support language attribute on C# documentation comment
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
Labels: new-feature

#9163 perf: Change JsonSerializerOptions instance to static
  src/Docfx.Build.SchemaDriven/Models/DocumentSchema.cs
Labels: performance

#9201 chore: Remove unused localsearch function from default template
  templates/default/styles/docfx.js
Labels: bug-fix

#9206 chore: fix `default/partials/title.tmpl.partial` file typo
  templates/default/partials/title.tmpl.partial
Labels: bug-fix

#9209 fix: merge members in same class name different assemblies
  samples/seed/dotnet/solution/CatLibrary.Core/BaseClass.cs
  samples/seed/dotnet/solution/CatLibrary/Class1.cs
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.Issue231.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#9220 fix: xml comment math inline escape
  samples/seed/dotnet/project/Project/Class1.cs
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
Labels: bug-fix

#9221 drop: remove some obsolete features
  src/Docfx.App/Config/BuildJsonConfig.cs
  src/Docfx.App/Config/ContentPairingInfo.cs
  src/Docfx.App/Config/GroupConfig.cs
  src/Docfx.App/Helpers/DocumentBuilderWrapper.cs
  src/Docfx.Build.Engine/DocumentBuildContext.cs
  src/Docfx.Build.Engine/DocumentBuildParameters.cs
  src/Docfx.Build.Engine/DocumentBuilder.cs
  src/Docfx.Build.Engine/HostService.cs
  src/Docfx.Build.Engine/HostServiceCreator.cs
  src/Docfx.Build.Engine/ManifestUtility.cs
  src/Docfx.Build.Engine/SingleDocumentBuilder.cs
  src/Docfx.Build.Engine/XRefMaps/XRefMap.cs
  src/Docfx.Build.SchemaDriven/ApplyTags.cs
  src/Docfx.Build.SchemaDriven/Processors/TagInterpreter.cs
  src/Docfx.Build.SchemaDriven/SchemaDrivenDocumentProcessor.cs
  src/Docfx.Build.SchemaDriven/TagInterpreters/ITagInterpreter.cs
  src/Docfx.Build.SchemaDriven/TagInterpreters/PatternedTagInterpreter.cs
  src/Docfx.Build.TableOfContents/TocHelper.cs
  src/Docfx.Common/FolderRedirection/FolderRedirectionManager.cs
  src/Docfx.Common/FolderRedirection/FolderRedirectionRule.cs
  src/Docfx.Plugins/BuildPhase.cs
  src/Docfx.Plugins/GroupInfo.cs
  src/Docfx.Plugins/HomepageInfo.cs
  src/Docfx.Plugins/IBuildParameters.cs
  src/Docfx.Plugins/IHostService.cs
  src/Docfx.Plugins/Manifest.cs
  src/Docfx.Plugins/SaveResult.cs
  src/Docfx.Plugins/UidDefinition.cs
  test/Docfx.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Docfx.Common.Tests/FolderRedirectionTest.cs
Labels: breaking-change

#9232 feat: experimental support for markdown output
  .github/workflows/ci.yml
  samples/seed/dotnet/solution/CatLibrary/Class1.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataConfig.cs
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Docfx.Dotnet/MarkdownFormatter.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  src/Docfx.Dotnet/SymbolFormatter.cs
  src/Docfx.Dotnet/SymbolHelper.cs
  src/Docfx.Dotnet/SymbolUrlResolver.cs
  src/docfx/Models/MetadataCommand.cs
  src/docfx/Models/MetadataCommandOptions.cs
  src/docfx/Properties/launchSettings.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromAssembly.Class1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromCSharpSourceCode.CSharp.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.IIssue8948.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8665.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8696Attribute.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8948.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Test`1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.IInheritdoc.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.Class1`1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.Class2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue7035.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue7484.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue8101.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue8129.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.A.A.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.B.B.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromVBSourceCode.BaseClass1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromVBSourceCode.Class1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.CatException`1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Cat`2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Complex`2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ColorType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeChild.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeChildInterface.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeDelegate.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ExplicitLayoutClass.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.Issue231.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.FakeDelegate`1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.IAnimal.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.ICat.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.ICatExtension.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.MRefDelegate`3.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.MRefNormalDelegate.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Tom.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.TomFromBaseClass.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/MRef.Demo.Enumeration.ColorType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/toc.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#9235 feat: markdown support namespaces and separated member pages
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Docfx.Dotnet/MarkdownFormatter.cs
  src/Docfx.Dotnet/SymbolFormatter.cs
  src/Docfx.Dotnet/SymbolHelper.cs
  src/Docfx.Dotnet/SymbolUrlResolver.cs
  src/Docfx.Dotnet/Visitors/VisitorHelper.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromAssembly.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromCSharpSourceCode.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.IIssue8948.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8665.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8696Attribute.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Issue8948.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Class1.Test-1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.Class1-1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.Class2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue6366.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue7035.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue7484.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue8101.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Inheritdoc.Issue8129.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.A.A.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.A.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.B.B.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.B.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.Issue8540.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromProject.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/BuildFromVBSourceCode.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Cat-2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.CatException-1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Complex-2.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ColorType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeChild.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeChildInterface.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.ContainersRefTypeDelegate.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ContainersRefType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.ExplicitLayoutClass.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.Issue231.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.Core.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.FakeDelegate-1.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.ICat.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.MRefDelegate-3.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/MRef.Demo.Enumeration.ColorType.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/MRef.Demo.Enumeration.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/MRef.Demo.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/MRef.verified.md
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/toc.verified.yml
Labels: new-feature

#9240 chore: drop support of metaddata command taking non docfx.json inputs
  src/docfx/Models/MetadataCommand.cs
  test/docfx.Tests/MetadataCommandTest.cs
Labels: breaking-change

#9237 feat: add overridable metadata output json config
  docs/reference/docfx-json-reference.md
  samples/Directory.Build.props
  samples/seed/docfx.json
  src/Docfx.App/Config/BuildJsonConfig.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#9244 feat: add --memberLayout argument to metadata command
  .github/workflows/ci.yml
  src/docfx/Models/MetadataCommand.cs
  src/docfx/Models/MetadataCommandOptions.cs
Labels: new-feature

#9251 fix: anchor sometimes failed to scroll
  templates/modern/src/markdown.ts
Labels: bug-fix
