Repository dotnet/docfx, pull requests merged in 2023-02, with the labels that each got.

#8384 fix: assert failure for cast operator overloads
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolHelper.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: bug-fix

#8386 fix: projects in sln build twice
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/FileInformation.cs
  src/Microsoft.DocAsCode.Dotnet/Microsoft.DocAsCode.Dotnet.csproj
Labels: bug-fix

#8387 fix: get assembly xml comment using DocumentationProvider
  samples/seed/dotnet/assembly/BuildFromAssembly.csproj
  samples/seed/dotnet/assembly/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/CompilationUtility.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/MergeComments/CommentIdAndComment.cs
  src/Microsoft.DocAsCode.Dotnet/MergeComments/CommentIdAndReader.cs
  src/Microsoft.DocAsCode.Dotnet/MergeComments/Extensions.cs
  src/Microsoft.DocAsCode.Dotnet/MergeComments/MergeCommentsHelper.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/TripleSlashCommentModel.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/TripleSlashParserUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
Labels: bug-fix

#8388 BREAKING CHANGE: drop metadata command incremental build
  docs/tutorial/docfx.exe_user_manual.md
  samples/extensions/docfx.json
  samples/seed/docfx.json
  src/Microsoft.DocAsCode.App/Config/BuildJsonConfig.cs
  src/Microsoft.DocAsCode.App/Config/MetadataJsonItemConfig.cs
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/Microsoft.DocAsCode.App/RunMetadata.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/AssemblyFileInputParameters.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataInputModel.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataOptions.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/IInputParameters.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ProjectDocumentCache.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ProjectFileInputParameters.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/SourceFileInputParameters.cs
  src/Microsoft.DocAsCode.Dotnet/Incremental/ApplicationLevelCache.cs
  src/Microsoft.DocAsCode.Dotnet/Incremental/BuildInfo.cs
  src/Microsoft.DocAsCode.Dotnet/Incremental/CacheBase.cs
  src/Microsoft.DocAsCode.Dotnet/Incremental/IncrementalCheck.cs
  src/Microsoft.DocAsCode.Dotnet/Incremental/ProjectLevelCache.cs
  src/docfx/Models/BuildCommandOptions.cs
  src/docfx/Models/CascadableOptions.cs
  src/docfx/Models/MetadataCommandOptions.cs
  src/docfx/SubCommands/BuildCommand.cs
  src/docfx/SubCommands/MetadataCommand.cs
  test/docfx.Tests/ArgsParserTest.cs
Labels: breaking-change

#8393 feat: Support <include> XML comment tag
  samples/seed/dotnet/csharp/CSharp.cs
  samples/seed/dotnet/docs.xml
  samples/seed/dotnet/project/CSharp8.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/CompilationUtility.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/ApiFilterUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/DefinitionMergeUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyEvent.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyField.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.Myroperty.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromCSharpSourceCode.CSharp.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.BaseClass1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Issue4007.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: new-feature

#8395 feat: Support latest C# syntax highlighting
  docs/docs/markdown.md
  docs/docs/media/Program.cs
  templates/.gitignore
  templates/build.js
  templates/default/styles/docfx.js
  templates/package.json
  templates/src/main.js
Labels: new-feature

#8398 Update license link in README
  README.md
Labels: documentation

#8399 feat: add API to generate .NET mref YAML files
  docfx.sln
  docs/docfx.json
  samples/extensions/build/Program.cs
  src/Microsoft.DocAsCode.App/Docset.cs
  src/Microsoft.DocAsCode.App/Helpers/Constants.cs
  src/Microsoft.DocAsCode.App/Microsoft.DocAsCode.App.csproj
  src/Microsoft.DocAsCode.Common/FileItems.cs
  src/Microsoft.DocAsCode.Common/FileMapping.cs
  src/Microsoft.DocAsCode.Common/FileMappingConverter.cs
  src/Microsoft.DocAsCode.Common/FileMappingItem.cs
  src/Microsoft.DocAsCode.Common/FileModelParser.cs
  src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs
  src/Microsoft.DocAsCode.Dotnet/MetadataJsonConfig.cs
  src/Microsoft.DocAsCode.Dotnet/MetadataJsonItemConfig.cs
  src/Microsoft.DocAsCode.Dotnet/Microsoft.DocAsCode.Dotnet.csproj
  src/Microsoft.DocAsCode.Glob/GlobUtility.cs
  src/docfx/SubCommands/InitCommand.cs
  src/docfx/SubCommands/MetadataCommand.cs
  src/docfx/docfx.csproj
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#8408 feat: allow custom API filtering
  docfx.sln
  src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs
  src/Microsoft.DocAsCode.Dotnet/DotnetApiOptions.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/RoslynIntermediateMetadataExtractor.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolFilter.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.Syntax.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolHelper.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/AllMemberFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/CachedFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/ConfigFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/DefaultFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/DelegatingFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/FilterVisitorExtensions.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/IFilterVisitor.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs
  src/docfx/SubCommands/MetadataCommand.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/ApiFilterUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/DefinitionMergeUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromAssemblyTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromVBUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: new-feature

#8416 fix: cannot search due to lunr not defined
  templates/build.js
  templates/default/styles/docfx.js
  templates/src/search-worker.js
Labels: bug-fix

#8418 fix: Newtonsoft.Json.Schema -> JsonSchema.Net
  src/Microsoft.DocAsCode.App/Config/BuildJsonConfig.cs
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Microsoft.DocAsCode.Build.SchemaDriven.csproj
  src/Microsoft.DocAsCode.Build.SchemaDriven/Models/BaseSchema.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Models/DocumentSchema.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/SchemaFragmentsIterator.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Validators/SchemaValidateService.cs
  src/Microsoft.DocAsCode.Build.SchemaDriven/Validators/SchemaValidator.cs
  src/docfx/Models/BuildCommandOptions.cs
  src/docfx/SubCommands/BuildCommand.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaFragmentsIteratorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/schemas/general.test.schema.json
Labels: bug-fix

#8422 test: add visual snapshot testing
  templates/src/docfx.ts
  test/docfx.Snapshot.Tests/ModuleInitializer.cs
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.cs
  test/docfx.Snapshot.Tests/docfx.Snapshot.Tests.csproj
Labels: engineering

#8437 BREAKING CHANGE: drop support of liquid template
  docs/template/dashboard.html.liquid
  docs/template/dashboard.html.tmpl
  docs/tutorial/intro_template.md
  src/Microsoft.DocAsCode.Build.Engine/Microsoft.DocAsCode.Build.Engine.csproj
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/Template.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/ViewRenderers/LiquidTemplateRenderer.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/ViewRenderers/RendererLoader.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/ViewRenderers/TemplateRendererType.cs
  templates/default/partials/_affix.liquid
  templates/default/partials/_breadcrumb.liquid
  templates/default/partials/_footer.liquid
  templates/default/partials/_head.liquid
  templates/default/partials/_logo.liquid
  templates/default/partials/_navbar.liquid
  templates/default/partials/_scripts.liquid
  templates/default/partials/_toc.liquid
  test/Microsoft.DocAsCode.Build.Engine.Tests/TemplateManagerUnitTest.cs
Labels: breaking-change

#8444 fix: sticky header anchor using scroll-margin-top
  templates/src/docfx.scss
  templates/src/docfx.ts
  templates/src/helper.ts
  templates/src/markdown.scss
  templates/src/nav.scss
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/docs-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/docs-markdown.html-tabs-windows-2Ctypescript.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/docs-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/docs-markdown.html-tabs-windows-2Ctypescript.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/docs-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/docs-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/docs-markdown.html-tabs-windows-2Ctypescript.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/docs-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/docs-markdown.html-tabs-windows-2Ctypescript.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: bug-fix

#8457 feat: multiple overwrite sections using markdig
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.Engine/HostService.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/DfmJsonTokenTreeServiceProvider.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/DfmServiceProvider.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/GfmServiceProvider.cs
  src/Microsoft.DocAsCode.Build.Engine/MarkdownProviders/JsonTokenTreeServiceProvider.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigEngine/YamlHeader/YamlHeaderExtension.cs
  src/Microsoft.DocAsCode.MarkdigEngine/YamlHeader/YamlHeaderRenderer.cs
  src/Microsoft.DocAsCode.Plugins/IMarkdownService.cs
  test/Microsoft.DocAsCode.Build.Common.Tests/MarkdownReaderTest.cs
  test/Microsoft.DocAsCode.Build.Common.Tests/ModelAttributeHandlerTest.cs
  test/Microsoft.DocAsCode.Build.ConceptualDocuments.Tests/ConceptualDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/ManagedReferenceDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/TestData/overwrite/mref.overwrite.parameters.md
  test/Microsoft.DocAsCode.Build.ManagedReference.WithPlugins.Tests/SplitClassPageToMemberLevelTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.Tests/RestApiDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.WithPlugins.Tests/SplitRestApiToOperationLevelTest.cs
  test/Microsoft.DocAsCode.Build.RestApi.WithPlugins.Tests/SplitRestApiToTagLevelTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/MergeMarkdownFragmentsTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/SchemaMergerTest.cs
  test/Microsoft.DocAsCode.Build.UniversalReference.Tests/UniversalReferenceDocumentProcessorTest.cs
  test/docfx.Tests/BuildCommandTest.cs
Labels: new-feature
