Repository dotnet/docfx, pull requests merged in 2023-03, with the labels that each got.

#8485 Improvement Document Guideline markdown with image
  docs/docs/markdown.md
Labels: documentation

#8491 fix: incorrect type name for unresolved generic types
  src/Microsoft.DocAsCode.Build.Engine/XrefDetails.cs
Labels: bug-fix

#8499 feat: add dark theme to modern template
  templates/modern/layout/_master.tmpl
  templates/modern/src/docfx.scss
  templates/modern/src/docfx.ts
  templates/modern/src/highlight.scss
  templates/modern/src/layout.scss
  templates/modern/src/markdown.scss
  templates/modern/src/nav.scss
  templates/modern/src/nav.ts
  templates/modern/src/toc.scss
  templates/modern/src/toc.ts
  templates/package-lock.json
  templates/package.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#8510 fix: custom logo not override logo from template
  src/Microsoft.DocAsCode.App/Docset.cs
  src/Microsoft.DocAsCode.App/RunServe.cs
  src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateProcessor.cs
  test/docfx.Tests/DocsetTest.cs
Labels: bug-fix

#8512 feature: add theme toggle
  templates/modern/layout/_master.tmpl
  templates/modern/partials/footer.tmpl.partial
  templates/modern/partials/scripts.tmpl.partial
  templates/modern/src/docfx.ts
  templates/modern/src/layout.scss
  templates/modern/src/theme.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8516 feat: update markdown tab style
  templates/modern/src/markdown.scss
  templates/modern/src/markdown.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: new-feature

#8517 feat: add code copy
  templates/modern/src/markdown.scss
  templates/modern/src/markdown.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8518 feat: clickable image
  templates/modern/src/markdown.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: new-feature

#8521 feat: add <wbr> tags to word boundaries
  .github/actions/build/action.yml
  templates/jest.config.js
  templates/modern/src/docfx.scss
  templates/modern/src/docfx.ts
  templates/modern/src/helper.test.ts
  templates/modern/src/helper.ts
  templates/modern/src/markdown.ts
  templates/modern/src/nav.ts
  templates/modern/src/toc.ts
  templates/package-lock.json
  templates/package.json
  templates/tsconfig.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8524 chore: tweak the color, spacing, icons of the modern template
  plugins/Microsoft.DocAsCode.Build.MemberLevelManagedReference/templates/memberpage/partials/class.tmpl.partial
  plugins/Microsoft.DocAsCode.Build.MemberLevelManagedReference/templates/memberpage/partials/collection.tmpl.partial
  templates/default/partials/class.header.tmpl.partial
  templates/default/partials/class.tmpl.partial
  templates/default/partials/enum.tmpl.partial
  templates/default/partials/rest.child.tmpl.partial
  templates/default/partials/uref/class.tmpl.partial
  templates/default/partials/uref/enum.tmpl.partial
  templates/default/partials/uref/namespace.tmpl.partial
  templates/default/partials/uref/parameters.tmpl.partial
  templates/default/styles/docfx.js
  templates/modern/layout/_master.tmpl
  templates/modern/src/docfx.scss
  templates/modern/src/layout.scss
  templates/modern/src/markdown.scss
  templates/modern/src/markdown.ts
  templates/modern/src/nav.scss
  templates/modern/src/nav.ts
  templates/modern/src/theme.ts
  templates/modern/src/toc.scss
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8536 Clean up
  .editorconfig
  .gitignore
  Directory.Build.props
  Directory.Packages.props
  plugins/Directory.Build.props
  src/Directory.Build.props
  src/Microsoft.DocAsCode.Build.Common/Microsoft.DocAsCode.Build.Common.csproj
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.Build.Engine/Microsoft.DocAsCode.Build.Engine.csproj
  src/Microsoft.DocAsCode.Build.OverwriteDocuments/Microsoft.DocAsCode.Build.OverwriteDocuments.csproj
  src/Microsoft.DocAsCode.Build.SchemaDriven/Microsoft.DocAsCode.Build.SchemaDriven.csproj
  src/Microsoft.DocAsCode.Dfm/Microsoft.DocAsCode.Dfm.csproj
  src/Microsoft.DocAsCode.Dotnet/Microsoft.DocAsCode.Dotnet.csproj
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.Symbols.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs
  src/Microsoft.DocAsCode.HtmlToPdf/Microsoft.DocAsCode.HtmlToPdf.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
  src/Microsoft.DocAsCode.MarkdigEngine.Validators/Microsoft.DocAsCode.MarkdigEngine.Validators.csproj
  src/Microsoft.DocAsCode.MarkdigEngine/Microsoft.DocAsCode.MarkdigEngine.csproj
  src/Microsoft.DocAsCode.MarkdownLite/Microsoft.DocAsCode.MarkdownLite.csproj
  src/Microsoft.DocAsCode.Plugins/Microsoft.DocAsCode.Plugins.csproj
  src/Microsoft.DocAsCode.YamlSerialization/Microsoft.DocAsCode.YamlSerialization.csproj
  src/docfx/docfx.csproj
  test/Directory.Build.props
  test/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests/Microsoft.DocAsCode.Build.OverwriteDocuments.Tests.csproj
  test/docfx.Snapshot.Tests/docfx.Snapshot.Tests.csproj
Labels: engineering

#8541 Target .NET 8.0
  .github/actions/build/action.yml
  .github/workflows/ci.yml
  Directory.Build.props
Labels: new-feature

#8548 feat: view source for assemblies using sourcelink
  docs/docs/dotnet-api-docs.md
  samples/seed/dotnet/assembly/BuildFromAssembly.csproj
  src/Microsoft.DocAsCode.Common/Git/GitUtility.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/SourceLink/PortableCustomDebugInfoKinds.cs
  src/Microsoft.DocAsCode.Dotnet/SourceLink/SourceLinkMap.cs
  src/Microsoft.DocAsCode.Dotnet/SourceLink/SymbolSourceDocumentFinder.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolHelper.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.SourceLink.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/VisitorHelper.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs
  templates/common/common.js
  test/Microsoft.DocAsCode.Dotnet.Tests/SymbolUrlResolverUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.html.view.verified.json
Labels: new-feature

#8549 fix: mslearn link not resolved in generic type parameter
  src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiReferenceBuildOutput.cs
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ConstantInterpolatedStrings.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.Issue7737.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ParameterlessStructConstructors.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.ReadOnlyRecordStruct.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.RecordClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.RecordStruct.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.RequiredModifier.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp11.StaticAbstractMembersInInterfaces.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DefaultInterfaceMembers.Nested.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.DisposableRefStructs.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.Issue4007.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.Misc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.NullableReferenceTypes.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.ReadOnlyMembers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.FunctionPointers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.InitOnlySetters.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.NativeSizedIntegers.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.Person.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.Teacher.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp9.RecordTypes.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyEvent.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromCSharpSourceCode.CSharp.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Test-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.BaseClass1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.CatException-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Complex-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.ContainersRefTypeChild.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ExplicitLayoutClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.FakeDelegate-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICat.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefNormalDelegate.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Tom.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.html.view.verified.json
Labels: bug-fix

#8550 feat: resolve langword to URLs
  docs/tutorial/docfx.exe_user_manual.md
  samples/extensions/docfx.json
  src/Microsoft.DocAsCode.App/Config/BuildJsonConfig.cs
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/Microsoft.DocAsCode.App/Microsoft.DocAsCode.App.csproj
  src/Microsoft.DocAsCode.App/langwordMapping.yml
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlCommentTransformer.cs
  src/Microsoft.DocAsCode.Dotnet/Resources/XmlCommentTransform.xsl
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.Langword.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.SourceLink.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/VisitorHelper.cs
  src/docfx/Models/BuildCommandOptions.cs
  src/docfx/SubCommands/BuildCommand.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Tests/JsonConverterTest.cs
Labels: new-feature

#8551 fix: &apos; in seealso
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: bug-fix

#8552 fix: NRE on duplicated params
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: bug-fix

#8554 feat: add allowCompilationErrors option
  src/Microsoft.DocAsCode.Dotnet/CompilationHelper.cs
  src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataConfig.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/MetadataJsonItemConfig.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
Labels: new-feature

#8555 fix: add margin to list terms
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/Resources/XmlCommentTransform.xsl
  templates/modern/src/dotnet.scss
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Test-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: bug-fix

#8556 fix: undefined lunrIndex
  templates/modern/src/search-worker.ts
Labels: bug-fix

#8557 BREAKING CHANGE: drop preserveRawInlineComment
  src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataConfig.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlCommentParserContext.cs
  src/Microsoft.DocAsCode.Dotnet/Resolvers/ResolverContext.cs
  src/Microsoft.DocAsCode.Dotnet/Resolvers/YamlMetadataResolver.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  src/docfx/Models/CascadableOptions.cs
  src/docfx/Models/MetadataCommandOptions.cs
  src/docfx/SubCommands/MetadataCommand.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: breaking-change

#8559 chore: remove sees from YAML output
  src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiBuildOutput.cs
  src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiReferenceBuildOutput.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/MetadataItem.cs
  src/Microsoft.DocAsCode.Dotnet/ManagedReference/ItemViewModel.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  src/Microsoft.DocAsCode.Dotnet/Resolvers/ResolveReference.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/VisitorHelper.cs
  src/Microsoft.DocAsCode.Dotnet/YamlViewModelExtensions.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: breaking-change

#8568 chore: drop useCompatibilityFileName
  docs/tutorial/docfx.exe_user_manual.md
  src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataConfig.cs
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Dotnet/MetadataJsonItemConfig.cs
Labels: breaking-change

#8570 Update index.md workflow sample
  docs/index.md
Labels: documentation

#8573 fix: dark theme flash on page refresh
  templates/modern/layout/_master.tmpl
  templates/modern/src/theme.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: bug-fix
