Repository dotnet/docfx, pull requests merged in 2023-12, with the labels that each got.

#9530 chore: drop name.vb from toc output
  src/Docfx.Build.ManagedReference/SplitClassPageToMemberLevel.cs
  src/Docfx.Build/TableOfContents/TocDocumentProcessor.cs
  src/Docfx.DataContracts.Common/TocItemViewModel.cs
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Linux/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Linux/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Linux/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Windows/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Windows/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp.Windows/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Linux/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Linux/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Linux/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Windows/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Windows/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions.Windows/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.verified.json
Labels: breaking-change

#9531 fix: code copy not shown on collapsed divs
  samples/seed/articles/markdown.md
  templates/modern/src/markdown.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: bug-fix

#9540 Support new submodule format using .git file
  src/Docfx.Common/Git/GitUtility.cs
Labels: new-feature

#9542 fix: PDF wait for network idle
  src/Docfx.App/PdfBuilder.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/seed.pdf.verified.json
Labels: bug-fix

#9554 chore: Hide the Docfx templates folder from VS project tree
  src/Docfx.App/Build/docfx.app.props
  src/Docfx.App/Docfx.App.csproj
Labels: bug-fix

#9543 feat: support PDF header footer template
  docs/docs/pdf.md
  src/Docfx.App/PdfBuilder.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/apipage/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/md/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/restapi/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/apipage/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/md/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/restapi/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/toc.pdf.verified.json
Labels: new-feature
