Repository dotnet/docfx, pull requests merged in 2023-04, with the labels that each got.

#8595 BREAKING CHANGE: retire xref service
  docs/tutorial/docfx.exe_user_manual.md
  docs/tutorial/links_and_cross_references.md
  src/Microsoft.DocAsCode.App/Config/BuildJsonConfig.cs
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildContext.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Build.Engine/XrefServiceResolver.cs
  src/docfx/Models/BuildCommandOptions.cs
  src/docfx/SubCommands/BuildCommand.cs
  test/Microsoft.DocAsCode.Build.Engine.Tests/DocumentBuilderTest.cs
Labels: breaking-change

#8600 feat: support math expressions
  docs/docs/markdown.md
  samples/seed/articles/markdown.md
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs
  templates/modern/layout/_master.tmpl
  templates/modern/src/docfx.ts
  templates/package-lock.json
  templates/package.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8609 Update markdown.md
  docs/docs/markdown.md
Labels: documentation

#8607 fix: xml comment whitespace handling
  samples/common/Example.cs
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlCommentParserContext.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlCommentTransformer.cs
  src/Microsoft.DocAsCode.Dotnet/Resources/XmlCommentTransform.xsl
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp10.Issue7737.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.Issue4007.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/api/CSharp8.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromAssembly.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Test-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.IInheritdoc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Inheritdoc.Issue6366.Class1-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Inheritdoc.Issue6366.Class2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Inheritdoc.Issue7484.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Inheritdoc.Issue8101.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Inheritdoc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.BaseClass1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.ColorType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.ContainersRefTypeDelegate.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.FakeDelegate-1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICat.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefDelegate-3.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefNormalDelegate.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Tom.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.ColorType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#8596 fix: xml entity escape for markdown
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/Microsoft.DocAsCode.Dotnet.csproj
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlCommentParserContext.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
Labels: bug-fix

#8624 feat: support name only TOC node
  docs/docs/toc.yml
  samples/seed/articles/toc.yml
  templates/modern/src/toc.scss
  templates/modern/src/toc.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
Labels: new-feature

#8613 feat: move modern template icons location to menu bar
  templates/modern/layout/_master.tmpl
  templates/modern/src/docfx.ts
  templates/modern/src/layout.scss
  templates/modern/src/nav.scss
  templates/modern/src/nav.ts
  templates/modern/src/theme.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#8630 fix: angle bracket escape in code inline
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/Parsers/XmlComment.cs
  test/Microsoft.DocAsCode.Dotnet.Tests/XmlCommentUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
Labels: bug-fix

#8631 fix: ignore unsupported PDB formats
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.SourceLink.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
Labels: bug-fix

#8632 fix: resolve windows app sdk URL
  src/Microsoft.DocAsCode.Dotnet/Resources/MSLearnAssemblies.txt
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.MSLearn.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.MSLearnAssemblies.cs
Labels: bug-fix

#8637 fix: hide generated assembly name
  src/Microsoft.DocAsCode.Dotnet/CompilationHelper.cs
  src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs
  templates/modern/partials/class.header.tmpl.partial
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyEvent.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyProperty.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromCSharpSourceCode.CSharp.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromCSharpSourceCode.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.BaseClass1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromVBSourceCode.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
Labels: bug-fix

#8640 test: skip snapshot tests in local run
  .github/workflows/ci.yml
  samples/seed/articles/markdown.md
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: engineering

#8656 Add .NET Foundation footer.
  docs/docfx.json
Labels: documentation

#8663 fix: duplicated PDF toc name
  templates/pdf.default/partials/toc.li.tmpl.partial
Labels: bug-fix

#8664 feat: iTextSharp -> PdfPig
  Directory.Packages.props
  samples/seed/pdf/toc.yml
  src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs
  src/Microsoft.DocAsCode.HtmlToPdf/Microsoft.DocAsCode.HtmlToPdf.csproj
Labels: new-feature

#8666 fix: compare uid string using ordical
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Build.ManagedReference/SplitClassPageToMemberLevel.cs
  src/Microsoft.DocAsCode.Dotnet/YamlViewModelExtensions.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Issue8665.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#8680 fix: edit link -> source url for modern template
  templates/modern/layout/_master.tmpl
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: bug-fix

#8689 fix: forward build command args to default command
  src/docfx/Models/BuildCommand.cs
  src/docfx/Models/DefaultCommand.cs
  src/docfx/Models/PdfCommand.cs
  src/docfx/Models/ServeCommand.cs
  test/docfx.Tests/CommandLineTest.cs
Labels: bug-fix

#8694 feat: support navbar dropdown button
  samples/seed/toc.yml
  templates/modern/src/nav.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8690 doc: added basic concepts page
  docs/docs/basic-concepts.md
  docs/docs/toc.yml
  docs/images/output-example.png
Labels: documentation

#8698 fixes: typedConstant NRE
  samples/seed/dotnet/project/Project/Class1.cs
  src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.Syntax.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Issue8696Attribute.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#8682 feat: add modern template customization options
  docs/docs/config.md
  docs/docs/template.md
  docs/template/public/main.css
  docs/template/public/main.js
  samples/seed/articles/markdown.md
  samples/seed/docfx.json
  samples/seed/template/public/bicep.js
  samples/seed/template/public/main.js
  templates/build.js
  templates/modern/layout/_master.tmpl
  templates/modern/public/main.css
  templates/modern/public/main.js
  templates/modern/src/docfx.ts
  templates/modern/src/highlight.ts
  templates/modern/src/markdown.ts
  templates/modern/src/nav.ts
  templates/modern/src/options.d.ts
  templates/modern/src/search.ts
  templates/modern/src/theme.ts
  templates/tsconfig.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8700 make postprocessors work again
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
Labels: bug-fix

#8701 fix: MetadataItem.Source NRE
  src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
Labels: bug-fix
