Repository dotnet/docfx, pull requests merged in 2023-01, with the labels that each got.

#8328 fix: wrong PDF template
  .github/workflows/ci.yml
  .gitignore
  README.md
  samples/seed/docfx.json
  samples/seed/pdf/toc.yml
  src/Microsoft.DocAsCode.App/Microsoft.DocAsCode.App.csproj
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: bug-fix

#8340 feat: Support redirect_url
  docs/template/layout/_master.tmpl
  templates/default/layout/_master.tmpl
  templates/default/partials/head.tmpl.partial
Labels: new-feature

#8343 test: add C# 8 test cases
  samples/seed/docfx.json
  samples/seed/src/DotnetNew/CSharp8.cs
  samples/seed/src/DotnetNew/Class1.cs
  samples/seed/src/DotnetNew/DotnetNew.csproj
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.IA.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.Nested.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DisposableRefStructs.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Issue4007.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Misc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.ReadOnlyMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: engineering

#8342 BREAKING CHANGE: Set markdig as default and deprecate dfm.
  docs/docfx.json
  samples/extensions/docfx.json
  samples/seed/docfx.json
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/docfx/SubCommands/InitCommand.cs
  test/docfx.Tests/BuildCommandTest.cs
  test/docfx.Tests/CompositeCommandTest.cs
Labels: breaking-change

#8341 feat: clickable console log
  src/Microsoft.DocAsCode.App/Docset.cs
  src/Microsoft.DocAsCode.Common/Loggers/AggregatedLogListener.cs
  src/Microsoft.DocAsCode.Common/Loggers/ConsoleLogListener.cs
  src/Microsoft.DocAsCode.Common/Loggers/Logger.cs
  src/Microsoft.DocAsCode.Common/Loggers/ReplayLogListener.cs
  src/docfx/Program.cs
Labels: new-feature

#8349 feat: Support building csproj targeting net7.0
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  plugins/Directory.Build.props
  samples/seed/src/DotnetNew/CSharp11.cs
  samples/seed/src/DotnetNew/DotnetNew.csproj
  src/Directory.Build.props
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/NameVisitor.cs
  src/Microsoft.DocAsCode.Plugins/Microsoft.DocAsCode.Plugins.csproj
  test/Directory.Build.props
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.RequiredModifier.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.IGetNext-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: new-feature

#8350 fix: RunPdf.Exec threw ArgumentNullException resolving path to wkhtmltopdf
  src/Microsoft.DocAsCode.App/RunPdf.cs
Labels: bug-fix

#8358 feat: allow custom markdown extensions
  samples/extensions/build/Program.cs
  samples/extensions/build/build.csproj
  samples/extensions/index.md
  src/Microsoft.DocAsCode.App/BuildOptions.cs
  src/Microsoft.DocAsCode.App/Docset.cs
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/Microsoft.DocAsCode.App/Microsoft.DocAsCode.App.csproj
  src/Microsoft.DocAsCode.App/RunBuild.cs
  src/Microsoft.DocAsCode.App/RunPdf.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs
  src/Microsoft.DocAsCode.Build.Engine/DocumentBuilder.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs
  src/Microsoft.DocAsCode.MarkdigEngine/MarkdigServiceProvider.cs
  src/docfx/SubCommands/BuildCommand.cs
  src/docfx/SubCommands/PdfCommand.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/index.raw.verified.json
Labels: new-feature

#8364 chore!: drop modifiers from .NET API YAML output
  src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiReferenceBuildOutput.cs
  src/Microsoft.DocAsCode.DataContracts.Common/Constants.cs
  src/Microsoft.DocAsCode.DataContracts.ManagedReference/ItemViewModel.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Models/MetadataItem.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/YamlViewModelExtensions.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/ManagedReferenceDocumentProcessorTest.cs
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/TestData/mref/CatLibrary.Cat-2.yml
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/TestData/mref/Namespace1.Class1`2.#ctor.yml
  test/Microsoft.DocAsCode.Build.ManagedReference.Tests/TestData/mref/Namespace1.Class1`2.yml
  test/Microsoft.DocAsCode.Build.ManagedReference.WithPlugins.Tests/TestData/mref/CatLibrary.Cat`2.yml
  test/Microsoft.DocAsCode.Build.ManagedReference.WithPlugins.Tests/TestData/mref/Microsoft.DocAsCode.Build.SchemaDriven.MergeType.yml
  test/Microsoft.DocAsCode.Build.MergeOverwrite.Tests/TestData/mref/CatLibrary.Cat-2.yml
  test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/inputs/CatLibrary.ICat.yml
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromVBUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.Myroperty.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ConstantInterpolatedStrings.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.Issue7737.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ParameterlessStructConstructors.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ReadOnlyRecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.RequiredModifier.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DisposableRefStructs.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Issue4007.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Misc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.ReadOnlyMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.FunctionPointers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.InitOnlySetters.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.NativeSizedIntegers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Person.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Teacher.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Tom.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/VBTestClass1.BaseClass1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/VBTestClass1.Class1.raw.verified.json
Labels: breaking-change

#8366 feat: generate C# API names using SymbolDisplay
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Models/ReferenceItem.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromAssemblyTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromVBUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ParameterlessStructConstructors.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ReadOnlyRecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.IGetNext-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Person.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Teacher.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: new-feature

#8367 feat: display C# API declaration using SymbolDisplay
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Helpers/EnumOps.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.Symbols.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.Syntax.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolHelper.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/SimpleYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromVBUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.Issue7737.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ParameterlessStructConstructors.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ReadOnlyRecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.RequiredModifier.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.IGetNext-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.IA.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.Nested.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DisposableRefStructs.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Issue4007.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Misc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.ReadOnlyMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.InitOnlySetters.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Person.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Teacher.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.CatException-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.FakeDelegate-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICat.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefDelegate-3.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefNormalDelegate.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeChild.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeChildInterface.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeDelegate.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/VBTestClass1.Class1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
Labels: new-feature

#8375 [BREAKING CHANGE]: drop builtin fsproj support
  .vsconfig
  README.md
  docfx.sln
  src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Microsoft.DocAsCode.Metadata.ManagedReference.csproj
Labels: breaking-change

#8374 feat: display C# referenced API name using SymbolDisplay
  src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiReferenceBuildOutput.cs
  src/Microsoft.DocAsCode.Build.UniversalReference/ModelConverter.cs
  src/Microsoft.DocAsCode.DataContracts.Common/SpecViewModel.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Models/ReferenceItem.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/ReferenceItemVisitor.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/YamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/YamlViewModelExtensions.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/ConvertToViewModelUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.-ctor.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/toc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ParameterlessStructConstructors.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ReadOnlyRecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.IGetNext-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.FunctionPointers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.NativeSizedIntegers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Person.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Teacher.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICat.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeChild.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeChildInterface.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeDelegate.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ExplicitLayoutClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
Labels: new-feature

#8377 Update docfx.exe_user_manual.md
  docs/tutorial/docfx.exe_user_manual.md
Labels: documentation

#8372 feat: display C# special types using familiar format
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VBYamlModelGenerator.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/VisitorHelper.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromAssemblyTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/GenerateMetadataFromVBUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyEvent.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyField.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.MyMethod.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.Myroperty.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Extensions/api/MyExample.ExampleClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ConstantInterpolatedStrings.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.Issue7737.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ParameterlessStructConstructors.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.ReadOnlyRecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp10.RecordStruct.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.CheckedUserDefinedOperators-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.RequiredModifier.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.RepeatSequence.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp11.StaticAbstractMembersInInterfaces.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.Nested.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DefaultInterfaceMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.DisposableRefStructs.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Issue4007.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.Misc.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.NullableReferenceTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp8.ReadOnlyMembers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.FunctionPointers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.InitOnlySetters.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.NativeSizedIntegers.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Person.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.Teacher.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CSharp9.RecordTypes.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Cat-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.CatException-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Complex-2.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.FakeDelegate-1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.IAnimal.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICat.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.ICatExtension.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.MRefNormalDelegate.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Tom.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.TomFromBaseClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.ColorType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.ContainersRefTypeChild.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ContainersRefType.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/Microsoft.DevDiv.ExplicitLayoutClass.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/VBTestClass1.BaseClass1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/VBTestClass1.Class1.raw.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Tests/MetadataCommandTest.cs
Labels: new-feature

#8371 Add support for generating multi-level TOC files
  src/Microsoft.DocAsCode.App/Config/MetadataJsonItemConfig.cs
  src/Microsoft.DocAsCode.App/RunMetadata.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/ExtractMetadata/ExtractMetadataOptions.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/ExtractMetadata/TocNamespaceStyle.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataInputModel.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/LayoutCheckAndCleanup.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/YamlMetadataResolver.cs
  src/Microsoft.DocAsCode.Metadata.ManagedReference/YamlViewModelExtensions.cs
  src/docfx/Models/MetadataCommandOptions.cs
  src/docfx/SubCommands/MetadataCommand.cs
  templates/default/styles/docfx.css
  test/docfx.Tests/Assets/test-multinamespace.cs.sample.1
  test/docfx.Tests/MetadataCommandTest.cs
Labels: new-feature
