Repository dotnet/docfx, pull requests merged in 2023-07, with the labels that each got.

#8935 Add default launchSettings.json
  src/docfx/Properties/launchSettings.json
Labels: engineering

#8942 fix: remove tab group hash function
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Aggregator/TabGroupAggregator.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TabGroup/HtmlTabGroupBlockRenderer.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TabGroup/TabGroupBlock.cs
  src/Microsoft.DocAsCode.MarkdigEngine.Extensions/TabGroup/TabGroupIdRewriter.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/GeneralTest.cs
  test/Microsoft.DocAsCode.MarkdigEngine.Extensions.Tests/TabGroupTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: bug-fix

#8931 sign and publish as .NET foundation
  .github/workflows/release.yml
  Directory.Build.props
  publish.yml
Labels: new-feature

#8971 chore: drop Docfx.MarkdigEngine.Validators
  docfx.sln
  src/Docfx.Build.Engine/DocumentBuilder.cs
  src/Docfx.MarkdigEngine.Extensions/Docfx.MarkdigEngine.Extensions.csproj
  src/Docfx.MarkdigEngine.Extensions/Rewriter/MarkdownObjectRewriterFactory.cs
  src/Docfx.MarkdigEngine.Extensions/Rewriter/MarkdownObjectValidatorAdapter.cs
  src/Docfx.MarkdigEngine.Validators/Docfx.MarkdigEngine.Validators.csproj
  src/Docfx.MarkdigEngine.Validators/IMarkdownObjectValidator.cs
  src/Docfx.MarkdigEngine.Validators/IMarkdownObjectValidatorProvider.cs
  src/Docfx.MarkdigEngine.Validators/MarkdownLambdaObjectValidator.cs
  src/Docfx.MarkdigEngine.Validators/MarkdownObjectValidatorFactory.cs
  src/Docfx.MarkdigEngine/Docfx.MarkdigEngine.csproj
  src/Docfx.MarkdigEngine/MarkdigMarkdownService.cs
  src/Docfx.MarkdigEngine/MarkdigServiceProvider.cs
  src/Docfx.MarkdigEngine/Validation/MarkdownValidatorBuilder.cs
  src/Docfx.MarkdigEngine/Validation/TagValidator.cs
  src/Docfx.Plugins/MarkdownTagValidationRule.cs
  test/Docfx.MarkdigEngine.Tests/HtmlMarkdownObjectValidatorProvider.cs
  test/Docfx.MarkdigEngine.Tests/ValidationTest.cs
Labels: breaking-change

#8974 fix: see/seealso tag copies href when a child node exist
  src/Docfx.Dotnet/Resources/XmlCommentTransform.xsl
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: bug-fix

#8973 chore: drop support for md.style
  src/Docfx.Build.ConceptualDocuments/BuildConceptualDocument.cs
  src/Docfx.Build.Engine/HostService.cs
  src/Docfx.Build.SchemaDriven/Processors/MarkdownInterpreter.cs
  src/Docfx.MarkdigEngine/MarkdigMarkdownService.cs
  src/Docfx.MarkdigEngine/Validation/MarkdownValidatorBuilder.cs
  src/Docfx.MarkdigEngine/Validation/Tag.cs
  src/Docfx.MarkdigEngine/Validation/TagValidator.cs
  src/Docfx.MarkdigEngine/Validation/ValidationExtension.cs
  src/Docfx.Plugins/IHostService.cs
  src/Docfx.Plugins/MarkdownStyleConfig.cs
  src/Docfx.Plugins/MarkdownSytleDefinition.cs
  src/Docfx.Plugins/MarkdownTagValidationRule.cs
  src/Docfx.Plugins/MarkdownValidationRule.cs
  src/Docfx.Plugins/MarkdownValidationSetting.cs
  test/Docfx.Build.Engine.Tests/DocumentBuilderTest.cs
  test/Docfx.MarkdigEngine.Tests/ValidationTest.cs
Labels: breaking-change

#8975 fix: display unresolved cref
  samples/seed/dotnet/project/Project/Class1.cs
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  src/docfx/Properties/launchSettings.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.IIssue8948.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.Issue8948.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.Class1.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/BuildFromProject.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#8982 Change dependabot schedule to daily
  .github/dependabot.yml
Labels: engineering

#9000 fix: backport triple colon extension updates
  src/Docfx.MarkdigEngine.Extensions/TripleColon/ChromelessFormExtension.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/CodeExtension.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/ImageExtension.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonBlock.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonBlockParser.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonBlockRenderer.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonExtension.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonInline.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonInlineParser.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/TripleColonInlineRenderer.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/VideoExtension.cs
  src/Docfx.MarkdigEngine.Extensions/TripleColon/ZoneExtension.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/ImageTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/TripleColonTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/VideoTest.cs
  test/Docfx.MarkdigEngine.Tests/InclusionTest.cs
Labels: bug-fix

#9017 feat: disable cert revoke list check using env variable DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  src/Docfx.Build.Engine/XRefMaps/XRefMapDownloader.cs
  src/Docfx.Build.Engine/XrefClient.cs
Labels: new-feature

#9019 chore: Reorganize editorconfig settings
  .editorconfig
Labels: engineering
