Repository dotnet/docfx, pull requests merged in 2023-11, with the labels that each got.

#9366 perf: skip unused scripts in pdf mode
  src/Docfx.App/PdfBuilder.cs
  templates/modern/src/docfx.ts
Labels: performance

#9365 docs: update PDF docs
  .github/workflows/ci.yml
  docs/docs/media/pdf-cover-page.png
  docs/docs/media/pdf-toc-page.png
  docs/docs/pdf.md
  samples/seed/articles/toc.yml
  src/Docfx.App/PdfBuilder.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/toc.verified.json
Labels: documentation

#9369 chore: Add custom file copy logics for template files
  src/Docfx.Build/TemplateProcessors/TemplateProcessor.cs
Labels: new-feature

#9372 fix: some API page child namespaces 404
  samples/seed/dotnet/project/Project/Namespace.cs
  src/Docfx.Dotnet/DotnetApiCatalog.ApiPage.cs
Labels: bug-fix

#9377 feat: update init command
  docs/index.md
  src/docfx/Models/InitCommand.cs
  src/docfx/Models/InitCommandOptions.cs
  src/docfx/Properties/launchSettings.json
Labels: new-feature

#9378 build(deps): bump xunit from 2.5.3 to 2.6.1
  Directory.Packages.props
  test/Docfx.Common.Tests/ConvertToObjectHelperTest.cs
Labels: bug-fix

#9380 fix: gracefully handle toc 404 links for PDF
  src/Docfx.App/PdfBuilder.cs
  src/docfx/Models/InitCommand.cs
  test/docfx.Tests/CommandLineTest.cs
Labels: bug-fix

#9381 perf: print page numbers using PdfPig
  src/Docfx.App/PdfBuilder.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/apipage/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/md/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/restapi/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: performance

#9392 Dockerfile
  Dockerfile
Labels: new-feature

#9401 feat: change some internal types from public to internal
  Directory.Packages.props
  src/Docfx.Build/CompositionContainer.cs
  src/Docfx.Build/Conceptual/BuildConceptualDocument.cs
  src/Docfx.Build/Conceptual/ConceptualDocumentProcessor.cs
  src/Docfx.Build/Conceptual/CountWord.cs
  src/Docfx.Build/Conceptual/HtmlDocumentUtility.cs
  src/Docfx.Build/Conceptual/SeparatedHtmlInfo.cs
  src/Docfx.Build/Conceptual/ValidateConceptualDocumentMetadata.cs
  src/Docfx.Build/FileMetadataConverter.cs
  src/Docfx.Build/ManifestUtility.cs
  src/Docfx.Build/PostProcessors/ExtractSearchIndex.cs
  src/Docfx.Build/PostProcessors/HtmlPostProcessor.cs
  src/Docfx.Build/PostProcessors/PostProcessor.cs
  src/Docfx.Build/PostProcessors/PostProcessorsManager.cs
  src/Docfx.Build/PostProcessors/RemoveDebugInfo.cs
  src/Docfx.Build/PostProcessors/SearchIndexItem.cs
  src/Docfx.Build/PostProcessors/SitemapGenerator.cs
  src/Docfx.Build/PostProcessors/ValidateBookmark.cs
  src/Docfx.Build/ResourceFiles/ResourceDocumentProcessor.cs
  src/Docfx.Build/ResourceFiles/ValidateResourceMetadata.cs
  src/Docfx.Build/TableOfContents/BuildTocDocument.cs
  src/Docfx.Build/TableOfContents/HrefType.cs
  src/Docfx.Build/TableOfContents/TocDocumentProcessor.cs
  src/Docfx.Build/TableOfContents/TocFileType.cs
  src/Docfx.Build/TableOfContents/TocHelper.cs
  src/Docfx.Build/TableOfContents/TocItemInfo.cs
  src/Docfx.Build/TableOfContents/TocResolver.cs
  src/Docfx.Build/TableOfContents/TocRestructureUtility.cs
  src/Docfx.Build/TableOfContents/Utility.cs
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  test/Docfx.Build.SchemaDriven.Tests/LimitationReachedTest.cs
  test/Docfx.Build.SchemaDriven.Tests/SchemaMergerTest.cs
  test/Docfx.Build.Tests/JsonConverterTest.cs
Labels: new-feature

#9405 feat: support DOCFX_PDF_TIMEOUT
  docs/reference/docfx-environment-variables-reference.md
  src/Docfx.App/PdfBuilder.cs
Labels: new-feature

#9408 feat: expand TOC on common URL rewrite rules
  templates/modern/src/helper.test.ts
  templates/modern/src/helper.ts
  templates/modern/src/toc.ts
Labels: new-feature

#9412 feat: add --verbose command line args for verbose logging, drops --repositoryRoot
  src/Docfx.Common/Loggers/ReportLogListener.cs
  src/docfx/Models/CommandHelper.cs
  src/docfx/Models/LogOptions.cs
  test/Docfx.Common.Tests/ReportLoggerListenerTest.cs
Labels: new-feature

#9413 chore: drop log_code from manifest
  src/Docfx.Build.RestApi/Swagger/Internals/JsonLocation/JsonLocationInfo.cs
  src/Docfx.Build/Conceptual/ConceptualDocumentProcessor.cs
  src/Docfx.Build/DocumentBuilder.cs
  src/Docfx.Build/ManifestUtility.cs
  src/Docfx.Common/Loggers/LogCodesLogListener.cs
  src/Docfx.Common/Path/PathUtility.cs
  src/Docfx.Common/StringExtension.cs
  src/Docfx.Plugins/ManifestItem.cs
  test/Docfx.Common.Tests/LogCodesLogListenerTest.cs
Labels: breaking-change

#9418 feat: add start event.
  samples/seed/template/public/main.js
  templates/modern/src/docfx.ts
  templates/modern/src/options.d.ts
Labels: new-feature

#9417 BREAKING CHANGE: drop keepFileLink
  docs/reference/docfx-json-reference.md
  samples/extensions/docfx.json
  src/Docfx.App/Config/BuildJsonConfig.cs
  src/Docfx.App/Helpers/DocumentBuilderWrapper.cs
  src/Docfx.Build/DocumentBuildParameters.cs
  src/Docfx.Build/DocumentBuilder.cs
  src/docfx/Models/BuildCommand.cs
  src/docfx/Models/BuildCommandOptions.cs
  test/docfx.Tests/JsonConverterTest.cs
Labels: breaking-change

#9416 feat: add showLightbox option
  templates/modern/src/markdown.ts
  templates/modern/src/options.d.ts
Labels: new-feature

#9406 feat: add TOC order for toc_rel pick order
  docs/docs/pdf.md
  docs/docs/table-of-contents.md
  samples/seed/articles/toc.yml
  samples/seed/docfx.json
  samples/seed/pdf/cover.md
  samples/seed/pdf/toc.yml
  src/Docfx.Build/SystemMetadataGenerator.cs
  src/Docfx.Build/TableOfContents/TocDocumentProcessor.cs
  src/Docfx.Build/TableOfContents/TocHelper.cs
  src/Docfx.DataContracts.Common/TocItemViewModel.cs
  src/Docfx.DataContracts.Common/TocRootViewModel.cs
  src/Docfx.Dotnet/DotnetApiCatalog.ManagedReference.cs
  src/Docfx.Plugins/TocInfo.cs
  src/docfx/Properties/launchSettings.json
  test/Docfx.Build.Tests/TocDocumentProcessorTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/cover.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/restapi/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/restapi/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/restapi/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/cover.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/restapi/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/restapi/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/restapi/toc.verified.json
  test/docfx.Tests/MetadataCommandTest.cs
Labels: new-feature

#9430 Fix the github actions not working properly in the newest versions of docfx with default settings
  docs/index.md
Labels: documentation

#9460 feat: toggle log severity using rules config
  docs/reference/docfx-json-reference.md
  samples/seed/docfx.json
  src/Docfx.App/Config/DocfxConfig.cs
  src/Docfx.App/Docset.cs
  src/Docfx.Common/Loggers/ConsoleLogListener.cs
  src/Docfx.Common/Loggers/Logger.cs
  src/Docfx.Dotnet/CompilationHelper.cs
  src/Docfx.Dotnet/DotnetApiCatalog.Toc.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/ManagedReference/Visitors/SymbolVisitorAdapter.cs
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  src/Docfx.MarkdigEngine.Extensions/Constants.cs
Labels: new-feature

#9464 fix: log message text break at 80 columns
  src/Docfx.Common/Loggers/ConsoleLogListener.cs
Labels: bug-fix

#9470 fix: affix display problem on ios
  templates/.stylelintrc.json
  templates/modern/src/layout.scss
Labels: bug-fix

#9465 fix: xml indentation issue on external <code>
  src/Docfx.Dotnet/Parsers/XHtmlWriter.cs
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  src/Docfx.Dotnet/Parsers/XmlCommentTransformer.cs
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: bug-fix

#9471 feat: Add option for including explicit interface implementations
  docs/reference/docfx-json-reference.md
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/ManagedReference/ExtractMetadataConfig.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  src/Docfx.Dotnet/SymbolFilter.cs
  src/Docfx.Dotnet/SymbolHelper.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
Labels: new-feature

#9474 fix: only allow first h1 to be the title
  src/Docfx.Build/Conceptual/BuildConceptualDocument.cs
  src/Docfx.Build/Conceptual/HtmlDocumentUtility.cs
  src/Docfx.Build/Conceptual/SeparatedHtmlInfo.cs
  src/Docfx.Build/Conceptual/WordCounter.cs
Labels: bug-fix

#9475 feat: set toc name from title
  docs/docs/table-of-contents.md
  samples/seed/articles/toc.yml
  src/Docfx.Build/ManifestProcessor.cs
  src/Docfx.Build/TableOfContents/TocResolver.cs
  templates/modern/src/helper.ts
  templates/modern/src/toc.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/articles/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Linux/pdf/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/seed.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/articles/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.pdf.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed.Windows/pdf/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: new-feature

#9481 feat: gen TOC name for folder ref or include
  src/Docfx.Build/TableOfContents/BuildTocDocument.cs
  src/Docfx.Build/TableOfContents/TocHelper.cs
  src/Docfx.Build/TableOfContents/TocResolver.cs
  test/Docfx.Tests.Common/TestBase.cs
  test/docfx.Tests/DocsetBuildTest.cs
Labels: new-feature

#9490 fix: PDB symbol link respect disable git features
  src/Docfx.Dotnet/ManagedReference/Visitors/SymbolVisitorAdapter.cs
Labels: bug-fix

#9492 feat: support <exclude /> documentation comment
  docs/docs/dotnet-api-docs.md
  src/Docfx.Dotnet/SymbolFilter.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
Labels: new-feature
