Repository dotnet/docfx, pull requests merged in 2023-06, with the labels that each got.

#8814 fix: re-render mermaid diagrams on tab switch
  samples/seed/articles/markdown.md
  templates/modern/src/markdown.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: bug-fix

#8816 feat: specify global metadata with -m|--metadata arg
  src/docfx/Models/BuildCommand.cs
  src/docfx/Models/BuildCommandOptions.cs
Labels: new-feature

#8828 fix: globalMetadataFiles and fileMetadataFiles not working
  src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs
  src/docfx/Models/OptionMerger.cs
  test/docfx.Tests/DocsetTest.cs
Labels: bug-fix

#8853 fix: theme button not refreshed on change
  docs/extensions/images/material.screenshot.png
  templates/modern/src/nav.ts
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: bug-fix

#8878 chore: update NuGet.Frameworks
  Directory.Packages.props
Labels: engineering

#8885 fix: wrong jquery in default template
  .github/dependabot.yml
  templates/default/src/docfx.vendor.js
  templates/package-lock.json
  templates/package.json
Labels: bug-fix

#8895 Set initial startup project to docfx.csproj
  docfx.sln
Labels: engineering

#8897 chore: enable invarient culture
  Directory.Build.props
  test/Microsoft.DocAsCode.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.CSharp/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/toc.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/xrefmap.verified.yml
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#8908 Typo fix
  docs/index.md
Labels: documentation
