Repository dotnet/docfx, pull requests merged in 2023-08, with the labels that each got.

#9038 fix(modern-template): nav & toc active state breaks with external urls
  samples/seed/articles/toc.yml
  templates/modern/src/helper.ts
  templates/modern/src/nav.ts
  templates/modern/src/toc.ts
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.json.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/toc.verified.json
Labels: bug-fix

#9066 feat: add type definition to REST API pages
  templates/common/RestApi.common.js
  templates/default/partials/rest.child.tmpl.partial
  templates/default/partials/rest.definition.tmpl.partial
  templates/default/partials/rest.tmpl.partial
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/restapi/contacts.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/restapi/petstore.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#9074 perf: Reduce lock wait when checking git command exists or not
  src/Docfx.App/RunBuild.cs
  src/Docfx.Common/Git/GitUtility.cs
Labels: fundamental: performance, new-feature

#9091 chore: Cleanup tests and fix spellings
  src/Docfx.Build.Engine/ManifestProcessor.cs
  src/Docfx.Build.SchemaDriven/OverwriteApplier.cs
  test/Docfx.Build.Engine.Tests/XRefMapDownloaderTest.cs
  test/Docfx.Build.ManagedReference.Tests/ManagedReferenceDocumentProcessorTest.cs
  test/Docfx.Build.SchemaDriven.Tests/LimitationReachedTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/CodeSnippetTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MathematicsTest.cs
  test/docfx.Tests/MetadataCommandTest.cs
Labels: engineering

#9102 chore: Add code coverage excusions
  src/Docfx.Common/Git/GitUtility.cs
Labels: engineering

#9093 feat: option to sort enum member in declaring order
  docs/reference/docfx-json-reference.md
  samples/seed/docfx.json
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataConfig.cs
  src/Docfx.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  src/Docfx.Dotnet/YamlViewModelExtensions.cs
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/CatLibrary.Core.ContainersRefType.ColorType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/api/MRef.Demo.Enumeration.ColorType.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
Labels: new-feature

#9115 feat: Enable DotnetToolMode option when creating nupkg
  src/docfx/Models/TemplateCommand.cs
  src/docfx/docfx.csproj
Labels: new-feature

#9125 fix: toc filter text not reset
  templates/modern/src/toc.ts
Labels: bug-fix

#9132 perf: Optimize read MIME operation
  src/Docfx.Common/YamlMime.cs
Labels: performance

#9130 fix: make blockquote more obvious
  samples/seed/articles/markdown.md
  templates/modern/src/markdown.scss
  test/docfx.Snapshot.Tests/SamplesTest.Seed/articles/markdown.html.view.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.Seed/index.verified.json
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
Labels: bug-fix

#9133 fix: remove document type template bundle warning
  src/Docfx.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs
Labels: bug-fix

#9153 fix: update msbuild.locator to 1.6.1
  Directory.Packages.props
Labels: bug-fix
