Repository dotnet/docfx, pull requests merged in 2024-04, with the labels that each got.

#9828 chore: Add a warning about relative path resolution.
  docs/reference/docfx-json-reference.md
Labels: documentation

#9825 feat: Add DLL references support for file-based API metadata generation
  src/Docfx.Dotnet/CompilationHelper.cs
  src/Docfx.Dotnet/DotnetApiCatalog.Compile.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromVBUnitTest.cs
Labels: new-feature

#9824 perf: Optimize xrefmap.json file deserialization performance
  src/Docfx.Build/XRefMaps/XRefMapDownloader.cs
  src/Docfx.Build/XRefMaps/XRefMapRedirection.cs
  test/Docfx.Build.Tests/TestData/xrefmap.json
  test/Docfx.Build.Tests/XRefMapDownloaderTest.cs
  test/Docfx.Build.Tests/XRefMapSerializationTest.cs
  test/docfx.Tests/Api.verified.cs
Labels: performance

#9759 feat: Support DOCFX_SOURCE_REPOSITORY_URL
  docs/reference/docfx-environment-variables-reference.md
  src/Docfx.Common/Git/GitUtility.cs
  test/Docfx.Common.Tests/GitUtilityWithSourceRepoUrlTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.cs
Labels: new-feature

#9820 feat: Add feature to configure markdig extension by docfx.json configs.
  docs/reference/docfx-json-reference.md
  src/Docfx.MarkdigEngine.Extensions/MarkdigExtensionSetting.cs
  src/Docfx.MarkdigEngine.Extensions/MarkdigExtensionSettingConverter.cs
  src/Docfx.MarkdigEngine.Extensions/MarkdownExtensions.cs
  src/Docfx.MarkdigEngine/MarkdownServiceParameters.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/EmojiTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/GeneralTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/AutoIdentifierTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/AutoLinkTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/EmojiTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/EmphasisExtraTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/MediaLinksTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/PipeTableTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/SmartyPantsTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/TestUtility.cs
  test/docfx.Tests/Api.verified.cs
Labels: new-feature

#9839 chore: Fix `filterconfig.yml` and `enumSortOrder` documentation
  docs/docs/dotnet-api-docs.md
  src/Docfx.Dotnet/MetadataJsonConfig.cs
Labels: documentation

#9850 feat: Enable PreferCSSPageSize option for PDF generation
  src/Docfx.App/PdfBuilder.cs
Labels: new-feature

#9851 fix: PDF `Producer` document information
  src/Docfx.App/PdfBuilder.cs
Labels: bug-fix

#9852 feat: Add docfx JSON Schema files and related tests
  schemas/docfx.schema.json
  schemas/filterconfig.schema.json
  schemas/toc.schema.json
  schemas/xrefmap.schema.json
  src/Docfx.Common/FileMappingItem.cs
  src/Docfx.DataContracts.Common/Constants.cs
  test/docfx.Tests/Api.verified.cs
  test/docfx.Tests/Assets/docfx.json_build/docfx.json
  test/docfx.Tests/Assets/docfx.json_empty/docfx.json
  test/docfx.Tests/Assets/docfx.json_invalid_key/docfx.json
  test/docfx.Tests/Assets/docfx.json_metadata/docfx.json
  test/docfx.Tests/Assets/docfx.json_metadata/docfxWithFilter.json
  test/docfx.Tests/Assets/docfx.json_metadata_build/docfx.json
  test/docfx.Tests/Assets/docfx.sample.1.json
  test/docfx.Tests/JsonSchemaTest.cs
  test/docfx.Tests/Utilities/JsonSchemaUtility.cs
  test/docfx.Tests/Utilities/PathHelper.cs
Labels: new-feature

#9871 Fix typo
  docs/docs/links-and-cross-references.md
Labels: documentation

#9869 fix: Xrefmap baseUrl problem reported at #9866
  src/Docfx.Build/XRefMaps/XRefArchiveBuilder.cs
  src/Docfx.Build/XRefMaps/XRefMapDownloader.cs
  test/Docfx.Build.Tests/XRefMapDownloaderTest.cs
  test/docfx.Tests/Api.verified.cs
Labels: bug-fix

#9880 fix: Xref links are not resolved on docs site
  docs/docfx.json
Labels: documentation, bug-fix

#9881 fix: URL in markdown and match to html example
  docs/docs/links-and-cross-references.md
Labels: documentation

#9883 fix: Change same URL check logic to case invariant
  templates/modern/src/helper.test.ts
  templates/modern/src/helper.ts
Labels: bug-fix

#9884 chore: Improve unresolved xref messages
  src/Docfx.Build/TemplateProcessors/TemplateModelTransformer.cs
Labels: bug-fix

#9895 chore: Fix documentation site build warnings
  docs/docs/markdown.md
  docs/reference/docfx-json-reference.md
  docs/tutorial/intro_overwrite_files.md
  samples/seed/dotnet/solution/CatLibrary/Class1.cs
Labels: documentation

#9894 deps: Update Spectre.Console package versions
  Directory.Packages.props
  src/docfx/Program.cs
Labels: engineering
