Repository dotnet/docfx, pull requests merged in 2024-11, with the labels that each got.

#10395 feat: Use PlantUML Online Server as default configs
  src/Docfx.MarkdigEngine.Extensions/PlantUml/PlantUmlExtension.cs
Labels: new-feature

#10399 fix: Place `.playwright` directory under bin directory
  src/docfx/docfx.csproj
Labels: bug-fix

#10394 docs: Add how to use docfx nightly version
  docs/index.md
Labels: documentation

#10372 feat: Reformat YouTube videos to the embeded URL
  src/Docfx.MarkdigEngine.Extensions/QuoteSectionNote/QuoteSectionNoteRender.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/QuoteSectionNoteTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/VideoTest.cs
Labels: new-feature
