Repository dotnet/docfx, pull requests merged in 2024-06, with the labels that each got.

#9937 feat: permits to specify the placement of overwrites
  Directory.Build.props
  src/Docfx.Common/Docfx.Common.csproj
  src/Docfx.Common/EntityMergers/MergePlacement.cs
  src/Docfx.Common/EntityMergers/ReflectionEntityMerger.cs
  src/Docfx.Common/IItemWithMetadata.cs
  src/Docfx.Dotnet/ManagedReference/Models/ItemViewModel.cs
Labels: new-feature

#9972 Feat/private symbols
  src/Docfx.Dotnet/CompilationHelper.cs
  src/Docfx.Dotnet/DotnetApiCatalog.Compile.cs
  src/Docfx.Dotnet/ManagedReference/Visitors/SymbolVisitorAdapter.cs
Labels: new-feature

#9966 feat: Add support for gzipped xrefmap that stored as local file
  src/Docfx.Build/XRefMaps/XRefMapDownloader.cs
  test/Docfx.Build.Tests/TestData/xrefmap.json.gz
  test/Docfx.Build.Tests/TestData/xrefmap.yml.gz
  test/Docfx.Build.Tests/XRefMapDownloaderTest.cs
Labels: new-feature

#9994 docs: Fix Docfx.App nuget package usage document
  docs/index.md
Labels: documentation

#10030 chore: Remove unused workflow settings
  .github/codeql-config.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
Labels: engineering

#10029 chore: Fix plugin related docs and logs
  docs/tutorial/howto_add_a_customized_post_processor.md
  src/Docfx.App/Helpers/DocumentBuilderWrapper.cs
Labels: documentation

#10023 fix: `docfx metadata` command throw `ArgumentException` when referencing empty namespace by doc comment
  src/Docfx.Dotnet/ManagedReference/Resolvers/YamlMetadataResolver.cs
Labels: bug-fix
