Repository dotnet/docfx, pull requests merged in 2024-03, with the labels that each got.

#9747 feat: percy snapshot
  .github/workflows/ci.yml
  Directory.Packages.props
  test/docfx.Snapshot.Tests/PercyTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1152x648/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/1920x1080/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/375x812/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-BuildFromProject.Class1.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.Cat-2.html-q-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html-term-cat.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/api-CatLibrary.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-csharp_coding_standards.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/index.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/768x600/restapi-petstore.html.verified.png
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.cs
  test/docfx.Snapshot.Tests/docfx.Snapshot.Tests.csproj
Labels: engineering

#9753 chore: Update roslyn packages
  Directory.Packages.props
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  src/Docfx.Dotnet/DotnetApiCatalog.Compile.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
Labels: new-feature

#9754 fix: Broken examples problems when using inheritdoc tag
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
Labels: dotnet: xml-comment, bug-fix

#9786 fix: NullReferenceException occurred when both include and exclude are null
  src/Docfx.Dotnet/Filters/ConfigFilterRuleItemUnion.cs
Labels: bug-fix

#9788 feat: publish nightly pre-release packages
  .github/workflows/nightly.yml
  README.md
Labels: new-feature

#9746 chore: Add detailed error message for specific exceptions
  src/Docfx.Build/HostServiceCreator.cs
Labels: engineering

#9803 chore: update pdfpig nuget package version
  Directory.Packages.props
  src/Docfx.App/PdfBuilder.cs
Labels: engineering

#9807 chore: Change JsonSchema EvaluationOptions instance to shared object
  src/Docfx.Build.SchemaDriven/Validators/SchemaValidator.cs
Labels: bug-fix

#9806 Bug fix Invalid documentation on type parameter #9755
  templates/common/ManagedReference.common.js
Labels: bug-fix

#9810 Update markdown documentation regarding MarkDig extension
  docs/docs/markdown.md
Labels: documentation

#9813 chore: Update `docfx.json` config reference document
  docs/reference/docfx-json-reference.md
  src/Docfx.App/Config/BuildJsonConfig.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
Labels: documentation

#9812 chore: Correct `docfx template` page title
  docs/reference/docfx-cli-reference/docfx-template.md
Labels: documentation
