Repository dotnet/docfx, pull requests merged in 2024-10, with the labels that each got.

#10272 fixed article a/an in config.md
  docs/docs/config.md
Labels: documentation

#10069 chore: Change generated HTML encoding to UTF-8N (without BOM)
  src/Docfx.Build/PostProcessors/HtmlPostProcessor.cs
Labels: breaking-change

#10299 docs: Add node.js as prerequisite
  docs/index.md
  docs/reference/docfx-environment-variables-reference.md
Labels: documentation

#10300 fix: change link as plaintext if API is excluded
  src/Docfx.Dotnet/DotnetApiCatalog.ApiPage.cs
  src/Docfx.Dotnet/ManagedReference/Visitors/SymbolVisitorAdapter.cs
  src/Docfx.Dotnet/ManagedReference/Visitors/YamlModelGenerator.cs
  src/Docfx.Dotnet/SymbolFormatter.cs
  src/Docfx.Dotnet/SymbolUrlResolver.cs
Labels: bug-fix

#10303 fix: suppress assembly load warning for wpf 8.0 project
  src/Docfx.Dotnet/CompilationHelper.cs
Labels: bug-fix

#10239 feat: Add .NET 9 support (and drop .NET 6 support)
  .github/actions/build/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  Directory.Build.props
  Directory.Packages.props
  docs/docs/dotnet-api-docs.md
  docs/index.md
  docs/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.md
  samples/seed/dotnet/project/Project.Core/BuildFromProject.Core.csproj
  samples/seed/dotnet/project/Project/BuildFromProject.csproj
  samples/seed/dotnet/solution/CatLibrary.Core/CatLibrary.Core.csproj
  samples/seed/dotnet/solution/CatLibrary/CatLibrary.csproj
  src/Docfx.App/Docfx.App.csproj
  src/Docfx.Build/Conceptual/WordCounter.cs
  src/Docfx.Build/DocumentBuildContext.cs
  src/Docfx.Build/TableOfContents/TocHelper.cs
  src/Docfx.Build/TemplateProcessors/TemplateManager.cs
  src/Docfx.Build/TemplateProcessors/TemplateProcessor.cs
  src/Docfx.Common/Path/RelativePath.cs
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/SymbolFormatter.Symbols.cs
  src/Docfx.MarkdigEngine/MarkdigMarkdownService.cs
  src/docfx/docfx.csproj
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/docfx.Snapshot.Tests/SamplesTest.SeedMarkdown/CatLibrary.CatException-1.verified.md
  test/docfx.Tests/Assets/multi-frameworks-test.csproj.sample.1
  test/docfx.Tests/Assets/ref.csproj.sample.1
  test/docfx.Tests/Assets/template/plugins/plugins.csproj
  test/docfx.Tests/Assets/test.csproj.sample.1
  test/docfx.Tests/Assets/test.vbproj.sample.1
  test/docfx.Tests/MetadataCommandTest.cs
Labels: new-feature, breaking-change
