Repository dotnet/docfx, pull requests merged in 2024-07, with the labels that each got.

#10051 Remove some enum boxing in GlobMatcher
  src/Docfx.Glob/GlobMatcher.cs
Labels: performance

#10064 chore: Fix json schemas
  schemas/docfx.schema.json
  schemas/filterconfig.schema.json
Labels: bug-fix

#10066 feat: Remove Node.js runtime dependencies from docfx tools
  .github/workflows/release.yml
  Directory.Build.props
  docs/reference/docfx-environment-variables-reference.md
  src/Docfx.App/Docfx.App.csproj
  src/Docfx.App/Helpers/PlaywrightHelper.cs
  src/Docfx.App/PdfBuilder.cs
  test/docfx.Snapshot.Tests/PercyTest.cs
Labels: new-feature

#10082 fix incorrect as usages
  src/Docfx.Build.ManagedReference/SplitClassPageToMemberLevel.cs
  src/Docfx.Common/FileModelParser.cs
Labels: engineering

#10075 remove redundant verbatim strings
  src/Docfx.Build.SchemaDriven/Processors/MarkdownInterpreter.cs
  src/Docfx.Build/TableOfContents/MarkdownTocReader.cs
  src/Docfx.Build/TemplateProcessors/Preprocessors/PreprocessorLoader.cs
  src/Docfx.Build/TemplateProcessors/ViewRenderers/RendererLoader.cs
  src/Docfx.Common/Git/GitUtility.cs
  src/Docfx.Dotnet/Parsers/XmlComment.cs
  src/Docfx.MarkdigEngine.Extensions/ExtensionsHelper.cs
  src/Docfx.MarkdigEngine.Extensions/MarkdigExtensionSetting.cs
  src/Docfx.YamlSerialization/Helpers/Regexes.cs
  test/Docfx.Build.RestApi.Tests/SwaggerJsonParserTest.cs
  test/Docfx.Build.SchemaDriven.Tests/MergeMarkdownFragmentsTest.cs
  test/Docfx.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Docfx.Build.SchemaDriven.Tests/SchemaMergerTest.cs
  test/Docfx.Build.Tests/ConceptualDocumentProcessorTest.cs
  test/Docfx.Build.Tests/DocumentBuilderTest.cs
  test/Docfx.Build.Tests/TemplateManagerUnitTest.cs
  test/Docfx.Build.Tests/TemplateProcessorUnitTest.cs
  test/Docfx.Build.Tests/TocDocumentProcessorTest.cs
  test/Docfx.Build.Tests/ValidateBookmarkTest.cs
  test/Docfx.Common.Tests/PathUtilityTest.cs
  test/Docfx.Common.Tests/YamlDeserializerWithFallbackTest.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromVBUnitTest.cs
  test/Docfx.Dotnet.Tests/XmlCommentUnitTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/AggregatorTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/ChromelessFormsTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/CodeSnippetTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/GeneralTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/InteractiveCodeTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/LineNumberTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/AutoIdentifierTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/AutoLinkTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/EmojiTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/MarkdigBuiltinExtensionTests/EmphasisExtraTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/NolocTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/QuoteSectionNoteTest.cs
  test/Docfx.MarkdigEngine.Tests/InclusionTest.cs
  test/Docfx.MarkdigEngine.Tests/MarkdigServiceTest.cs
Labels: engineering

#10074 remove redundant Directory.GetCurrentDirectory
  src/docfx/Models/BuildCommand.cs
  src/docfx/Models/MergeCommand.cs
Labels: engineering

#10093 chore: Update docker file
  Dockerfile
Labels: new-feature

#10081 remove redundant members
  src/Docfx.App/RunMerge.cs
  src/Docfx.Build/DocumentBuildContext.cs
  src/Docfx.Build/TableOfContents/BuildTocDocument.cs
  src/Docfx.Build/TemplateProcessors/Template.cs
  src/Docfx.MarkdigEngine.Extensions/CodeSnippet/CodeSnippetParser.cs
  src/Docfx.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs
  src/Docfx.MarkdigEngine.Extensions/ExtensionsHelper.cs
  test/Docfx.Build.SchemaDriven.Tests/SchemaDrivenProcessorTest.cs
  test/Docfx.Build.Tests/DocumentBuilderTest.cs
  test/Docfx.Build.Tests/TemplateManagerUnitTest.cs
  test/Docfx.Tests.Common/TestBase.cs
  test/docfx.Tests/DocsetBuildTest.cs
  test/docfx.Tests/JsonSchemaTest.cs
Labels: engineering

#10073 chore: source code improvements
  src/Docfx.Build/CompilePhaseHandler.cs
  src/Docfx.Build/DocumentBuilder.cs
  src/Docfx.Dotnet/DotnetApiCatalog.ApiPage.cs
  src/Docfx.Dotnet/DotnetApiCatalog.ManagedReference.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
Labels: engineering

#10100 fix: PDF Header/Footer pages size
  src/Docfx.App/PdfBuilder.cs
Labels: bug-fix

#10099 feat: pdfHeaderTemplate/pdfFooterTemplate supports value as file path
  docs/docs/pdf.md
  src/Docfx.App/PdfBuilder.cs
Labels: new-feature

#10090 feat: expose type through the toc
  src/Docfx.DataContracts.Common/TocItemViewModel.cs
  src/Docfx.Dotnet/YamlViewModelExtensions.cs
  templates/default/toc.html.primary.js
  templates/default/toc.json.js
  test/docfx.Tests/Api.verified.cs
Labels: new-feature

#10107 chore: Fix build error on .NET 9 SDK preview6
  Directory.Packages.props
  src/Docfx.Common/Docfx.Common.csproj
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  test/Docfx.Build.Tests/XRefMapDownloaderTest.cs
Labels: engineering
