Repository dotnet/docfx, pull requests merged in 2024-01, with the labels that each got.

#9575 chore: Fix picture image click event handling
  templates/modern/src/markdown.ts
Labels: bug-fix

#9574 Added extensions configuration point and PlantUml support
  Directory.Packages.props
  src/Docfx.MarkdigEngine.Extensions/Docfx.MarkdigEngine.Extensions.csproj
  src/Docfx.MarkdigEngine.Extensions/MarkdownContext.cs
  src/Docfx.MarkdigEngine.Extensions/MarkdownExtensions.cs
  src/Docfx.MarkdigEngine.Extensions/PlantUml/PlantUmlCodeBlockRenderer.cs
  src/Docfx.MarkdigEngine.Extensions/PlantUml/PlantUmlExtension.cs
  src/Docfx.MarkdigEngine.Extensions/QuoteSectionNote/QuoteSectionNoteExtension.cs
  src/Docfx.MarkdigEngine/MarkdigMarkdownService.cs
  src/Docfx.Plugins/MarkdownServiceParameters.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/PlantUmlTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/QuoteSectionNoteTest.cs
  test/Docfx.MarkdigEngine.Extensions.Tests/TestUtility.cs
  test/Docfx.MarkdigEngine.Tests/MarkdigServiceTest.cs
  test/Docfx.MarkdigEngine.Tests/TestUtility/TestUtility.cs
  test/docfx.Tests/Api.verified.cs
  test/docfx.Tests/JsonConverterTest.cs
Labels: new-feature

#9586 fix: warn on PDF timeout
  src/Docfx.App/PdfBuilder.cs
Labels: bug-fix

#9585 feat: support description metadata
  src/Docfx.Build/SystemMetadata.cs
  templates/default/partials/head.tmpl.partial
  templates/modern/layout/_master.tmpl
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-csharp_coding_standards.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/articles-markdown.html-tabs-windows-2Ctypescript-markdown-extensions.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/index.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/restapi-petstore.html.verified.html
Labels: new-feature

#9600 Update documentation readme
  README.md
Labels: documentation

#9605 Fix japanese search
  templates/modern/src/search-worker.ts
Labels: bug-fix

#9607 Updated docs to include PlantUML extension
  docs/docs/markdown.md
Labels: documentation

#9610 fix: remove PDF missing TOC warning
  src/Docfx.App/PdfBuilder.cs
Labels: bug-fix

#9615 Markdig extensions configuration/support documentation
  docs/docs/markdown.md
Labels: documentation

#9637 pref: Optimize xrefmap download performance
  src/Docfx.Build/XRefMaps/XRefMapDownloader.cs
Labels: performance

#9633 fix: new line in mref title
  templates/default(zh-cn)/partials/title.tmpl.partial
  templates/default/partials/title.tmpl.partial
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-BuildFromProject.Class1.html.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.Cat-2.html-q-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html-term-cat.verified.html
  test/docfx.Snapshot.Tests/SamplesTest.SeedHtml/html/api-CatLibrary.html.verified.html
Labels: bug-fix

#9654 chore: Update YamlDotNet version
  Directory.Packages.props
  src/Docfx.YamlSerialization/NodeDeserializers/EmitGenericCollectionNodeDeserializer.cs
  src/Docfx.YamlSerialization/NodeDeserializers/ExtensibleObjectNodeDeserializer.cs
  src/Docfx.YamlSerialization/YamlDeserializer.cs
  src/Docfx.YamlSerialization/YamlSerializer.cs
Labels: engineering

#9648 fix: Corrected class name in inheritedMembers block
  templates/modern/partials/class.header.tmpl.partial
Labels: bug-fix

#9650 fix: ApiPage is not generated when multiple namespaces defined across projects
  src/Docfx.Dotnet/DotnetApiCatalog.Toc.cs
Labels: bug-fix
