Repository dotnet/docfx, pull requests merged in 2024-05, with the labels that each got.

#9909 feat: Enable view transitions feature
  templates/.stylelintrc.json
  templates/modern/src/docfx.scss
Labels: static-site

#9913 chore: Fix nightly build errors
  src/Docfx.Build/PostProcessors/PostProcessorsManager.cs
  test/Docfx.Common.Tests/ConvertToObjectHelperTest.cs
Labels: bug-fix

#9912 fix: TOC filter value is not shared between pages
  templates/modern/src/toc.ts
Labels: bug-fix

#9922 Fix: Build problems when running .NET 6 version of docfx on some environment
  Directory.Packages.props
  src/Docfx.Dotnet/Docfx.Dotnet.csproj
  src/Docfx.Dotnet/DotnetApiCatalog.cs
Labels: bug-fix

#9935 docs: Fix missing docfx.json config docs
  docs/reference/docfx-json-reference.md
Labels: documentation

#9942 chore: fix NU5129 warning on `dotnet pack` command
  src/Docfx.App/Build/Docfx.App.props
  src/Docfx.App/Docfx.App.csproj
Labels: engineering

#9953 feat: Add `toc.json` transform logics using `toc.extension.js`
  templates/default/toc.extension.js
  templates/default/toc.json.js
Labels: new-feature

#9960 chore: Add PolySharp libarary to use latest C# syntax
  Directory.Build.props
  Directory.Packages.props
  src/Docfx.Build/ApiPage/ApiPage.cs
  src/Docfx.Build/ApiPage/ApiPageHtmlTemplate.cs
  src/Docfx.Build/ApiPage/ApiPageMarkdownTemplate.cs
  src/Docfx.Build/ApiPage/ApiPageProcessor.cs
  src/Docfx.Build/DocumentBuilder.cs
  src/Docfx.Dotnet/DotnetApiCatalog.ApiPage.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
Labels: engineering

#9957 feat(xml): better error when link not found
  src/Docfx.Dotnet/Parsers/XmlComment.cs
Labels: new-feature

#9965 feat: Add `categoryLayout` option for metadata generation
  docs/reference/docfx-json-reference.md
  schemas/docfx.schema.json
  src/Docfx.Dotnet/DotnetApiCatalog.Toc.cs
  src/Docfx.Dotnet/DotnetApiCatalog.cs
  src/Docfx.Dotnet/ManagedReference/ExtractMetadataConfig.cs
  src/Docfx.Dotnet/MetadataJsonConfig.cs
  src/docfx/Models/MetadataCommand.cs
  src/docfx/Models/MetadataCommandOptions.cs
Labels: new-feature
