Repository dotnet/docfx, pull requests merged in 2024-02, with the labels that each got.

#9665 fix: Toc warnings when toc item with TopicUid but name is not specified
  src/Docfx.Build/ManifestProcessor.cs
Labels: bug-fix

#9689 build(deps): bump YamlDotNet from 15.1.0 to 15.1.1 dependencies .NET
  Directory.Packages.props
  src/Docfx.YamlSerialization/YamlSerializer.cs
Labels: engineering

#9693 chore: update NuGet package dependencies (Microsoft.NET.Test.Sdk,Microsoft.Build.Locator)
  Directory.Packages.props
Labels: engineering

#9698 chore: Update Microsoft.Build package version
  Directory.Packages.props
Labels: engineering

#9666 fix: filterconfig exclude rule is not works as documented
  src/Docfx.Dotnet/Filters/ConfigFilterRuleItemUnion.cs
  src/Docfx.Dotnet/Filters/ExtendedSymbolKind.cs
  test/Docfx.Dotnet.Tests/ApiFilterUnitTest.cs
  test/Docfx.Dotnet.Tests/TestData/filterconfig_docs_sample.yml
Labels: bug-fix

#9707 feat: Add DefineConstants supports for source file based build
  src/Docfx.Dotnet/CompilationHelper.cs
  src/Docfx.Dotnet/DotnetApiCatalog.Compile.cs
  test/Docfx.Dotnet.Tests/ApiFilterUnitTest.cs
  test/Docfx.Dotnet.Tests/DefinitionMergeUnitTest.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromVBUnitTest.cs
Labels: new-feature

#9708 docs: Split docfx CLI reference docs based on commands
  docs/docs/toc.yml
  docs/reference/docfx-cli-reference.md
  docs/reference/docfx-cli-reference/docfx-build.md
  docs/reference/docfx-cli-reference/docfx-download.md
  docs/reference/docfx-cli-reference/docfx-init.md
  docs/reference/docfx-cli-reference/docfx-merge.md
  docs/reference/docfx-cli-reference/docfx-metadata.md
  docs/reference/docfx-cli-reference/docfx-pdf.md
  docs/reference/docfx-cli-reference/docfx-serve.md
  docs/reference/docfx-cli-reference/docfx-template.md
  docs/reference/docfx-cli-reference/docfx.md
  docs/reference/docfx-cli-reference/overview.md
  docs/reference/docfx-cli-reference/toc.yml
  src/docfx/Models/BuildCommandOptions.cs
Labels: documentation

#9723 deps: Update nuget packages dependencies
  Directory.Packages.props
Labels: engineering

#9713 fix: Resolved .NET SDK version problem on source-based API metadata generation
  src/Docfx.Dotnet/CompilationHelper.cs
  test/Docfx.Dotnet.Tests/GenerateMetadataFromCSUnitTest.cs
Labels: bug-fix

#9737 feat: Add additional layout options to modern template
  docs/docs/template.md
  templates/modern/layout/_master.tmpl
  templates/modern/src/layout.scss
  templates/modern/src/nav.ts
Labels: new-feature

#9742 Added pdfPrintBackground setting
  docs/docs/pdf.md
  src/Docfx.App/PdfBuilder.cs
Labels: new-feature
